### ISSUE TITLE
我是刚建的一个weex 用官方的tookit,然后weex src/index.vue，报错 Uncaught SyntaxError: Unexpected token export；放到安卓手机里不显示

### ISSUE THREAD

**Issue by goodmanman** [alibaba/weex-ui#10]
<template>
  <div class="wrapper" @click="update">
    <text class="title">Hell123123o {{target}}</text>
    <text class="desc">Now, let's use vue to build your weex app.</text>
    <div>
	    <wxc-button text="Open Popup" ></wxc-button>
	    <wxc-popup width="500"
	               pos="left"
	               ></wxc-popup>
	  </div>
  </div>
</template>

<style>
  .wrapper { align-items: center; margin-top: 120px; }
  .title { padding-top:40px; padding-bottom: 40px; font-size: 48px; }
  .logo { width: 360px; height: 156px; }
  .desc { padding-top: 20px; color:#888; font-size: 24px;}
</style>

<script>
	import { WxcButton, WxcPopup } from 'weex-ui';
  export default {
    data: {
      target: 'World'
    },
    components: { WxcButton, WxcPopup },
    methods: {
      update: function (e) {
        this.target = 'Weex'
        console.log('target:', this.target)
      },
     
    }
  }
</script>

**Comment by tw93** [comment]
update the weex-toolkit to latest 
and more info you can see  https://github.com/alibaba/weex-ui#weex-toolkit

**Comment by goodmanman** [comment]
![em _20171010191258](https://user-images.githubusercontent.com/20736213/31383875-3ae7c8ac-adef-11e7-9ce4-be2b97bbc52d.png)
![em _20171010191313](https://user-images.githubusercontent.com/20736213/31383876-3b17a388-adef-11e7-8391-4f07f6fbcc75.png)

**Comment by goodmanman** [comment]
我已经更新了，还是报错，问什么呢
![em _2017101019154](https://user-images.githubusercontent.com/20736213/31383960-91c55e82-adef-11e7-9393-104a2c030269.png)

**Comment by tw93** [comment]
it is very like this case：https://github.com/alibaba/weex-ui/issues/3
@erha19  You need to speed up the problem 😊

**Comment by goodmanman** [comment]
感谢。我已经看了#3 了。同样的问题，坐等更新

**Comment by erha19** [comment]
@goodmanman try `weex update weex-previewer@latest`.

**Comment by goodmanman** [comment]
![qq 20171010220843](https://user-images.githubusercontent.com/20736213/31391109-35564a6c-ae08-11e7-8dc4-ec413a7d2c65.png)

这回直接报错

**Comment by erha19** [comment]
@goodmanman 1.3.13 is a problematic version, please run `weex update weex-previewer@1.3.12`to install prev version.

**Comment by goodmanman** [comment]
This doesn't work ，same question ，waiting for the update ,thank you ~

**Comment by erha19** [comment]
@goodmanman I updated a new version to fix your problem, try `weex update weex-previewer@1.3.13-beta.1`.

**Comment by goodmanman** [comment]
same question , this doesn't work 
![111](https://user-images.githubusercontent.com/20736213/31444098-c778a9b0-aecd-11e7-89ef-9ca65551bb25.png)

**Comment by erha19** [comment]
Try `weex update weex-previewer@1.3.13-beta.3`, this version has fixed it.

**Comment by tw93** [comment]
weex update weex-previewer
![jietu20171012-173649](https://user-images.githubusercontent.com/8736212/31489722-3ad4d238-af07-11e7-9ae0-b7cf69415c24.jpg)

**Comment by huangying1111** [comment]
weex debug still wrong

**Comment by erha19** [comment]
You'd also need to upgrade your `weex-devtool` to 0.3.2-beta.7.

**Comment by huangying1111** [comment]
- weex-devtool : v0.3.2-beta.7
 - weex-previewer : v1.3.13-beta.3
 'Uncaught Error: Uncaught SyntaxError: Unexpected token export' 

 so sad

**Comment by thecorsair** [comment]
环境  
 v1.1.0-beta.1
 - weexpack : v0.4.7-beta.8
 - weex-builder : v0.2.13-beta.2
 - weex-devtool : v0.3.2-beta.7
 - weex-previewer : v1.3.13-beta.3

mac 正常
windows 依然  'Uncaught Error: Uncaught SyntaxError: Unexpected token export'

**Comment by erha19** [comment]
@thecorsair Thanks, I will try to fix it in next version of `weex-devtool`.

**Comment by marekchen** [comment]
@erha19 
weex -v
   v1.1.0-beta.6
 - weexpack : v0.4.7-beta.20
 - weex-builder : v0.2.13-beta.4
 - weex-devtool : v0.3.2-beta.9
 - weex-previewer : v1.3.13-beta.9
still has this error.
more detail please see #50

**Comment by AugTang** [comment]
具体解决方案是什么

**Comment by AugTang** [comment]
C:\Users\myth>weex update weex-previewer@1.3.13-beta.
? update package "weex-previewer" now? Yes
npm ERR! code ETARGET
npm ERR! notarget No matching version found for weex-previewer@1.3.13-beta.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\myth\AppData\Roaming\npm-cache\_logs\2018-01-10T02_04_57_953Z-debug.log

您说的两条命令都用了，还是报错，求解决
 @erha19

**Comment by AugTang** [comment]
![image](https://user-images.githubusercontent.com/31499235/34752668-aef880fa-f5ee-11e7-8984-e3e561feb8b2.png)

您说的两条命令都用了，还是报错，求解决
@ erha19

**Comment by AugTang** [comment]
![image](https://user-images.githubusercontent.com/31499235/34752891-e0283af2-f5ef-11e7-90c4-709e7bae0179.png)
@erha19 还是报错，我已经是最新版的了

**Comment by tw93** [comment]
https://alibaba.github.io/weex-ui/#/cn/with-weex-toolkit
