### ISSUE TITLE
Need local sources

### ISSUE THREAD

**Issue by chencl1986** [alibaba/weex-ui#100]
##### 1.Your development environment（weex、weex-toolkit、system and more).    
 - weex-ui 0.3.9beta

##### 2.Expected behavior and actual behavior.   
 - Weex-ui use the icon address as https://gw.alicdn.com/tfs/TB1x18VpwMPMeJjy1XdXXasrXXa-21-36.png.
 - But our projects need to use local image resources, Because we don't allow to visit internet.
 - Could you please to provide local resources version?

**Comment by tw93** [comment]
Thank you for your feedback. I will conduct research and implementation on this issue

**Comment by chencl1986** [comment]
Thank you very much.

**Comment by tw93** [comment]
Weex's native runtime support load image file from device's disk, all you have to do set the file url like file:///sdcard/image_new0.png. 
As to load image file in your project,**Weex is not support yet.**

Also It seems to be a bit of a problem on android when using `base64`

https://github.com/alibaba/weex/blob/doc/doc/faq.md#use-local-image
https://github.com/alibaba/weex/issues/74
http://dotwe.org/vue/e0dd098a0b4d0da00c7195dc7b01b0e7

What weex-ui can be done is to support the configuration of the image,What do you think?
