### ISSUE TITLE
是否支持钉钉？

### ISSUE THREAD

**Issue by sum1201** [alibaba/weex-ui#101]
钉钉官方文档提到可以 使用weex 构建三端应用(参见：https://open-doc.dingtalk.com/docs/doc.htm?spm=a219a.7629140.0.0.eWw5Vd&treeId=357&articleId=107060&docType=1）
根据 钉钉 CLI 创建的引用，可以使用 weex ui 吗？ 
能否提供继承教程。
谢谢

**Comment by tw93** [comment]
- Yes, but you need modify some config
- Add a `exclude` in `build/webpack.base.weex.conf.js` Like this:

  ```
  module: {
      rules: [
        {
          test: /\.vue(\?[^?]+)?$/,
          loaders: ['weex-loader'],
          exclude: /node_modules(?!(\/|\\).*(weex).*)/
        },
        {
          test: /\.js$/,
          loaders: ['babel-loader'],
          exclude: /node_modules(?!(\/|\\).*(weex).*)/
        }
      ]
    }
  ```
- Please add 'babel-preset-stage-0' and 'babel-plugin-component' to .babelrc
  
  > npm i babel-plugin-component babel-preset-stage-0  -D
  
  Edit the `.babelrc` like this
  
  ```
  {
    "presets": ["es2015", "stage-0"],
    "plugins": [
      [
        "component",
        {
          "libraryName": "weex-ui",
          "libDir": "packages",
          "style": false
        }
      ]
    ]
  }
 ```
