### ISSUE TITLE
能提供下例子中的wxc-city的源码吗

### ISSUE THREAD

**Issue by heiren0926** [alibaba/weex-ui#102]
能提供下例子中的wxc-city的源码吗

**Comment by tw93** [comment]
有计划开源，但是目前通用城市列表的数据还在整合

**Comment by tw93** [comment]
可以更新组件到0.3.10最新版本
详细使用可见 https://github.com/alibaba/weex-ui/blob/master/packages/wxc-city/README_cn.md
