### ISSUE TITLE
weex-styler验证到部分样式语法有问题

### ISSUE THREAD

**Issue by lerit** [alibaba/weex-ui#104]
升级了部分weex和vue的包版本后，编译项目报错，提示
`'./node_modules/weex-vue-loader/lib/style-loader.js!./node_modules/weex-vue-loader/lib/style-rewriter.js?id=data-v-63bed4b2!./node_modules/weex-vue-loader/lib/selector.js?type=styles&index=0!./node_modules/weex-ui/packages/wxc-cell/index.vue\n(Emitted value instead of an instance of Error) NOTE: property value `relative` is the DEFAULT value for `position` (could be removed)`
应该是从weex-styler验证样式语法报出来的错，提示relative为默认属性，无需设置。

**Comment by tw93** [comment]
谢谢反馈
怎么升级的？
列一下具体的版本号码哦

**Comment by lerit** [comment]
我一下升级了6个包，不太清楚是哪个导致的（我的web和weex项目是一个，所以下面有些包可能跟weex没太相关）：
 "vue": "^2.5.9",-"vue": "^2.5.13",
 "vue-loader": "^13.5.0",-"vue-loader": "^13.6.1",
"vue-template-compiler": "^2.5.9",-"vue-template-compiler": "^2.5.13",
"weex-loader": "^0.6.0-beta.3",-"weex-loader": "^0.6.7",
"weex-ui": "^0.3.2",-"weex-ui": "^0.3.9-beta1",
"weex-vue-render": "^0.12.25"-"weex-vue-render": "^0.12.27"

**Comment by lerit** [comment]
只需要移除wxc-cell/index.vue中position: relative;就不报错了

**Comment by tw93** [comment]
@lerit   更新weex-ui 到 weex-ui@0.3.10-beta1

**Comment by lerit** [comment]
谢啦！

**Comment by lerit** [comment]
wxc-minibar/index.vue也报警告了，要求色值 为6位。
 warning  in ./node_modules/weex-ui/packages/wxc-minibar/index.vue
property value `#fff` is autofixed to `#ffffff`

**Comment by tw93** [comment]
@lerit  警告可以暂时不管  我理解这一块weex-style是会帮助代码转换的 我下一个版本修复

**Comment by lerit** [comment]
好的明白了
