### ISSUE TITLE
在indexlist组件加入minibar组件后，出现滚动

### ISSUE THREAD

**Issue by janxy** [alibaba/weex-ui#105]
##### 1.Your development environment（weex、weex-toolkit、system and more).    
 - 
 - 

##### 2.Expected behavior and actual behavior.   
 - 在indexlist组件加入minibar组件后，出现滚动
 - 是否能自适应或者可以手动更改？

##### 3.Steps to reproduce the problem.    
 - 在indexlist例子中加入minibar组件
 -

**Comment by tw93** [comment]
贴一下代码

**Comment by janxy** [comment]
<template>
  <div class="container">
  	 <wxc-minibar title="title"
                   background-color="#009ff0"
                   text-color="#FFFFFF"></wxc-minibar>
    <wxc-indexlist :normal-list="list.normalList"
                   :hot-list-config="hotListConfig"
                   :city-location-config="cityLocationConfig"
                   @wxcIndexlistItemClicked="wxcIndexlistItemClicked"
                   :show-index="showIndex"></wxc-indexlist>
  </div>
</template>

**Comment by janxy** [comment]
`<template>
  <div class="container">
  	 <wxc-minibar title="title"
                   background-color="#009ff0"
                   text-color="#FFFFFF"></wxc-minibar>
    <wxc-indexlist :normal-list="list.normalList"
                   :hot-list-config="hotListConfig"
                   :city-location-config="cityLocationConfig"
                   @wxcIndexlistItemClicked="wxcIndexlistItemClicked"
                   :show-index="showIndex"></wxc-indexlist>
  </div>
</template>`

**Comment by janxy** [comment]
![111](https://user-images.githubusercontent.com/10809790/34344133-32a51aa4-ea1d-11e7-9558-5dd6cb010e25.jpg)

**Comment by tw93** [comment]
也即需要minibar和indexlist一起滚动暂时应该是不支持的
因为indexlist里面其实就是一个list
在下一个版本加入一个自定义slot 让你配置即可

**Comment by janxy** [comment]
咨询下，下个版本什么时候更新呢。
随便咨询下。如果通过indexlist点击后返回到上一页面，然后上一页面更新数据，这个是用什么做的呢，能否给个建议方向。

**Comment by tw93** [comment]
更新组件到 weex-ui@0.3.10-beta2 ，详细可见文档
https://github.com/alibaba/weex-ui/blob/dev/packages/wxc-indexlist/README_cn.md#slot

> npm i weex-ui@0.3.10-beta2 -S


>如果通过indexlist点击后返回到上一页面，然后上一页面更新数据，这个是用什么做的呢，能否给个建议方向
点击后有一个回调，在里面navigator.pop回去上一个页面，然后上一个页面监听页面变化，来更新即可
http://weex-project.io/cn/references/common-event.html#Page-%E4%BA%8B%E4%BB%B6

**Comment by janxy** [comment]
谢谢，navigator.pop试过可以了。但是navigator.pop传参数要怎么传呢，我想过用storage一起配合，不知道这种方法可行不

**Comment by tw93** [comment]
按理说不支持传参 建议使用storage 
详细文档 https://weex-project.io/cn/faq.html#%E5%A6%82%E4%BD%95%E5%9C%A8-pages-%E4%B9%8B%E9%97%B4%E4%BC%A0%E9%80%92%E6%95%B0%E6%8D%AE

**Comment by janxy** [comment]
大神，问个其他问题：
weex market里面的插件比如amap这个插件，他都是早期.WE版本的，放在现在都用不了，请问有什么好的解决方案嘛，或者其他地图?或者可以改成现在版本可以用的 ·
谢谢。。。

**Comment by tw93** [comment]
@janxy   请不要在一个不相关的issue里面问其他不相关问题，可以在钉钉群中讨论这种类似问题
