### ISSUE TITLE
天猪其他的小伙伴哪去了？只有一个人维护，开放的组件太少，更新的速度太慢，组件的属性和方法命名不能理解，当然还是得谢谢阿里的同学们的辛苦和贡献。

### ISSUE THREAD

**Issue by tong3jie** [alibaba/weex-ui#106]

**Comment by tw93** [comment]
weex-ui 是从阿里飞猪这边还有其他业务线抽离出来然后刨除阿里元素的weex-ui组件库
目前开放的组件已经有30个，自认为已经很多了..
不过还是有部分组件正在开发中
从930发布一来 已经累计迭代20个大小版本，详细可见https://github.com/alibaba/weex-ui/releases
自认为速度还可以哦
关于组件的属性和方法命名是使用统一规范 尽量和weex和vue的开发习惯靠拢，如果有疑问，可以开issue一起讨论。

同时[维护开源](https://nolanlawson.com/2017/03/05/what-it-feels-like-to-be-an-open-source-maintainer/)工作是很辛苦的工作，作为一个免费的开源项目，weex-ui的维护人员必然是有限的，开源项目的用户和维护者之间并不是甲方和乙方的关系，反而是大家可以一起来提交pr，共同促进其发展。

**Comment by zsmjhtn** [comment]
期待早日支持复杂交互，比如touch事件的细分，不然不能做拖拽布局的复杂交互。另外动画过程中目前也不支持实时的callback，想在动画中设置eg：opciaty也还不行。干巴得
