### ISSUE TITLE
安装weex-ui后运行报错Module not found: Error: Can't resolve 'weex-ui/packages/wxc-lightbox/style.css' in 'G:\个人项目\weex-start-kit-master\Web\src\demo'

### ISSUE THREAD

**Issue by ONZHEWAY** [alibaba/weex-ui#108]
##### 1.Your development environment（weex、weex-toolkit、system and more).    
 - weex
 - win10

##### 2.Expected behavior and actual behavior.   
 - 使用weex-ui内的demo
 - 运行后报错

##### 3.Steps to reproduce the problem.    
 - 安装weex-ui后运行报错Module not found: Error: Can't resolve 'weex-ui/packages/wxc-lightbox/style.css' in 'G:\个人项目\weex-start-kit-master\Web\src\demo'
 -

**Comment by tw93** [comment]
由于 babel-plugin-component有一个大版本升级，新加入了style，需要在原有.babelrc中加入`"style": false`

```
// add a plugins setting to .babelrc
{
  "plugins": [
    [
      "component",
      {
        "libraryName": "weex-ui",
        "libDir": "packages",
        "style": false
      }
    ]
  ]
}
```
