### ISSUE TITLE
wxc-tab-page的示例不能左右滑动

### ISSUE THREAD

**Issue by hongweiqu** [alibaba/weex-ui#11]
wxc-tab-page的示例用Weex Playground不能左右滑动，但在tmall是可以的，请问什么原因。

**Comment by tw93** [comment]
This issue is same as https://github.com/alibaba/weex-ui/issues/6 
 The left and right slide attributes depend on expressionBinding，the feature is not included in weex_sdk for now, but we plan to open source it later this year
