### ISSUE TITLE
radio问题

### ISSUE THREAD

**Issue by AutumnDeSea** [alibaba/weex-ui#110]
版本号:"weex-ui": "^0.3.9-beta1",
`  getNextCategoryCrm({
          'cateGoryParentId': this.secondCategorys[0].id,
        }, res => {
          this.thirdCategorys = [];
          res.data.data.forEach((item, index) => {
            if (index == 0) {
              this.thirdCategorys.push({
                title: item.documentCName.split(' ')[1],
                value: item.documentCNameHeader,
                checked: true,
                id: item.id,
              })
            } else {
              this.thirdCategorys.push({
                title: item.documentCName.split(' ')[1],
                value: item.documentCNameHeader,
                checked: false,
                id: item.id,
              });
            }
          });
        })`
如此,带你出来的thirdCategorys里面的所有checked 都是fasle

**Comment by tw93** [comment]
Thank you for your feedback. I've been working on a forthcoming release, and you can upgrade to weex-ui@0.3.11-beta1 for the time being.

> npm i weex-ui@0.3.11-beta1 -S
