### ISSUE TITLE
wxc-mask content内容 绑定data数据 

### ISSUE THREAD

**Issue by wilson-0422** [alibaba/weex-ui#111]
content的通过data绑定的数据，再通过click来改变的时候，会让wxc的弹框消失
//html
 <wxc-mask height="800"
                width="702"
                border-radius="0"
                duration="300"
                mask-bg-color="#FFFFFF"
                :has-overlay="true"
                :show-close="true"
                :show="show"
                :has-animation="hasAnimation"
                @wxcMaskSetHidden="wxcMaskSetHidden">
        <div class="content">
          <div class="demo-title">
            <image src="http://cdn.udian.me/code_tiao.png" style="width: 270px;height: 130px;"></image>
          </div>
          <div class="demo-input">
            **<text class="input-text">{{input_text}}</text>**
 **<div class="grid-option" @click="edit_input(1)" bubble="false"><text class="text-title">1</text></div>**

//.js
 edit_input (e) {
        this.input_text = '2323'
        console.log(this.input_text)
      },

点击事件去改变this的data值，渲染页面的时候，会让弹框消失

**Comment by tw93** [comment]
Thank you for your feedback. I've been working on a forthcoming release, and you can upgrade to weex-ui@0.3.11-beta for the time being.

> npm i weex-ui@0.3.11-beta -S

**Comment by wilson-0422** [comment]
真机测试。。。弹框会有闪屏……

**Comment by tw93** [comment]
try `:has-animation="false"`

**Comment by wilson-0422** [comment]
那不是用不了动画了……
:hack="shouldShow"
这个是什么机制？好像是这个影响的

**Comment by esappear** [comment]
闪屏的问题只能靠把动画禁掉解决吗？而且即便禁掉动画，弹窗内部数据更新的时候还是会闪屏。

**Comment by DorisOu** [comment]
@wilson-0422 :hack="shouldShow" 是那个weex-ui组件的配置啊？找不到

**Comment by b1003572686** [comment]
你好,关闭动画后安卓手机上更新数据 还是会闪动,iOS没这个问题

**Comment by b1003572686** [comment]
[1570762087578893.mp4.zip](https://github.com/alibaba/weex-ui/files/3715460/1570762087578893.mp4.zip)
