### ISSUE TITLE
preview时提示语法错误，扫码预览时 出现error render error:-2013

### ISSUE THREAD

**Issue by zhangshuo-test** [alibaba/weex-ui#113]
preview中出现：
/* 13 */
/***/ (function(module, exports) {

	export { default } from './index.vue';

/***/ }),

**Comment by tw93** [comment]
https://github.com/alibaba/weex-ui/issues/14
https://alibaba.github.io/weex-ui/#/cn/with-weex-toolkit

Please find the issue and document first.
