### ISSUE TITLE
wxc-tab-page error in oppo

### ISSUE THREAD

**Issue by kangjunfeng** [alibaba/weex-ui#115]
environment（weex、weex-toolkit、system and more).    
 - weex version:V1.1.0-beta.7
 - phone:oppo
-  phone version:X909_11_141125
-  android version:4.2.2
-  system:ColorOS

Expected behavior and actual behavior.   
 - wxc-tab-page ，@wxcTabPageCurrentTabSelected
 - When I click on the navigation options, the list goes blank

**Comment by tw93** [comment]
Please use weex playground to scan the code to see if there is any problem.
![image](https://user-images.githubusercontent.com/8736212/34711964-297f16a6-f55c-11e7-91b9-14acf00bb008.png)

**Comment by kangjunfeng** [comment]
I've tried it. It's the same problem.

**Comment by tw93** [comment]
I can't repeat the problem here. I suspect the mobile phone system is too old.
What app do you use to scan the qrcode?
Please use taobao to scan the qrcode to see if there is any problem.

**Comment by tw93** [comment]
Unable to recover temporarily closed.
