### ISSUE TITLE
wxc-tab-bar 不能正确显示图标，及部分解决办法

### ISSUE THREAD

**Issue by DamingLake** [alibaba/weex-ui#118]
wxc-tab-bar 不能正确显示图标。
具体为：
1、`&#xe7a1; `这样的，后面三位里带字母的不能正常显示，会显示 为 e7a1这样，后面三位全为数字的正常。
2、web显示正常，Android app 显示为 X 
3、应用第一次启动，图标只显示一半，点击操作后显示正常。
经过分析，修改wxc-tab-bar 下的两处。
1、修改 wx-tab-bar  util.js 30 行 
decodeIconFont (text) {
    // 正则匹配 图标和文字混排 eg: 我去上学校&#xe600;,天天不&#xe600;迟到
    // const regExp = /&#x[a-z]\d{3,4};?/; 
    修改为
    const regExp = /&#x[a-z|0-9]{4,5};?/g;
2、修改 index.vue 182 行
if (titleType === 'iconFont' && tabStyles.iconFontUrl) {
        dom.addRule('fontFace', {
          'fontFamily': "wxcIconFont",
         //'src':\`url(${tabStyles.iconFontUrl})\`  
            修改为 
          'src': \`url('${tabStyles.iconFontUrl}')\` // 里面加上单引号
        });
      }
3、求助该如何处理。

##### 1.Your development environment（weex、weex-toolkit、system and more).    
 weex 0.16.0
weex-toolkit@1.1.0-beta.7
 windows 10 x64
手机是 华为荣耀6plus android 6.0

##### 2.Expected behavior and actual behavior.   
weex-ui wxc-tab-bar

##### 3.Steps to reproduce the problem.    
 全部按官方demo代理书写。 tab-bar 图标使用 iconFont方式。

**Comment by tw93** [comment]
Please update the weex-ui to the latest version.
I optimized the use of iconfont，You don't need to encode it.
Please modify `&#xe7a1;` to `/ue7a1`

> npm i weex-ui@latest -S

```
tabIconFontTitles: [
    {
      title: 'Home',
      codePoint: '\ue608'
    },
    {
      title: 'Message',
      codePoint: '\ue752',
      badge: 5
    },
    // ....
  ],
```
