### ISSUE TITLE
使用vue init创建工程按照weex-ui说明引用wxc-button chrome浏览器里面报错

### ISSUE THREAD

**Issue by alex1226** [alibaba/weex-ui#12]
Uncaught ReferenceError: weex is not defined
    at eval (index.vue?ab67:37)
    at Object.<anonymous> (app.js:1808)
    at __webpack_require__ (app.js:678)
    at fn (app.js:88)
    at eval (index.vue?c5c5:1)
    at Object.<anonymous> (app.js:1795)
    at __webpack_require__ (app.js:678)
    at fn (app.js:88)
    at eval (index.js?9340:1)
    at Object.<anonymous> (app.js:1788)

**Comment by tw93** [comment]
use the tool  https://github.com/weexteam/weex-toolkit

**Comment by alex1226** [comment]
D:\weex>weex init test
Invalid project name:
将weex-toolkit升级到最新版本后weex init命令好像不行了 如上提示。

**Comment by tw93** [comment]
@erha19

**Comment by alex1226** [comment]
刚才用weex create test创建了工程 仅仅添加引用语句：
<script> 
  import { WxcButton, WxcPopup } from 'weex-ui';

运行npm run build 还是报错：
    ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/weex-ui/pac
kages/wxc-rich-text/wxc-rich-text-text.vue
    Module build failed: SyntaxError: D:/weex/test/node_modules/weex-ui/packages/wxc-rich-text/wxc-r
ich-text-text.vue: Unexpected token (65:10)
      63 |       if (textStyle && textStyle.fontSize) {
      64 |         style = {
    > 65 |           ...style,
         |           ^
      66 |           fontSize: `${textStyle.fontSize}px`,
      67 |           height: `${textStyle.fontSize * 1.2}px`
      68 |         }

     @ ./~/weex-ui/packages/wxc-rich-text/wxc-rich-text-text.vue 7:2-105
     @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/weex-ui/packages/
wxc-rich-text/index.vue
     @ ./~/weex-ui/packages/wxc-rich-text/index.vue
     @ ./~/weex-ui/packages/wxc-rich-text/index.js
     @ ./~/weex-ui/index.js
     @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/index.vue
     @ ./src/index.vue
     @ ./temp?entry=true

**Comment by tw93** [comment]
this issue is like this  https://github.com/alibaba/weex-ui/issues/10
you can see it to get solutions
