### ISSUE TITLE
富文本组件的坑

### ISSUE THREAD

**Issue by tonyyls** [alibaba/weex-ui#121]
weex-ui中的wxc-rich-text组件，当文本内容过长时候会超出父亲容器，导致溢出。有啥版本可以解决？

**Comment by tw93** [comment]
Only one row `wxc-rich-text`  is supported.
You can use  `wxc-special-rich-text` for two lines

**Comment by vLCv** [comment]
Cannot support only text if you use wxc-special-rich-text in 2 lines. Show black space if you leave tag/icon part empty.

**Comment by vLCv** [comment]
<text :class="[ title ? 'black' : 'default-text' ]" v-if="isString">{{configList}}</text>customised the source code so that can achieve diff requirements

**Comment by vLCv** [comment]
`<text :class="[ title ? 'black' : 'default-text' ]" v-if="isString">{{configList}}</text>`
