### ISSUE TITLE
wxc-tab-bar can not show titles on ios 11.2 , but on ios 8.1 it shows right

### ISSUE THREAD

**Issue by lilin666** [alibaba/weex-ui#122]
##### 1.Your development environment（weex、weex-toolkit、system and more).    
 - weex  v1.1.0-beta.7
 - "weex-ui": "^0.3.11"
##### 2.Expected behavior and actual behavior.   
 -  ios 8.1 
![image](https://user-images.githubusercontent.com/3794956/34931812-7ce2ee4a-fa0b-11e7-9742-2807854d9b23.png)

 - ios 11.2 
![image](https://user-images.githubusercontent.com/3794956/34931749-3e4161a8-fa0b-11e7-822f-f71c481327aa.png)

##### 3.Steps to reproduce the problem.    
 -  Showing the same as ios 8.1

**Comment by tw93** [comment]
https://github.com/alibaba/weex-ui/blob/master/example/tab-bar/index.vue#L37
The tab bar height is error,you can change it

**Comment by FuckDoctors** [comment]
The same here, ios 10.3 = ios 8.1, ios 11 the same.
can you tell me how to fix it？ @tw93 @lilin666 
---------------------------
能给说一下把`const tabPageHeight = Utils.env.getPageHeight();`具体改成什么样吗?
作为一个不了解原生的非前端，使用weex好费劲啊。。。

**Comment by tw93** [comment]
You can calculate the height like this.
```
const { env } = weex.config;
const pageHeight=env.deviceHeight / env.deviceWidth * 750;
```

**Comment by FuckDoctors** [comment]
@tw93 I tried, but it doesn't work for me.
finally, i renamed index.vue to app.vue, and added a new index.vue,in this one, using navigator.push to goto the app.vue.
it worked for me.
sorry for my poor english， and 新年快乐～
