### ISSUE TITLE
use WxcGridSelect, When the quantity is too much, do not change line.

### ISSUE THREAD

**Issue by lczhai** [alibaba/weex-ui#123]
我在使用 ‘WxcGridSelect’ 的时候发现当item数量很多，一行显示不下的情况下，WxcGridSelect并不会自动换行，查看weex-ui的文档及demo也没有找到相关的css，请问是怎么回事？

**Comment by tw93** [comment]
It`s my bug about new weex version, I will fix it next version

**Comment by tw93** [comment]
> npm i weex-ui@latest -S

You need update weex-ui to `0.3.12-beta` , I have fixed it.

**Comment by lczhai** [comment]
ok 3q.
