### ISSUE TITLE
wxc-tab-bar和wxc-city一起使用时，出现遮挡

### ISSUE THREAD

**Issue by heiren0926** [alibaba/weex-ui#124]
由于都是在横向滚动切换，出现了遮挡

**Comment by tw93** [comment]
将wxc-city放到wxc-tab-bar的同级，应该可解决

**Comment by Pimpernell** [comment]
放到同层之后出现了一个bug,错误提示是这样的：“[Vue warn]: Unknown custom element: <wxc-city> - did you register the component correctly? For recursive components, make sure to provide the "name" option.”

求帮助！各位大神！

**Comment by tw93** [comment]
确定引入了吗？

**Comment by Pimpernell** [comment]
你好,谢谢回复。
确实引入了相关文件。
首次学习使用WEEX，我再找找原因。

**Comment by Pimpernell** [comment]
@tw93  把wxc-city引入到wex-tab-bar的同级，在当前页面上通过this.$refs找不到wxcCity这个组件，求问怎么跨文件找到这个组件
