### ISSUE TITLE
wxc-tab-bar

### ISSUE THREAD

**Issue by sumincy** [alibaba/weex-ui#125]
https://h5.m.taobao.com/trip/wx-detection-demo/tab-bar/index.html?_wx_tpl=https%3A%2F%2Fh5.m.taobao.com%2Ftrip%2Fwx-detection-demo%2Ftab-bar%2Findex.weex.js 

这个在线demo的tab可以在谷歌浏览器里点击，我拉下来的weex-ui   npm run server 跑起来的点击没用  
有哪些地方使用需要注意的吗

**Comment by Aibric** [comment]
我的也是，VUE版本降级到2.5.3也白搭

**Comment by tw93** [comment]
![image](https://user-images.githubusercontent.com/8736212/35021183-b63704aa-fb6a-11e7-9637-5c8a8530743a.png)
Switch to development mode.

**Comment by Aibric** [comment]
![image](https://user-images.githubusercontent.com/2859844/35023993-2d6401ba-fb78-11e7-9700-f847e1563e57.png) 非手机模式下不可用。

**Comment by tw93** [comment]
This is a normal effect, because `tap` has been used instead of `click` in the new version of weex-vue-render

**Comment by Aibric** [comment]
如果想WEB端也可能用的话，应该如何解决这个问题呢？
