### ISSUE TITLE
wxc-stepper的default-value需要支持动态修改

### ISSUE THREAD

**Issue by deepcoldy** [alibaba/weex-ui#126]
##### 1.Your development environment（weex、weex-toolkit、system and more).    
weex

##### 2.Expected behavior and actual behavior.   
wxc-stepper的default-value支持动态修改

##### 3.Steps to reproduce the problem.    
 不支持.sync

**Comment by tw93** [comment]
I'll add it in the latest version. Thank you for your feedback

**Comment by tw93** [comment]
> npm i weex-ui@latest -S

You need update weex-ui to `0.3.12-beta` , I have fixed it.
