### ISSUE TITLE
icon使用会报错，好像是...语法不识别

### ISSUE THREAD

**Issue by ZSH-HSZ** [alibaba/weex-ui#127]
Try to search for your [issue](https://github.com/alibaba/weex-ui/issues?utf8=%E2%9C%93&q=), it may have already been answered or even fixed in the development branch. 
 
 在开 issue 前，可以先搜索以下以往的旧 [issue](https://github.com/alibaba/weex-ui/issues?utf8=%E2%9C%93&q=)，你遇到的问题可能已经有人提了，也可能已经在最新版本中被修正。

开源项目的用户和维护者之间并不是甲方和乙方的关系，issue 也不是客服。
在开 issue 的时候，请抱着一种『一起合作来解决这个问题』的心态，同时请尽可能描述清楚，这样效率才会高。

Remember to delete the above statement before committing.
同时建议使用英语进行描述，这样国外的开发者也可以看懂，提交之前，记得将上述说明删除。

##### 1.Your development environment（weex、weex-toolkit、system and more).    
 - 
 - 

##### 2.Expected behavior and actual behavior.   
 - 
 - 

##### 3.Steps to reproduce the problem.    
 - 
 -

**Comment by tw93** [comment]
请详细描述，否则直接关闭issue

**Comment by ZSH-HSZ** [comment]
/~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/weex-ui/packages/wxc-button/index.vue
Module build failed: SyntaxError: Unexpected token (38:8)

  36 |       const { type, disabled, btnStyle } = this;
  37 |       const mrBtnStyle = {
> 38 |         ...STYLE_MAP[type],
     |         ^
  39 |         ...btnStyle
  40 |       };
  41 |       return disabled ? {

 @ ./~/weex-ui/packages/wxc-button/index.vue 8:2-92
 @ ./~/weex-ui/packages/wxc-button/index.js
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/mine/passwordSet.vue
 @ ./src/components/mine/passwordSet.vue
 @ ./src/router.js
 @ ./src/app.js
 @ multi (webpack)-dev-server/client?http://192.168.1.251:8081 ./src/app.js

**Comment by tw93** [comment]
重复问题
请参考这个解决
https://github.com/alibaba/weex-ui/blob/master/docs/with-weex-toolkit_cn.md#%E5%9C%A8%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8-weex-ui
