### ISSUE TITLE
wxc-cell组件@wxcCellClicked="wxcCellClicked"事件会在ios下报错，web和安卓都正常

### ISSUE THREAD

**Issue by janxy** [alibaba/weex-ui#128]
wxc-cell组件@wxcCellClicked="wxcCellClicked"事件会在ios下报错，web和安卓都正常

**Comment by tw93** [comment]
你是说点击cell demo 中的第二个，跳转时候到下一个页面变成空白了的这个问题吗？
应该是 weex playground ios上面navigation跳转的一个小bug，我这边更新下demo即可

**Comment by janxy** [comment]
不是的页面空白的，是我在wxc-cell点击后执行这个方法wxcCellClicked，，ios下就报错，，，wxcCellClicked方法里面是modal.toast弹出框。但是web和安卓都是正常运行的。就ios报错。

**Comment by tw93** [comment]
贴一下详细错误，包括如何使用的

**Comment by janxy** [comment]
<wxc-cell :title="value.RoomName"  :has-arrow="true" @wxcCellClicked="wxcCellClicked(key)" v-for="(value, key) in lists"></wxc-cell>

js/////////
methods: {
      wxcCellClicked (key) {
      	modal.toast({ message: '3333'})
      }
    }

**Comment by tw93** [comment]
`wxccellclicked`写错 ==
`wxcCellclicked`

**Comment by janxy** [comment]
<wxc-cell :title="value.RoomName"  :has-arrow="true" @wxcCellClicked="wxcCellClicked(key)" v-for="(value, key) in lists"></wxc-cell>

js/////////
methods: {
wxcCellClicked (key) {
modal.toast({ message: '3333'})
}
}

**Comment by janxy** [comment]
没有错，是他自己帮我转小写了

**Comment by janxy** [comment]
@wxcCellClicked="wxcCellClicked(key)"

**Comment by janxy** [comment]
![qq 20180118114952](https://user-images.githubusercontent.com/10809790/35079977-b7bf323a-fc45-11e7-8527-1d9b1316be8c.jpg)

**Comment by tw93** [comment]
详细错误是什么？

**Comment by janxy** [comment]
![qq 20180118114617](https://user-images.githubusercontent.com/10809790/35080000-cf54d0bc-fc45-11e7-92bd-e74ab86cab9d.jpg)

**Comment by janxy** [comment]
ios有点看不懂。。但是单击完他就那样了。不会像web和安卓那样弹出modal.toast({ message: '3333'})

**Comment by tw93** [comment]
看样子不是cell的问题， 使用了v-for的地方记得加上key，可以写一个简单的demo试试

```
<wxc-cell label="标题"
                  title="Weex Ui"
                  v-for="(value, index) in [1,2,3,4,5]"
                  key="index"
                  @wxcCellClicked="wxcCellClicked(key)"
                  :has-margin="false"></wxc-cell>
```
