### ISSUE TITLE
weex-rich-text Can't find variable: appendProtocol

### ISSUE THREAD

**Issue by xyzgit** [alibaba/weex-ui#13]
When the config type is 'link', click the text, an error occur:
`ReferenceError: Can't find variable: appendProtocol
goToH5Page
onLinkClick
fireEvent@native-bundle-main.js:8:9230
native-bundle-main.js:3:26676
forEach@[native code]
d@native-bundle-main.js:3:26575
native-bundle-main.js:8:16204 `

**Comment by tw93** [comment]
npm i weex-ui@0.1.2 -S , I have fixed it 
Thank you for your feedback.

**Comment by xyzgit** [comment]
Thank you first, but after I update to 0.1.2, once I click the link,  iOS App is crashed, here is the error info: 

> unrecognized selector sent to instance 0x1b17727a8
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFBoolean lowercaseString]: unrecognized selector sent to instance 0x1b17727a8'
*** First throw call stack:
(0x180da3d38 0x1802b8528 0x180db11f8 0x180da96e4 0x180c8f0dc 0x100982f14 0x100971f68 0x180dab6a0 0x180c8a820 0x10090f7f8 0x10090f8a8 0x10098997c 0x181793a50 0x180d4c358 0x180d4c2d8 0x180d4bb60 0x180d49738 0x180c6a2d8 0x182afbf84 0x18a217880 0x1005d7714 0x18078e56c)
libc++abi.dylib: terminating with uncaught exception of type NSException

my code: 
`<wxc-rich-text :config-list="configList" :has-text-margin="false" v-on:wxcRichTextLinkClick="wxcRichTextLinkClick"></wxc-rich-text>`

**Comment by tw93** [comment]
you can change the configList href to a js bundle url
I guess is the playground bug

**Comment by xyzgit** [comment]
```
import { WxcRichText } from 'weex-ui'
configList: [{
                type: 'text',
                value: 'hello world',
                theme: 'yellow'
            },{
                type: 'text',
                value: 'rich-text',
                theme: 'black'
            }, {
                type: 'link',
                value: '点击跳转',
                href: '//h5.m.taobao.com',
                style: {
                    color: '#546E7A'
                }
            }]
<wxc-rich-text :config-list="configList" @wxcRichTextLinkClick="wxcRichTextLinkClick"></wxc-rich-text>
```
click link text, then App crashed, maybe that's a sdk bug
