### ISSUE TITLE
WxcTabBar TabBar按住鼠标不动，可左右拖拽

### ISSUE THREAD

**Issue by Aibric** [alibaba/weex-ui#131]
WxcTabBar TabBar 按住鼠标可以拖拽，不应该拖拽。

![image](https://user-images.githubusercontent.com/2859844/35179067-855a1060-fdcd-11e7-84ed-2212572cd5df.png)

**Comment by tw93** [comment]
Because the middle text is too long，Not tab-bar

**Comment by Aibric** [comment]
根本就不是 TEXT 太长了，什么都不写一样可以拖拽。  @tw93 
![image](https://user-images.githubusercontent.com/2859844/35191540-9c714c8c-feb8-11e7-9d26-76191b47be23.png)

**Comment by tw93** [comment]
Try it this link  https://h5.m.taobao.com/trip/wx-detection-demo/tab-bar/index.html?_wx_tpl=https%3A%2F%2Fh5.m.taobao.com%2Ftrip%2Fwx-detection-demo%2Ftab-bar%2Findex.weex.js

**Comment by tw93** [comment]
应该是你这边环境中 weex-vue-render 的版本有问题，你可以参考下这个项目

https://github.com/tw93/weex-ui-demo
或者更新weex-toolkit 到最新 重新创建试试~
https://alibaba.github.io/weex-ui/#/cn/with-weex-toolkit

**Comment by tw93** [comment]
@邵新才  更新下weex-ui 组件里面加了一个overflow: hidden;  应该已经修复
npm i weex-ui@latest -S

**Comment by heiren0926** [comment]
我也遇到同样的问题了，更新了最新版的weex-ui也还是不行啊，升级了weex-vue-render到0.12.21，也不行

**Comment by oli365** [comment]
楼主解决了吗？ 这个问题为嘛关闭了？
