### ISSUE TITLE
紧急求助 wxc-indexlist 无法更改背景颜色

### ISSUE THREAD

**Issue by xiaozhuxiong121** [alibaba/weex-ui#132]
`wxc-indexlist` 无法更改背景颜色
例如下载这样的样式

![b7339925-c24d-4858-915b-e17799de88c3](https://user-images.githubusercontent.com/7292110/35204689-d212d664-ff6a-11e7-8dd2-2f93fb57416d.png)

**Comment by tw93** [comment]
谢谢反馈，我想想怎么加入进去

**Comment by tw93** [comment]
更新weex-ui到最新
> npm i weex-ui@latest -S

### 完全自定义样式
- 假如上述默认样式不符合要求，可以通过传入相对应的参数来覆盖原有的样式。
- 样式为 Object 类型，使用驼峰方式命名

<img src="https://img.alicdn.com/tfs/TB1ga6Sn6nD8KJjSspbXXbbEXXa-769-1374.jpg" width="300"/>

**Comment by xiaozhuxiong121** [comment]
A、B、C下面的背景颜色怎么变呢
![wechatimg57](https://user-images.githubusercontent.com/7292110/35220320-de79e24e-ffb0-11e7-98ac-d72e5ea87476.jpeg)

**Comment by tw93** [comment]
这里其实是一个text，通过headerStyle来覆盖
假如没有问题了，可以将这个issue关闭

**Comment by xiaozhuxiong121** [comment]
嗯，提两个建议
1、建议提供一个文档，好多属性都不知道，比如`headerStyle `，我都不知道有这个API，查官方文档也没有
<img width="850" alt="2018-01-22 8 53 40" src="https://user-images.githubusercontent.com/7292110/35221771-5c1fb188-ffb6-11e7-8ead-c73aa8be8803.png">

2、弄个版本更新记录，每个版本更新了啥也不知道

**Comment by xiaozhuxiong121** [comment]
大神，`popTextStyle `设置没有起作用，不知道是我代码有问题还是什么原因
有没有什么QQ或微信群，都没有找到

![29818f02-9373-4984-80e2-f3857b2ab717](https://user-images.githubusercontent.com/7292110/35223122-53fa47b6-ffbb-11e7-85e2-1f230b5868c3.png)

**Comment by HaoyCn** [comment]
感谢 @tw93 的及时响应，不过看到这个 Issue 我也有些想法希望借此探讨下。

这个 Issue 是样式定制需求的一个很好的代表，这类情况有可能普遍存在于各种组件之中。如果每次都是靠增加类似的样式 API，问题倒是解决了，但感觉存在两个问题：

1. 成本：需要不断地增加 API；维护组件的时候面对已经暴露出来的 API，再去改样式难免束手束脚

2. 渲染：不得不说 Weex 在样式切换上是存在一定问题的，如果是这种一成不变的样式还好，一旦涉及样式切换，可能就会有意想不到的问题出现，类似于闪烁、样式重置无效等（我在其他组件开发时遇到过这个问题）

不知道我这两个顾虑维护者们是怎么看的。同时 Weex 组件样式定制问题是否有进一步的改进空间呢？

**Comment by tw93** [comment]
抱歉 之前哪一张图片有误
使用这种来配置
关于你说的文档记录和changelog 其实都是有的，只是现在给你的版本还是beta版本，没有合并到master，需要等到正式发布时候(每周尽量一次，防止对使用者频繁更新)

关于成本：你说的这个自定义需求，我认为更多是需要从视觉规范上面来统一，而不是通过增加大量的参数，譬如你这种情况最多5%的人有使用到，但是反而会让95%的同学觉得这个组件太复杂
关于渲染：这里需要自己去优化，尽量不要频繁更新样式，同时做好层级优化，越简单越好

![](https://img.alicdn.com/tfs/TB13DEPn8TH8KJjy0FiXXcRsXXa-776-1370.jpg)
