### ISSUE TITLE
求助，weex-loading导致list重复加载mounted

### ISSUE THREAD

**Issue by ebolavirus** [alibaba/weex-ui#134]
主页：
`    <our-list  :key="new Date()+i" :conf="val" :fatherSize="viewSize"/>
    
    <wx-loading
      :show="showloading"/>
.....`
our-list是我们封装的list组件，内嵌联网获取数据的业务逻辑以及cell渲染逻辑。
业务逻辑基本是：
list在mounted方法中打开loading的bool变量开关，
list在mounted方法中开始联网获取业务数据，
list在解析完成回调中渲染cell数组并展示，关闭loading的bool开关，
结果每次关闭后，都重新触发了list的mounted方法，导致这个过程循环3次以上甚至无限循环……
求解决方案。
源代码日志：
Object {__ob__: Observer}
index.web.js:3 hide loading...
index.web.js:3 list mounted...
index.web.js:3 show loading...

**Comment by tw93** [comment]
mounted 按理应该只会触发一次，不建议这样弄，仔细检查下自己代码，应该哪儿逻辑不对

同时将请求数据抽离成一个方法，只去调用一次，而不是每次一触发就去请求，同时这里可以新加一个参数，假如已经请求过了，就不要再次去请求了
这种咨询类问题，可以在群里咨询大家
