### ISSUE TITLE
Cannot read property 'transition' of undefined

### ISSUE THREAD

**Issue by hongmaoxiao** [alibaba/weex-ui#135]
## environment
- weex-toolkit: v1.2.7
 - MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports)
 - chrome 63.0.3239.132 (64 bit）
 - weex-ui: 0.3.13-beta3
## actions
 - expected: success to switch tab
 - actual: Cannot read property 'transition' of undefined
<img width="1394" alt="2018-01-25 4 34 28" src="https://user-images.githubusercontent.com/3943494/35378423-b4daa06a-01ed-11e8-9520-d7e0eb3672c3.png">

**Comment by Anonlyy** [comment]
我也有这个问题,坐等更新

**Comment by Anonlyy** [comment]
通过测试知道
![image](https://user-images.githubusercontent.com/28748475/35379214-54a17fd6-01f0-11e8-9398-21a6d74da53f.png)

**Comment by erha19** [comment]
@hongmaoxiao @Anonlyy can you provide a simple test demo?

**Comment by hongmaoxiao** [comment]
@erha19 I use the demo from here [https://alibaba.github.io/weex-ui/#/cn/packages/wxc-tab-bar/?id=%e4%bd%bf%e7%94%a8%e6%96%b9%e6%b3%95](https://alibaba.github.io/weex-ui/#/cn/packages/wxc-tab-bar/?id=%e4%bd%bf%e7%94%a8%e6%96%b9%e6%b3%95)，I just modify some text.

**Comment by hongmaoxiao** [comment]
@erha19 It is a bug on web, not in andriod and ios。maybe it is not so important

**Comment by ISCLOUDX** [comment]
I need to use this to support the web page.

**Comment by wen911119** [comment]
试了一下，不只是animation模块，其它模块也是一样。应该是执行时序问题。
setTimeout(() => {
        const animation = weex.requireModule('animation');
        console.log(animation) // ok
    }, 0)
只有这样才可以

**Comment by tw93** [comment]
This is my environment:

```
   v1.2.7
 - weexpack : v1.0.8
 - weex-builder : v0.3.12
 - weex-previewer : v1.4.4
 - toolkit-repair : v0.0.5
```

And this is my package.json,Can you compare what's wrong?
```
...
"dependencies": {
        "fs-extra": "^4.0.1",
        "vue": "^2.4.3",
        "weex-html5": "^0.4.1",
        "weex-ui": "^0.3.13",
        "weex-vue-render": "^0.12.21"
    },
    "devDependencies": {
        "babel-core": "^6.21.0",
        "babel-loader": "^6.2.4",
        "babel-plugin-add-module-exports": "^0.2.1",
        "babel-plugin-component": "^1.1.0",
        "babel-plugin-transform-runtime": "^6.9.0",
        "babel-preset-es2015": "^6.9.0",
        "babel-preset-stage-0": "^6.24.1",
        "babel-runtime": "^6.9.2",
        "css-loader": "^0.26.1",
        "html-webpack-plugin": "^2.30.1",
        "ip": "^1.1.5",
        "raw-loader": "^0.5.1",
        "script-ext-html-webpack-plugin": "^1.8.5",
        "vue-loader": "^12.2.0",
        "vue-template-compiler": "^2.4.3",
        "webpack": "^2.2.1",
        "webpack-dev-server": "^2.4.2",
        "webpack-merge": "^4.1.0",
        "weex-loader": "^0.5.3"
    },
...
```

**Comment by javaKhan** [comment]
对web支持不完善

**Comment by hoatructhanhlam** [comment]
I also have same problem. it can't load weex module in components with weex-vue-render latest.

**Comment by tw93** [comment]
Because `weex-vue-render` 1.x version has changed a lot, But weex-toolkit has not yet been upgraded, So it is recommended to use version 0.12.21 first.
>npm i  weex-vue-render@0.12.21 -D

**Comment by wen911119** [comment]
@tw93  the issue still exists when change to 0.12.21 , demo is here [https://github.com/wen911119/weex-issue-demo](url)
1.git clone
2. npm install
3. npm start

**Comment by tw93** [comment]
Your project seems too old to be re-created.

```
   v1.2.7
 - weexpack : v1.0.8
 - weex-builder : v0.3.12
 - weex-previewer : v1.4.4
 - toolkit-repair : v0.0.5
```

You can uninstall weex-toolkit and reinstall it.Then try It with .
https://alibaba.github.io/weex-ui/#/cn/with-weex-toolkit
https://github.com/tw93/weex-ui-demo

**Comment by erha19** [comment]
@hongmaoxiao @wen911119 @javaKhan @ISCLOUDX  That's a very typical `Hosting` issue, you can see [Hosting MDN](https://developer.mozilla.org/en-US/docs/Glossary/Hoisting), try the flowing steps to fix it:
1. you want to fix an existing project:
searching `webpack.common.config.js` file on `configs` folder, and change `contents += `\nimport App from '${relativeVuePath}';\n`;` to `contents += `\nconst App = require('${relativeVuePath}');\n`;`.
2. If you just want to create a normal weex project
upgrade your `weexpack` to the latest version by `weex update weexpack@latest` command, then re-create again. the latest version should above `v1.0.12`.

**Comment by wen911119** [comment]
@erha19  it works ! thanks very much ！
