### ISSUE TITLE
 "weex-ui": "^0.3.13-beta2",wxc-cell包含input时，设置slot="value" 无法显示input控件

### ISSUE THREAD

**Issue by wyh497823256** [alibaba/weex-ui#136]
版本  :0.3.13-beta2
问题描述：wxc-cell包含input时，设置slot="value" 无法显示input控件，slot="title"可以显示
代码：
```
      <wxc-cell label="订单金额"
                      :has-arrow=true>

                <input slot="title" value="" type="number" placeholder="请输入优惠券面值"/>
            </wxc-cell>
            <wxc-cell label="发放总量">
                <input slot="value" value="" type="number" placeholder="请输入优惠券面值"/>
            </wxc-cell>
```
效果：
![image](https://user-images.githubusercontent.com/8830870/35380417-245565dc-01f4-11e8-9566-58a30661bec2.png)

**Comment by tw93** [comment]
在 input上面加入样式width、height、border-width 试试，怀疑是默认是白色的

**Comment by wyh497823256** [comment]
@tw93  你说的对，只要设置个width 值 就可以。input 为什么没有光标

**Comment by tw93** [comment]
有的， 你需要在真实环境中看

**Comment by wyh497823256** [comment]
@tw93 原来要设置 height 才能显示 光标

**Comment by tw93** [comment]
对 在weex里面 尽量让component知道自己的大小~

**Comment by wyh497823256** [comment]
@tw93  非常感谢的你的回答，谢谢
