### ISSUE TITLE
when use command weex compile case error /node_modules/weex-ui/index.js Module build failed: Error: Cannot find module 'babel-core'

### ISSUE THREAD

**Issue by songxing10000** [alibaba/weex-ui#137]
根据官方命令安装环境
```js
brew install node
npm install -g cnpm --registry=https://registry.npm.taobao.org
cnpm install -g weex-toolkit@latest
```
然后环境为
![image](https://user-images.githubusercontent.com/10040131/35438592-1878eeee-02d2-11e8-8956-a4eb8d4975e2.png)
然后`weex create UUU`
然后进入项目
`npm i weex-ui@latest -S`
`npm i babel-plugin-component babel-preset-stage-0 -D`
修改文件`.babelrc`
```js
{
  "presets": ["es2015", "stage-0"],
  "plugins": [
    [
      "component",
      {
        "libraryName": "weex-ui",
        "libDir": "packages",
        "style": false
      }
    ]
  ]
}

```
导入组件
```js
<script>
  import { WxcLightbox } from 'weex-ui';
  export default {
    components: {
      WxcLightbox
    },
    ....
```
使用组件
```js
<template>
  <div class="container">
    <wxc-lightbox
      height="100"
      :show="show"
      :image-list="imageList"
      @wxcLightboxOverlayClicked="wxcLightboxOverlayClicked">
    </wxc-lightbox>
    ...
```
然后执行命令`weex compile src /usr/local/var/www`用来把js文件放到nginx上，结果报错

![image](https://user-images.githubusercontent.com/10040131/35438562-f410fb78-02d1-11e8-9fb2-c845a23e9c62.png)
试了npm装，cnpm装，都报错
`/node_modules/weex-ui/index.js
Module build failed: Error: Cannot find module 'babel-core'`

**Comment by tw93** [comment]
Try it  https://alibaba.github.io/weex-ui/#/cn/with-weex-toolkit

**Comment by songxing10000** [comment]
@tw93 所有操作都是按那个文档来的，`npm run serve`能界面正常，为啥执行命令weex compile src /usr/local/var/www用来把js文件放到nginx上，就会提示
/node_modules/weex-ui/index.js Module build failed: Error: Cannot find module 'babel-core'
呢

**Comment by tw93** [comment]
Try 
```
npm install babel-core babel-loader -D
```

**Comment by songxing10000** [comment]
已解决，将文件`/usr/local/lib/node_modules`下的`weex-toolkit`反复删除，反复执行`npm install -g weex-toolkit@latest`就正常了，因为之前已经在项目里执行过了命令`npm i`  `npm i weex-ui@latest -S`  `npm i babel-plugin-component babel-preset-stage-0 -D` 同时修改.babelrc，所以命令`npm install -g weex-toolkit@latest`是关键
![image](https://user-images.githubusercontent.com/10040131/35606896-7ab2874c-068c-11e8-8f26-963b2180fe01.png)

**Comment by liangklfangl** [comment]
这个反复两个字用的好，到底是多少次算反复？

**Comment by liangklfangl** [comment]
其实解决方案在[这里](https://github.com/liangklfangl/react-article-bucket/blob/master/weex/error.md#2%E8%BF%90%E8%A1%8Cweex-compile%E7%9A%84%E6%97%B6%E5%80%99babel-core%E4%B8%8D%E5%AD%98%E5%9C%A8)。因为weex-toolkit全局安装的时候将babel-core设置了devDependencies，所以导致全局安装的时候并不会主动安装它，所以找不到这个模块，你可以看看[weex-toolkit的package.json](https://github.com/weexteam/weex-toolkit/blob/master/package.json#L28)。

**Comment by songxing10000** [comment]
又报这个错了`weex build failed: Error: Cannot find module \'babel-core\'\n at`，
解决方案还是
将文件`/usr/local/lib/node_modules`下的`weex-toolkit`删除，
执行`npm install -g weex-toolkit@latest`就正常了，
然后 删除项目里的`node_modules`，
然后执行`cnpm install `,并没有执行
`npm i npm i weex-ui@latest -S`和` npm i babel-plugin-component babel-preset-stage-0 -D`也是编译成功的
