### ISSUE TITLE
引用weex-ui组件android界面显示空白，除了example例子还没成功运行过

### ISSUE THREAD

**Issue by alex1226** [alibaba/weex-ui#14]
1.用weex create test创建weex项目
2.后续按照weex-ui提示做：
npm i weex-ui -S
import { WxcButton, WxcPopup } from 'weex-ui';
添加到index.vue里面
3.运行看效果 weexpack run android 不能显示出来
界面提示 ： render error：-2013
log提示:10-12 10:47:11.022 19480-20668/com.alibaba.weex E/jsengine:  ReportException :undefined:630: SyntaxError: Unexpected token (
10-12 10:47:11.025 19480-20668/com.alibaba.weex E/jsengine:  ReportException : SyntaxError: Unexpected token (
                                                                at Jt ((weex):4:2004)
                                                                at Object.Dt [as createInstance] ((weex):3:31729)
                                                                at Object.R [as createInstance] ((weex):1:7385)
                                                                at global.(anonymous function) ((weex):7:1148)
10-12 10:47:11.026 19480-20668/com.alibaba.weex E/weex: reportJSException >>>> instanceId:1, exception function:createInstance, exception:SyntaxError: Unexpected token (

**Comment by tw93** [comment]
@erha19 Have a hard look

**Comment by alex1226** [comment]
能给个组简单的weex-ui组件应用例子吗，除了example那个上下文的. 
look what?

**Comment by thecorsair** [comment]
同样的问题

**Comment by erha19** [comment]
OK, I will follow up on this question.

**Comment by erha19** [comment]
Edit `platform/android/app/build.gradle` 
```
- compile 'com.taobao.android:weex_sdk:0.10.0'
+ compile 'com.taobao.android:weex_sdk:0.16.0'
```
Then run `weex run android` again.

**Comment by alex1226** [comment]
按照上面修改build.gradle也没用，看了下应该是添加引用wxc-button后编译vue时候出现问题。
在工程目录下执行npm run build 会提示：
    ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/weex-ui/pac
kages/wxc-rich-text/wxc-rich-text-text.vue
    Module build failed: SyntaxError: D:/weex/test/node_modules/weex-ui/packages/wxc-rich-text/wxc-r
ich-text-text.vue: Unexpected token (65:10)

      63 |       if (textStyle && textStyle.fontSize) {
      64 |         style = {
    > 65 |           ...style,
         |           ^
      66 |           fontSize: `${textStyle.fontSize}px`,
      67 |           height: `${textStyle.fontSize * 1.2}px`
      68 |         }

     @ ./~/weex-ui/packages/wxc-rich-text/wxc-rich-text-text.vue 7:2-105
     @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/weex-ui/packages/
wxc-rich-text/index.vue
     @ ./~/weex-ui/packages/wxc-rich-text/index.vue
     @ ./~/weex-ui/packages/wxc-rich-text/index.js
     @ ./~/weex-ui/index.js
     @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/index.vue
     @ ./src/index.vue
     @ ./temp?entry=true

**Comment by tw93** [comment]
@alex1226  https://github.com/alibaba/weex-ui#weex-toolkit

**Comment by alex1226** [comment]
D:\weex\test>weex -v
   v1.1.0-beta.1
 - weexpack : v0.4.7-beta2
 - weex-builder : v0.2.13-beta.1
 - weex-devtool : v0.2.83
 - weex-previewer : v1.3.13-beta.2
 - toolkit-repair : v0.0.5

已经是最新了吧

**Comment by tw93** [comment]
### Weex-toolkit

If you use [weex-toolkit](https://github.com/weexteam/weex-toolkit) to develop a Weex project, Please add 'state-0' and 'babel-plugin-component' to .babelrc.

```shell
npm i babel-preset-stage-0 babel-plugin-component  -D
```

```json
{
  "presets": ["es2015", "stage-0"],
  "plugins": [
    [
      "component",
      {
        "libraryName": "weex-ui",
        "libDir": "packages"
      }
    ]
  ]
}
```

**Comment by erha19** [comment]
I suggest you upgrade `weexpack` of weex-toolkit by `weex update weexpack`.
Re-create your project.
Edit your index.vue, `npm install`, `npm install install babel-preset-stage-0 babel-plugin-component weex-ui -D`...
Remember to modify your `.babelrc` according to @tw93 's latest comment.
Finally, you can run `weex run android` to start your app (If you do install the android environment correctly).

**Comment by alex1226** [comment]
ok
