### ISSUE TITLE
weex-tab-bar  如何配合vue router 使用

### ISSUE THREAD

**Issue by sumincy** [alibaba/weex-ui#149]
比方点击底下tab的时候 回调方法里  使用router.push 去切换其内容界面。
现在看到的demo 里  内容全在  weex-tab-bar里的几个<div>中 点击切换的是这几个div 
生产开发中 ,应该不会有把内容全放到这一个vue中的吧

**Comment by tw93** [comment]
实际生产过程中，建议直接使用原生的tabbar抽成weex component，这样体验更好
但是假如不是很好弄，才用这个组件的

> 生产开发中 ,应该不会有把内容全放到这一个vue中的吧
是的，复杂页面不建议这样，反而增大复杂性和性能体验

同时也不建议weex 使用vue-router去弄，采用多页方式体验会比较好

**Comment by xujiale** [comment]
@tw93 weex没有原生的tab bar吧

**Comment by tw93** [comment]
没有的，需要客户端实现
