### ISSUE TITLE
Cannot read property 'transition' of undefined 

### ISSUE THREAD

**Issue by zqqq** [alibaba/weex-ui#151]
与 #135  一样的问题
复制这个组件示例代码，在chrome web中运行出错
https://alibaba.github.io/weex-ui/#/cn/packages/wxc-tab-bar/

```javascript
Uncaught TypeError: Cannot read property 'transition' of undefined
    at VueComponent._animateTransformX (webpack-internal:///147:267)
    at VueComponent.boundFn [as _animateTransformX] (webpack-internal:///100:190)
    at VueComponent.setPage (webpack-internal:///147:254)
    at Proxy.boundFn (webpack-internal:///100:190)
    at click (webpack-internal:///148:44)
    at applyFns (webpack-internal:///132:5488)
    at HTMLDocument.eval (webpack-internal:///132:6180)
    at fireEvent (webpack-internal:///132:114)
    at HTMLHtmlElement.touchendHandler (webpack-internal:///132:387)
    at eval (webpack-internal:///235:182)
````

使用 https://github.com/wen911119/weex-issue-demo 这个demo运行正常，但是新的weex-toolkit创建的项目结构已经不一样了不知道如何修改。

##### 1.Your development environment（weex、weex-toolkit、system and more).    
 weex-toolkit  v1.2.9
 - weexpack : v1.1.4
 - weex-builder : v0.3.16
 - weex-previewer : v1.4.6

**Comment by tw93** [comment]
https://github.com/alibaba/weex-ui/issues/135#issuecomment-361491752

**Comment by zqqq** [comment]
If you want to fix an existing project:
searching webpack.common.config.js file on configs folder, and change
contents += `\nimport App from '${relativeVuePath}';\n`;
to

contents += `\nconst App = require('${relativeVuePath}');\n`;
If you just want to create a normal weex project
upgrade your weexpack to the latest version by weex update weexpack@latest command, then re-create again. the latest version should above v1.0.13.

发之前已经看过这个，
方法1提到的， 最新的 weex-toolkit 生成的 webpack.common.config.js  中已经没有相关的代码了
广告2提到的 ，weexpack已经是最新版

能否实际测试下？

**Comment by zqqq** [comment]
我的项目使用子 vue-router ，不知道是不是因为这个的原因？
我刚测试生成一个不带 vue-router的项目。貌似配置文件和 [#135 (comment)](url=https://github.com/alibaba/weex-ui/issues/135#issuecomment-361491752)
一致了。

**Comment by erha19** [comment]
@zqqq try to re-create your project, it has been fixed on the latest version of weex-template.

**Comment by zqqq** [comment]
好的，感谢。经测试正常了。

**Comment by wengpengfeijava** [comment]
你们解决了吗？怎么解决的？是什么问题引起的呢 ？

**Comment by EddieZhao** [comment]
@zqqq 请问你这个问题最后，怎么解决的
