### ISSUE TITLE
wxc-loading should have mask

### ISSUE THREAD

**Issue by danjiang** [alibaba/weex-ui#152]
wxc-loading should have mask

**Comment by tw93** [comment]
It is not recommended to add a mask to the loading according to the design interaction specification.

**Comment by danjiang** [comment]
Where is design interaction specification? Please let us know.

**Comment by tw93** [comment]
Do you mean that mask is covered by loading without user operation?
The main thing I understand loading is to tell the user that the page is loading but should not interfere with the user's not letting him click, for example, loading more.
Maybe I was wrong. Tell me what you think.

**Comment by danjiang** [comment]
When I submit my form. I use loading with mask to prevent user resubmit or go other interface. I think it is pretty common use case. Check out this iOS native HUD view https://github.com/SVProgressHUD/SVProgressHUD.

**Comment by tw93** [comment]
Thank you very much for your feedback.
I think can add a param to control whether you need a mask.
I'm going to add it to today's release.

**Comment by tw93** [comment]
> npm i weex-ui@latest -S

More  you can see here <https://github.com/alibaba/weex-ui/blob/master/packages/wxc-loading/README_cn.md#%E9%A1%B5%E9%9D%A2loading>
