### ISSUE TITLE
wxc-tab-bar iconFont 样式 margin-bottom 固定写死成8px，字体调小之后，感觉上下间隙有点大，建议加入配置项！

### ISSUE THREAD

**Issue by zqqq** [alibaba/weex-ui#156]
wxc-tab-bar iconFont 样式 margin-bottom 固定写死成8px，字体调小之后，感觉上下间隙有点大，建议加入配置项！

**Comment by zqqq** [comment]
wxc-tab-page 也有同样的问题。既然允许调整字体大小了，icon 的 margin-bottom 也应该允许调整才比较协调。

**Comment by zqqq** [comment]
![001](https://user-images.githubusercontent.com/10234272/36893761-36725f1a-1e44-11e8-9d33-20ba6fc54775.png)

**Comment by tw93** [comment]
> npm i weex-ui@latest -S

https://github.com/alibaba/weex-ui/blob/master/example/tab-bar/config.js#L80

**Comment by xujiale** [comment]
@tw93 请问使用:tab-titles是不是不能设置间隙？我看demo好像没有这样的配置

**Comment by tw93** [comment]
@xujiale  不可以的 直接使用 tabIconFontStyles
```
tabIconFontStyles: {
    bgColor: '#FFFFFF',
    titleColor: '#666666',
    activeTitleColor: '#3D3D3D',
    activeBgColor: '#FFFFFF',
    isActiveTitleBold: true,
    width: 160,
    height: 120,
    fontSize: 24,
    textPaddingLeft: 10,
    textPaddingRight: 10,
    iconFontSize: 50,
    iconFontMarginBottom: 8,
    iconFontColor: '#333333',
    activeIconFontColor: 'red',
    iconFontUrl: '//at.alicdn.com/t/font_501019_mauqv15evc1pp66r.ttf'
  }
```

**Comment by xujiale** [comment]
@tw93 谢谢大佬，我看源码的时候发现没有这个配置项，准备把图片改成iconfont了。
另外，假如我对某些组件(不限于tab bar)加了可以配置可以提PR吗

**Comment by tw93** [comment]
可以的 很欢迎
