### ISSUE TITLE
wxc-popup bug chrome web

### ISSUE THREAD

**Issue by zqqq** [alibaba/weex-ui#158]
当使用 weex 的 list组件 下的子组件 header时  在web环境下 header层会有一个z-index:9999的样式。导致无法遮罩。如果下图

When using the sub-component header under weex's list component, the header layer has a z-index: 9999 style in the web environment. Can not be masked. If the following figure

![002](https://user-images.githubusercontent.com/10234272/36932211-03fa6cae-1f01-11e8-8649-de0c0ec004ac.png)

**Comment by zqqq** [comment]
ios ,android 下正常。

**Comment by tw93** [comment]
在html文件中 写一个样式 .weex-ios-sticky 样式进行覆盖即可，无需组件升级

**Comment by zqqq** [comment]
但是那个header的z-index是需要的，否则在web下，会有问题。修改的办法就是，给wxc-overlay及wxc-popup 添加更高的z-index ，可以解决，但是感觉这样不是很好，你们看吧。没有必要升级也行。
