### ISSUE TITLE
安卓手机，选择城市组件，快速点击侧栏字母，会出现灰色遮罩

### ISSUE THREAD

**Issue by Sunrise1970** [alibaba/weex-ui#16]
设备为红米note 4x，Android6.0.1

快速点击字母会出现大灰色遮罩层

期待：
     不要出现超大遮罩层
     手指向下滑动字母排序时，能选择对应城市

**Comment by tw93** [comment]
This is just a demo, you can combine wxc-popup to do it , see the City Demo in the complex demo.
https://h5.m.taobao.com/trip/wxc-city/index.html?_wx_tpl=https%3A%2F%2Fh5.m.taobao.com%2Ftrip%2Fwxc-city%2Fdemo%2Findex.native-min.js&ttid=2017%40weex_h5_0.11.17

**Comment by tw93** [comment]
Have fixed in v0.1.3 branch, you can update it 
Thanks for your feedback

**Comment by Sunrise1970** [comment]
Ok, give you 666.
Expect more useful components, and hope weex will be more powerful.
