### ISSUE TITLE
wxc-ep-slider 与 开源版bindingx 并不兼容

### ISSUE THREAD

**Issue by hetian9288** [alibaba/weex-ui#160]
wxc-ep-slider 与 开源版bindingx 并不兼容

wxc-ep-slider 依赖模块还未更新：`requireModule('expressionBinding'); `

**Comment by tw93** [comment]
本周在进行兼容，预计这两天会发布一个beta版本

**Comment by tw93** [comment]
> npm i weex@0.5.0beta -S
目前已经对wxc-ep-slider 、 wxc-tab-page 进行bindingx 改造，可以去dev分支查看代码。
预计周末发布

**Comment by hetian9288** [comment]
wxc-tab-page 左右滑动滑动时最好能够屏蔽子列表的上下滑动
wxc-ep-slider 第一次滑动没问题但是第二次闪退

**Comment by tw93** [comment]
问题已经修复 请升级到weex-ui@0.5.0-beta1  使用

**Comment by hetian9288** [comment]
wxc-tab-page  wxc-ep-slider 第一次滑动没问题但是第二次闪退
xcode log 报错
`unrecognized selector sent to instance 0x12fd1d180'`

**Comment by tw93** [comment]
用手淘帮我测试下 是否也有这个问题哦

**Comment by hetian9288** [comment]
手淘 没问题 正常

**Comment by hetian9288** [comment]
手淘应该有`expressionBinding` 模块吧
 `weex-bindingx` 里有些 `expressionBinding`的兼容

**Comment by tw93** [comment]
![image](https://user-images.githubusercontent.com/8736212/37135623-10c3e254-22d9-11e8-9ddf-4068d2b3aba0.png)
用这个官方的demo 市场试试呢，我这边没有复现，会不会是你们android引入有点点问题呢

**Comment by hetian9288** [comment]
我这边测试的是IOS的

**Comment by hetian9288** [comment]
我这测试 weex-bindingx/demo 内的演示都是没问题的；

**Comment by hetian9288** [comment]
使用的 [eros-template](https://github.com/bmfe/eros-template) 生成项目；
IOS pod 安装 的 bindingx  `pod 'BindingX', '~> 1.0.0'`
`npm install weex-bindingx --save`
运行 `weex-bindingx/demo`演示没有问题；

你可尝试以下应该能够复现问题 在IOS 真机 与模拟器上都有这个问题

**Comment by tw93** [comment]
升级BindingX 到最新，中午发布了一个，是已知的一个bug。

**Comment by hetian9288** [comment]
👌没问题了
