### ISSUE TITLE
Weex 搜索栏组件，wxc-searchbar出现bug及建议

### ISSUE THREAD

**Issue by beijinaqie** [alibaba/weex-ui#166]
Weex 搜索栏组件，wxc-searchbar，输入框输入内容后，系统键盘删除文字，input内容全部清楚，但是绑定的值却保留了第一个字节，另外建议在@wxcSearchbarCloseClicked事件中，能把input框内的内容清除掉

**Comment by tw93** [comment]
第一个问题应该是 weex input 组件在android上面的一个bug，可以用这个官方demo测试下：
<http://dotwe.org/vue/8442cc83a7da3ce8856ba74405f567c8>
第二个问题也是类似情况 没有清除，ios 和 H5 是好的，我找 input 同学看看@misakuo

**Comment by tw93** [comment]
@beijinaqie weex 官方这边将此bug已经修复，合并master中，预计0.19版本解决~
