### ISSUE TITLE
weex-popover无法使用！

### ISSUE THREAD

**Issue by AugTang** [alibaba/weex-ui#172]
最新环境，运行报错。

**Comment by tw93** [comment]
贴一下详细错误

**Comment by AugTang** [comment]
![image](https://user-images.githubusercontent.com/31499235/37186314-ccfe562e-237f-11e8-8261-611772f675b2.png)
@tw93

**Comment by tw93** [comment]
看起来不像 weex-ui 的问题，你这边试试其他代码能不能跑~

**Comment by AugTang** [comment]
我试了幻灯片，那个没问题。
@tw93

**Comment by tw93** [comment]
这样文件引了吗？  https://github.com/alibaba/weex-ui/blob/master/example/popover/type.js
