### ISSUE TITLE
what is swipeback?

### ISSUE THREAD

**Issue by Alexis374** [alibaba/weex-ui#174]
In `wxc-tab-page`，I see `weex.requireModule('swipeBack')`,so `swipeBack` is another native module?    
after my test, `weexplayground` doesn't have, while `bindingxplayground` has `swipeBack`

**Comment by tw93** [comment]
This is a unique API used in taobao to prevent slippage back in ios.

**Comment by tonyyls** [comment]
where  can i  get swipeback  module? thanks

**Comment by fishyumiao** [comment]
I got this too.  where can i get swipeback module? thanks
