### ISSUE TITLE
使用vue-router跳转后宽度没有自动适应屏幕宽度

### ISSUE THREAD

**Issue by iori0758** [alibaba/weex-ui#176]
各位大神，我的 版本信息如下  
  "vue": "^2.5.11",
    "vue-router": "^3.0.1",
    "weex-ui": "^0.5.0-beta1",
    "weex-vue-render": "^0.12.26"
    "vue-loader": "^12.2.0",
    "vue-style-loader": "^3.0.3",
    "vue-template-compiler": "^2.5.11",
    "webpack": "^3.10.0",
    "webpack-dev-server": "^2.9.7",
    "webpack-merge": "^4.1.0",
    "webpack-uglify-parallel": "^0.1.4",
    "weex-loader": "^0.6.7"

就是在主页面A使用router跳转到B页面，B页面宽度显示正常，返回A页面，然后跳转到C页面，C页面就
是按照设定的750px来显示。
反过来在主页面A使用router跳转到C页面，C页面宽度显示正常，返回A页面，然后跳转到B页面，B页面就是按照设定的750px来显示。

A页面
![image](https://user-images.githubusercontent.com/3361962/37337091-4352f2a0-26ee-11e8-8230-cfe99a8d0518.png)

B页面

![image](https://user-images.githubusercontent.com/3361962/37337131-5862f816-26ee-11e8-99d8-16a62e6bfc1c.png)

C页面
![image](https://user-images.githubusercontent.com/3361962/37337154-66132be8-26ee-11e8-90aa-6984b1a5567e.png)

**Comment by tw93** [comment]
不建议在issue中咨询weex业务问题，直接钉钉群中问即可
