### ISSUE TITLE
WxcRadio 和 WxcCity  组件建议

### ISSUE THREAD

**Issue by zqqq** [alibaba/weex-ui#177]
WxcRadio  的 title  应该允许自定义 solt 比如用在用户地址选择时，要展示多行内容时，有需求。
WxcCity  应该允许不显示 定位，即继承  WxcIndexlist  的【 only-show-list | Boolean | N | false |】 是否只显示列表 属性，WxcCity 这个组件，即可以用来选择城市也可以用来选择区县，在选择区县时，就不需要定位这个了功能了。但是搜索这个功能又要，所以如果用  WxcIndexlist   就要自己处理搜索了。

**Comment by tw93** [comment]
关于WxcRadio 允许多行地址选择，这里建议用户通过wxc-cell这个组件自行扩展，因为WxcRadio是一个列表，涉及内部循环，不适合使用slot方式处理
关于WxcCity 不显示定位逻辑，已经更新，请更新weex-ui到最新版本 `weex-ui@0.5.3-beta` 即可
直接传入 currentLocation 为空即可
