### ISSUE TITLE
由于 Weex 在我们这边和 H5 一样，都是当做页面来发布、而不是一个 View 里面写很多子View来组织，同时也很不建议大家使用vue-router来管理，更多的使用多页面来跳转体验会更好。

### ISSUE THREAD

**Issue by shizhiang** [alibaba/weex-ui#178]
请问文档里面的这句话怎么理解呢？意思是不要使用weex的跳转，要跳转的还是用原生的跳转，然后原生的一个页面里面加载一个weex的页面？

**Comment by tw93** [comment]
此类问题不建议通过issue的方式来咨询，直接钉钉群里问~
因为你多view会导致bundle体积过来 同时不好管理 性能过低
