### ISSUE TITLE
官网文档中示例代码的一处错误

### ISSUE THREAD

**Issue by zqqq** [alibaba/weex-ui#180]
https://alibaba.github.io/weex-ui/#/cn/packages/wxc-stepper/
`<wxc-stepper default-value="4"
                   step="2"
                   max="10"
                   min="2"
                   @stepperValueChange="stepperValueChange"></wxc-stepper>`

其中 @stepperValueChange 应为 @wxcStepperValueChanged

**Comment by tw93** [comment]
Thanks for feedback,I have fixed it
