### ISSUE TITLE
直接按文档使用wxc-tab-bar 有问题 

### ISSUE THREAD

**Issue by zb1006801184** [alibaba/weex-ui#188]
https://alibaba.github.io/weex-ui/#/cn/packages/wxc-tab-bar/    我是完全按照文档上来编写的  不知道是文档没有更新还是我哪里写的有问题，写出来是这样
![221ca774-a218-4e18-a33e-76cd374604ff](https://user-images.githubusercontent.com/22284069/37693944-eec2c344-2cfd-11e8-8801-4b0968c619d7.png)

**Comment by tw93** [comment]
Your screenshot has some problems, please upload it again.

**Comment by linda8167** [comment]
我的也是，不过以APP的方式打包到Android手机上，看到的样子是，底部的tab和上面得页面之间有一个很大的空白间隙。不知道什么原因
