### ISSUE TITLE
Error when using weex-builder  complier .vue

### ISSUE THREAD

**Issue by zsmjhtn** [alibaba/weex-ui#190]
##### 1.Your development environment（weex、weex-toolkit、system and more).    
 - weex-builder@0.2.12 
├── babel-plugin-component@1.1.0
├── babel-preset-es2015@6.24.1
├── babel-preset-stage-0@6.24.1
├── url-parse@1.2.0
├── weex-bindingx@0.0.14
└── weex-components@0.2.1
 - 

##### 2.Expected behavior and actual behavior.   
 - I am developing project in WEEX.So I compiler project through  weex-builder .Recently, I want to combine weex-ui with my project.When i compiler demo.vue(which copied from button.vue in your weex-ui ),error happened as:

Build Failed!
[webpack errors]
demo.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [/Users/huangtianning/~/weex-bindingx/lib/index.js:783,0]
demo.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [/Users/huangtianning/~/weex-bindingx/lib/index.js:783,0]
 - 
What should i do when trying combine weex-ui with my project?

**Comment by tw93** [comment]
Try it
https://alibaba.github.io/weex-ui/#/cn/with-weex-toolkit

**Comment by tw93** [comment]
Try it
https://alibaba.github.io/weex-ui/#/cn/with-weex-toolkit
