### ISSUE TITLE
[optimize] JS bundle so big when add bindingx .

### ISSUE THREAD

**Issue by PerseveranceZ** [alibaba/weex-ui#191]
##### 1.Your development environment（weex、weex-toolkit、system and more).    
 - webpack 3.2.0
- .babelrc
```js
//   babelrc
{
  "presets": [
      ["env", {
          "targets": {
              "modules": false,
              "loose": true,
              "browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
          }
      }],
      "stage-0"
  ],
  "plugins": [
    ["component",{
        "libraryName": "weex-ui",
        "libDir": "packages",
        "style": false
    }],
    ["transform-runtime", {
      "polyfill": false,
      "helpers": false
    }]
  ],
  "env": {
      "test": {
          "presets": ["env", "stage-0"],
          "plugins": ["istanbul"]
      }
  }
}

``` 

##### 2.Expected behavior and actual behavior.   
I want to know why my js bundles so big and how to optimize. Thanks.

##### 3.Steps to reproduce the problem.    
 when i use `weex-ui` without `bindingx` , compiled js bundle info:
![image](https://user-images.githubusercontent.com/13193407/37722780-cc5a23f0-2d67-11e8-80bb-831fa665723a.png)

when i use `weex-ui@0.5.4beta` with `weex-bindingx` , compiled js bundle info:
![image](https://user-images.githubusercontent.com/13193407/37722871-fd89a73e-2d67-11e8-9333-00e5c158dff5.png)

[docs](https://alibaba.github.io/weex-ui/#/cn/?id=%E4%BD%BF%E7%94%A8%E5%89%8D) it work in `weex-ui` without `weex-bindingx`.

**Comment by PerseveranceZ** [comment]
oh,  many component import util.js and util import `weex-bindingx`.

**Comment by tw93** [comment]
Thank you for your feedback. We have optimized today.
Please upgrade weex-ui to `0.5.4beta-1` version, At the same time determine whether to open [this ](https://github.com/tw93/weex-ui-demo/blob/master/webpack.config.js#L110)  `exclude: /node_modules(?!(\/|\\).*(weex).*)/` 
Please try again. I'll think about the package optimization.

**Comment by tw93** [comment]
> oh, many component import util.js and util import weex-bindingx.
oh,My carelessness

**Comment by PerseveranceZ** [comment]
@tw93 Thank you very much,  It's a lot smaller.
![image](https://user-images.githubusercontent.com/13193407/37758716-22a6f236-2dec-11e8-9976-560ea6087420.png)
I have another question, you can see `js/pages/demo/other/weexui.js`, this js bundle is be compiled by [code](https://github.com/alibaba/weex-ui/tree/master/example/tab-page), I think it's a lot bigger, do you think? 

I think that rather than dealing with one file's compatible logic, it's better to divide the three files to process their respective logic separately and to quote individually, which will reduce the size of some components.

Sometimes, I really just need `binding-parser` and some simple `compatible code` like this in weex pure native project.

```js
import { parse } from 'bindingx-parser'
import _cloneDeep from 'lodash/cloneDeep'

const WeexBinding = weex.requireModule('bindingx')
const BindingxFunction = WeexBinding.bind

let _WeexBinding = _cloneDeep(WeexBinding)

// 重写 bind 方法
_WeexBinding.bind = (options, callback) => {
    if (!options) {
        throw new Error('should pass options for binding')
    }

    options.exitExpression = formatExpression(options.exitExpression)

    if (options.props) {
        options.props.forEach((prop) => {
            prop.expression = formatExpression(prop.expression)
        })
    }

    return BindingxFunction(options, options && options.eventType === 'timing' ? fixCallback(callback) : callback)
}

module.export =  _WeexBinding

```

**Comment by huxiaoqi567** [comment]
@PerseveranceZ  thank you for your advice. `bindingx-parser` is an easy way to parse expression that you just write the original expression. I'd build multiple entry files in weex-bindingx@0.0.17, you can quote individually. Just like `require('weex-bindingx/lib/index.weex.js')` (about 18kb) on weex and `require('weex-bindingx/lib/index.web.js')` (about 80kb) on web .

**Comment by PerseveranceZ** [comment]
@huxiaoqi567 @tw93 Perfect! thanks very much.

**Comment by tw93** [comment]
In addition, you can upgrade `weex-ui` version to `weex-ui@0.6.0-beta-2`, currently using only the weex version of the bindingx, Maybe a little bit smaller.

**Comment by PerseveranceZ** [comment]
@tw93 Cooool~
Finally JS bundle size:
![image](https://user-images.githubusercontent.com/13193407/37811170-6f598e16-2e93-11e8-9592-c2d27416afe4.png)
@tw93 @huxiaoqi567 thanks for your help!
