### ISSUE TITLE
wxc-tab-page back cause shadow.

### ISSUE THREAD

**Issue by PerseveranceZ** [alibaba/weex-ui#192]
##### 1.Your development environment（weex、weex-toolkit、system and more).    
 - Two level pages use wxc-tab-page will cause shadow.
 
![image](https://s18.postimg.org/x5wokzz15/ui-error.gif)

##### 2.Expected behavior and actual behavior.   
 - No shadow.

![image](https://s18.postimg.org/oavuajn49/ui-success.gif)

##### 3.Steps to reproduce the problem.    
Two ways can fix:
1. Add attrrbute in template.
```
<wxc-tab-page style="overflow: hidden;">
```
 2. Add attrrbute`overflow: hidden` in  **wxc-tab-page/index.vue style .wxc-tab-page** .

**Comment by tw93** [comment]
Thanks for the feedback, I'll add
Maybe get rid of the default attribute in the beta version.
