### ISSUE TITLE
wxc-tab-page error

### ISSUE THREAD

**Issue by Z-Janp** [alibaba/weex-ui#193]
##### 1.Your development environment（weex、weex-toolkit、system and more).    
 -  WeexSDK: 0.18.0
 -  BindingX: 1.0.0
weex -v
   v1.2.9
 - weexpack : v1.1.5
 - weex-debugger : v1.0.6
 - weex-builder : v0.3.14
 - weex-previewer : v1.4.6

##### 2.Expected behavior and actual behavior.   
 - Sliding to switch tabpage
 - app breakdown

##### 3.Steps to reproduce the problem.    
 - open weex-ui demo at Native app
 - open tab-page
 - slide the card
 - app will be broke
 - xcode show 
`
Thread 1: signal SIGABRT
`

**Comment by tw93** [comment]
Maybe you need import bindingx for your App
<https://github.com/alibaba/bindingx#installation>

**Comment by Z-Janp** [comment]
yes. I did import, but not work.

**Comment by tw93** [comment]
Show me the error details.

**Comment by tw93** [comment]
update BindingX to update 1.0.1
