### ISSUE TITLE
tabbar底部切换会稍微卡顿，不流畅

### ISSUE THREAD

**Issue by pcwang0205** [alibaba/weex-ui#195]
tabbar底部切换会稍微卡顿，不流畅，但是用weex官方提供的WeexPlayGround不会卡顿，请问为啥？
官方提供的weexPlayGround扫描出来是h5?

**Comment by tw93** [comment]
不是H5，是Weex的
在自己的playground比较卡的原因，可能是之前用久了，导致内存涨了才卡
建议这里有Native能力的同学通过 native 实现 component ，体验会更好~

**Comment by pcwang0205** [comment]
@tw93 是集成在自己的APP中会卡。。
