### ISSUE TITLE
编译时报错weex-ui@0.1.0@weex-ui\packages\wxc-button\index.vue: Unexpected token

### ISSUE THREAD

**Issue by feifei8** [alibaba/weex-ui#2]
Module build failed: SyntaxError: E:\代码\weex\weex-hackernews\node_modules\_weex-ui@0.1.0@weex-ui\packages\wxc-button\index.vue: Unexpected token (35:8)

      33 |       const { type, disabled, btnStyle } = this;
      34 |       const mrBtnStyle = {
    > 35 |         ...STYLE_MAP[type],
         |         ^
      36 |         ...btnStyle
      37 |       };
      38 |       return disabled ? {

**Comment by tw93** [comment]
https://alibaba.github.io/weex-ui/#/cn/with-weex-toolkit?id=%E5%9C%A8%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8-weex-ui
这里没有配置好
