### ISSUE TITLE
组件上的使用style的动态数值，计算有误？？

### ISSUE THREAD

**Issue by vebin** [alibaba/weex-ui#200]
![image](https://user-images.githubusercontent.com/3676141/37900308-687f3584-3120-11e8-9bd1-d684c192034e.png)
![image](https://user-images.githubusercontent.com/3676141/37900324-788dd08e-3120-11e8-86a0-500eebb316d4.png)
![image](https://user-images.githubusercontent.com/3676141/37900326-7ab6f264-3120-11e8-89cd-4629c41fca38.png)

**Comment by tw93** [comment]
loading 此处计算正确，但是你的最外层div需要设置高度，同时loading 建议放到最外层第一层的子节点
