### ISSUE TITLE
wxc-overlay怎样做到覆盖住Activity上的Toolbar的??

### ISSUE THREAD

**Issue by legenli** [alibaba/weex-ui#217]
请问wxc-overlay是怎样做到覆盖住Activity上的Toolbar的，我发现直扫码weex-ui的demo的二维码是可以覆盖住Toolbar，但我自己写的例子不行，能告知是怎样实现的吗?

**Comment by tw93** [comment]
直接看源码~
https://github.com/alibaba/weex-ui/blob/master/packages/wxc-noticebar/index.vue
