### ISSUE TITLE
WxcGridSelect 和recycle-list 在一个页面中使用页面会闪退

### ISSUE THREAD

**Issue by super-chen** [alibaba/weex-ui#219]
##### 1.Your development environment（weex、weex-toolkit、system and more).    
 - Dev platform: Mac
 - Node: 8.10.0
 - Npm: 5.6.0

##### 2.Expected behavior and actual behavior.   
 - WxcGridSelect 和recycle-list 在一个页面中使用页面会闪退

**Comment by tw93** [comment]
目前 recycle-list 使用上面有很多限制 http://weex-project.io/cn/references/components/recycle-list.html#zhu-yi-shi-xiang
需要等到 recycle-list 支持

暂时不建议在recycle-list 里面使用weex-ui 组件 建议用list 就好
此处新recycle-list的定位是具有很强回收和复用的能力list 更多场景是 data -view 绑定好的特定场景

**Comment by pcwang0205** [comment]
@tw93 用list的在某种情况下存在问题:
list有多个header
当header悬浮时，刷新list的其他section的cell，此时header会被隐藏掉。请问有解决方法吗？
