### ISSUE TITLE
没有tab吗，就像iOS下面常见的tabbar一样

### ISSUE THREAD

**Issue by sunzhongliangde** [alibaba/weex-ui#22]
没有tab吗，就像iOS下面常见的tabbar一样

**Comment by tw93** [comment]
后续有计划提供

**Comment by MIAPP-H5** [comment]
强烈需求提供这个组件！

**Comment by jlsky** [comment]
http://www.debugrun.com/a/eUqPTnV.html
参考这个链接。我认为不要像例子里那样计算屏幕高度。flex：1 这样用（http://weex-project.io/cn/references/common-style.html）适应性更好--我在安卓和苹果里分别试了。
另外有个， bui weex里直接有这个组件。不想用他的整套，可以把其中的那两个组件考出来，稍微修改下样式部分。

**Comment by marekchen** [comment]
@tw93 有开源的时间表吗？

**Comment by tw93** [comment]
https://github.com/alibaba/weex-ui/projects/1

**Comment by tw93** [comment]
@marekchen  @sunzhongliangde @MIAPP-H5
> npm i weex-ui@latest -S

详细文档   https://alibaba.github.io/weex-ui/#/./packages/wxc-tab-bar/
