### ISSUE TITLE
recycle-list 里嵌套 wxc-pan-item 组件内容无法显示

### ISSUE THREAD

**Issue by shaibaoj** [alibaba/weex-ui#220]
recycle-list 里嵌套 wxc-pan-item 组件，wxc-pan-item 里内容无法显示

**Comment by tw93** [comment]
目前 recycle-list 使用上面有很多限制  http://weex-project.io/cn/references/components/recycle-list.html#zhu-yi-shi-xiang
需要等到 recycle-list 支持

暂时不建议在recycle-list 里面使用weex-ui 组件  建议用list 就好
此处新recycle-list的定位是具有很强回收和复用的能力list  更多场景是 data -view 绑定好的特定场景
