### ISSUE TITLE
日历组件 ，在web下，能自动滚动到选择的时间区间，但是在android和ios上不能滚动到选择区间。

### ISSUE THREAD

**Issue by zqqq** [alibaba/weex-ui#221]
日历组件 ，在web下，能自动滚动到选择的时间区间，但是在android和ios上不能滚动到选择区间。
![web](https://user-images.githubusercontent.com/10234272/38160321-6008ca38-34ee-11e8-9f07-12ce9623a192.png)
![ios](https://user-images.githubusercontent.com/10234272/38160323-646139c6-34ee-11e8-8901-001882769d29.png)

**Comment by tw93** [comment]
设置一个高度试试~
