### ISSUE TITLE
wxc-tab-page questions about the width of title

### ISSUE THREAD

**Issue by JerrySir** [alibaba/weex-ui#228]
i have a questions, how to set the wxc-tab-page's title, achieve automatic set title's width, i set the tab-styles's width parameter, but the looks's verry ugly.
![111](https://user-images.githubusercontent.com/20677373/38285468-e1555186-37f2-11e8-901b-2e429c39817d.jpg)
![222](https://user-images.githubusercontent.com/20677373/38285470-e5a831ae-37f2-11e8-9f94-0d2b22b835b5.jpg)

**Comment by JerrySir** [comment]
我有一个问题，如何设置wxc-tab-page的title，让它自动设置宽度，我现在手动设置的tab-styles的width参数，但是看起来挺丑的

**Comment by tw93** [comment]
https://alibaba.github.io/weex-ui/#/cn/packages/wxc-tab-page/?id=%E6%B3%A81%EF%BC%9A%E8%87%AA%E5%AE%9A%E4%B9%89%E5%A4%B4%E9%83%A8%E5%AF%BC%E8%88%AA%E5%9D%97
