### ISSUE TITLE
wxc-icon 在devtool 报错

### ISSUE THREAD

**Issue by shenmashi** [alibaba/weex-ui#234]
WXComponentFactory error type:[span] class not found

**Comment by tw93** [comment]
错误麻烦详细点儿~

**Comment by tw93** [comment]
请将项目weex-vue-loader更新
同时这个错误看起来是web端降级了的一个报错，或者是你在weex中使用了 span标签导致，和wxc-icon关系不大，假如没有bug错误，暂时不关注也可以
