### ISSUE TITLE
终于找到你，weex ui！顺便求一个upload文件的组件，日历选择器希望能加“时分秒”

### ISSUE THREAD

**Issue by SteveCruise** [alibaba/weex-ui#235]
##### 1.Your development environment（weex、weex-toolkit、system and more).    
 - weex

##### 2.Expected behavior and actual behavior.   
 - 求一个upload文件的组件
 - 日历选择器希望能加“时分秒”，包括单程和往返
 - 饿了么都被你们收购了，干脆和element ui团队合并呗

**Comment by tw93** [comment]
关于1：现在upload组件需要合Native这边module配合，不太适合将功能放到weex-ui中，可以客户端自行实现
关于2：这种交互感觉会有些怪哦，可以点击日历回调然后再用datePicker弹出，自己组织就好
关于3：欢迎大家给Weex Ui 提交 PR  ：）

**Comment by webthen** [comment]
关于2：这种交互感觉会有些怪哦 

这种交互怪的理由是什么？
市场是有需求的。

可能被element ui惯坏了，里面的组件过分全。
