### ISSUE TITLE
bind-env.js

### ISSUE THREAD

**Issue by 377123** [alibaba/weex-ui#238]
ERROR in ./node_modules/weex-ui/packages/utils/bind-env.js
Module not found: Error: Can't resolve 'weex-bindingx/lib/index.weex.js' in '/Users/ring/wwwroot/one_eros/node_modules/weex-ui/packages/utils'
 @ ./node_modules/weex-ui/packages/utils/bind-env.js 7:17-59
 @ /Users/ring/.nvm/versions/node/v8.10.0/lib/node_modules/eros-cli/node_modules/_weex-vue-loader@0.6.1@weex-vue-loader/lib/script-loader.js!/Users/ring/.nvm/versions/node/v8.10.0/lib/node_modules/eros-cli/node_modules/_babel-loader@7.1.4@babel-loader/lib!/Users/ring/.nvm/versions/node/v8.10.0/lib/node_modules/eros-cli/node_modules/_weex-vue-loader@0.6.1@weex-vue-loader/lib/selector.js?type=script&index=0!./node_modules/weex-ui/packages/wxc-tab-page/index.vue
 @ ./node_modules/weex-ui/packages/wxc-tab-page/index.vue
 @ ./node_modules/weex-ui/packages/wxc-tab-page/index.js
 @ /Users/ring/.nvm/versions/node/v8.10.0/lib/node_modules/eros-cli/node_modules/_weex-vue-loader@0.6.1@weex-vue-loader/lib/script-loader.js!/Users/ring/.nvm/versions/node/v8.10.0/lib/node_modules/eros-cli/node_modules/_babel-loader@7.1.4@babel-loader/lib!/Users/ring/.nvm/versions/node/v8.10.0/lib/node_modules/eros-cli/node_modules/_weex-vue-loader@0.6.1@weex-vue-loader/lib/selector.js?type=script&index=0!./src/js/pages/lives/earn/index.vue
 @ ./src/js/pages/lives/earn/index.vue?entry=true

**Comment by tw93** [comment]
缺少 weex-bindingx 依赖，按理安装weex-ui 最新版本会自动安装
请重新更新weex-ui试试
或者直接
> npm i weex-bindingx@0.0.17 -S 手动更新试试
