### ISSUE TITLE
wxc-tab-bar 跟wxc-minibar不能搭配使用

### ISSUE THREAD

**Issue by WilliamALiang** [alibaba/weex-ui#239]
Try to search for your [issue](https://github.com/alibaba/weex-ui/issues?utf8=%E2%9C%93&q=), it may have already been answered or even fixed in the development branch. 
 
 在开 issue 前，可以先搜索以下以往的旧 [issue](https://github.com/alibaba/weex-ui/issues?utf8=%E2%9C%93&q=)，你遇到的问题可能已经有人提了，也可能已经在最新版本中被修正。

开源项目的用户和维护者之间并不是甲方和乙方的关系，issue 也不是客服。
在开 issue 的时候，请抱着一种『一起合作来解决这个问题』的心态，同时请尽可能描述清楚，这样效率才会高。

Remember to delete the above statement before committing.
同时建议使用英语进行描述，这样国外的开发者也可以看懂，提交之前，记得将上述说明删除。

##### 1.Your development environment（weex、weex-toolkit、system and more).    
 - 
 - 

##### 2.Expected behavior and actual behavior.   
 - 
 - 

##### 3.Steps to reproduce the problem.    
 - 
 -

**Comment by tw93** [comment]
可能你是将wxc-minibar放到了tab-bar组件的里面了，直接放到平级的地方即可
同时这里建议使用客户端自己的navigatorBar体验更好，更加可控

**Comment by xiaozehao** [comment]
确实是不能一起用
![image](https://user-images.githubusercontent.com/9866297/39664045-c0b8d71a-50af-11e8-9d8e-ac3fbf90ab49.png)
![image](https://user-images.githubusercontent.com/9866297/39664046-c8f4f24c-50af-11e8-9055-ebc41ed5b8ad.png)

**Comment by xchz** [comment]
@tw93 wxc-tab-bar组件渲染后会加上position: absolute;top: 0px;，顶部的minibar被遮挡了

**Comment by xchz** [comment]
@xiaozehao wxc-tab-bar不能被两层div包裹，不然就会出现tabbar不在底部的问题,,,,,,看来问题还是蛮多的

**Comment by xchz** [comment]
```
<template>
  <div class="wrapper">
      <!-- 这里不能再添加div，否则wxc-tab-bar不能固定在底部-->
      <!--<div>-->
      <wxc-minibar title="告警监控"
                   background-color="#2da45d"
                   text-color="#FFFFFF"
                   left-button='https://gw.alicdn.com/tfs/TB1cAYsbv2H8KJjy0FcXXaDlFXa-30-53.png'
                   right-text=""
                   @wxcMinibarLeftButtonClicked="minibarLeftButtonClick"
                   @wxcMinibarRightButtonClicked="minibarRightButtonClick"></wxc-minibar>
      <wxc-tab-bar :tab-titles="tabTitles"
                   :tab-styles="tabStyles"
                   title-type="icon"
                   @wxcTabBarCurrentTabSelected="wxcTabBarCurrentTabSelected">
          <!-- 第一个页面内容-->
          <div class="item-container" :style="contentStyle"><text>首页</text></div>

          <!-- 第二个页面内容-->
          <div class="item-container" :style="contentStyle"><text>特别推荐</text></div>

          <!-- 第三个页面内容-->
          <div class="item-container" :style="contentStyle"><text>消息中心</text></div>

          <!-- 第四个页面内容-->
          <div class="item-container" :style="contentStyle"><text>我的主页</text></div>
      </wxc-tab-bar>
      <!--</div>-->
  </div>
</template>

<script>
import { WxcTabBar, Utils, WxcMinibar } from 'weex-ui'
import Config from './components/config'
const CART_ICON =
  'https://gw.alicdn.com/tfs/TB1HrvtbBTH8KJjy0FiXXcRsXXa-32-32.png'
const RETURN_ICON = 'https://gw.alicdn.com/tfs/TB1cAYsbv2H8KJjy0FcXXaDlFXa-30-53.png'
const modal = weex.requireModule('modal')
export default {
  components: { WxcTabBar, WxcMinibar },
  data: () => ({
    tabTitles: Config.tabTitles,
    tabStyles: Config.tabStyles,
    rightButton: CART_ICON,
    leftButton: RETURN_ICON
  }),
  created () {
    const tabPageHeight = Utils.env.getPageHeight()
    // 如果页面没有导航栏，可以用下面这个计算高度的方法
    // const tabPageHeight = env.deviceHeight / env.deviceWidth * 750;
    const { tabStyles } = this
    this.contentStyle = { height: (tabPageHeight - tabStyles.height - 180) + 'px' }
  },
  methods: {
    wxcTabBarCurrentTabSelected (e) {
      const index = e.page
      console.log(index)
    },
    minibarLeftButtonClick () {
    },
    minibarRightButtonClick () {
      modal.toast({ 'message': 'click rightButton!', 'duration': 1 })
    }
  }
}
</script>

<style scoped>
    .item-container {
        width: 750px;
        background-color: #f2f3f4;
        align-items: center;
        justify-content: center;
    }
</style>

```

**Comment by xchz** [comment]
![image](https://user-images.githubusercontent.com/7054257/45200976-e53b0b00-b2a5-11e8-8899-b98df8e4a884.png)

**Comment by xchz** [comment]
@tw93 兄弟 麻烦指导一下，，，

**Comment by xchz** [comment]
找到解决办法了[Weex 目前不支持 z-index 设置元素层级关系，但靠后的元素层级更高，因此，对于层级高的元素，可将其排列在后面](http://weex.apache.org/cn/wiki/common-styles.html#ding-wei)，因此可以将wxc-minibar放在wxc-tab-bar之后，那么wxc-minibar就不会被wxc-tab-bar遮挡了 哈哈

**Comment by hilads** [comment]
> 找到解决办法了[Weex 目前不支持 z-index 设置元素层级关系，但靠后的元素层级更高，因此，对于层级高的元素，可将其排列在后面](http://weex.apache.org/cn/wiki/common-styles.html#ding-wei)，因此可以将wxc-minibar放在wxc-tab-bar之后，那么wxc-minibar就不会被wxc-tab-bar遮挡了 哈哈

求指教 为什么我把wxc-minibar放在wxc-tab-bar之后  wxc-minibar盖着了 我的部分内容

**Comment by hilads** [comment]
@xchz 求指教 为什么我把wxc-minibar放在wxc-tab-bar之后  wxc-minibar盖着了 我的部分内容
