### ISSUE TITLE
部分组件会报错

### ISSUE THREAD

**Issue by Zijing-Li** [alibaba/weex-ui#24]
按照readme中的方式使用weex-ui,在导入部分组件的时候直接报错，发现是由于那些组件vue文件中使用了module.exports初始化，改成export default就不报错了，所以目前是直接copy源码修改了在使用。望修改

**Comment by tw93** [comment]
可以参考下这个   https://github.com/alibaba/weex-ui#weex-toolkit

**Comment by Zijing-Li** [comment]
完全按照 https://github.com/alibaba/weex-ui#weex-toolkit 来做的，但是并非所有组件都能直接用。
比如：wxc-button能用，但是wxc-popup却会报错，查看了wxc-popup源码发现里面是这样初始化的
`
module.exports = {...}
`
iOS端SDK0.15.1会报错：
`
 TypeError: Attempted to assign to readonly property.
`
改成
`
export default {...}
`
后就能正常使用了，这是否是SDK版本不兼容导致？

**Comment by tw93** [comment]
好的 谢谢反馈哦 下一个版本进行修复~

**Comment by tw93** [comment]
更新到最新版0.2.0beta
