### ISSUE TITLE
WxcButton 在 v0.6.1版本中，borderColor 无效

### ISSUE THREAD

**Issue by wyh497823256** [alibaba/weex-ui#243]
weex SDK v0.18
weex-ui v0.6.1

> 代码：

```
<wxc-button text="编辑"
                                    type="normal"
                                    v-if="item.status!=0"
                                    :text-style="deleteBtnTextStyle"
                                    :btn-style="deleteBtnStyle"
                                    @wxcButtonClicked="couponDetailClick(item)"/>
```
```
computed: {
            deleteBtnStyle() {

                let deleteBtnStyle = {};
                deleteBtnStyle.width = '100px';
                deleteBtnStyle.height = '60px';
                deleteBtnStyle.padding = '4px';
                deleteBtnStyle.borderColor = '#42BD56';
                deleteBtnStyle.marginLeft = '16px';
                return deleteBtnStyle;
            },
            deleteBtnTextStyle() {
                let deleteBtnTextStyle = {};
                deleteBtnTextStyle.color = '#42BD56';
                deleteBtnTextStyle.fontSize = '24px'
                return deleteBtnTextStyle;
            },
      }
```

> 在  `v0.6.1` 当中的表现如下图
<img width="147" alt="2018-04-17 5 30 00" src="https://user-images.githubusercontent.com/8830870/38861371-ffdfcfba-4264-11e8-99ef-d0b44def164a.png">

>  在  `v0.5.3`当中的表现如下图

<img width="150" alt="2018-04-17 5 25 37" src="https://user-images.githubusercontent.com/8830870/38861385-0bde4738-4265-11e8-9262-0dd9e5f6ca07.png">

**# 在 v 0.5.3 的borderColor 是没有问题的，升级到 v 0.6.1 borderColor 无效。**

**Comment by tw93** [comment]
分配给@GJJDD

**Comment by wyh497823256** [comment]
@GJJDD 补充下，wxc-cell 设置 height: 80px ,在v.0.5.3 和 v0.6.1 到表现也不一样。

**Comment by GJJDD** [comment]
@wyh497823256 在 weex-ui 0.6.0 版本以上，我们对 type api 有对应修改，同时新增 size api 用于设置大小。 请参考 https://alibaba.github.io/weex-ui/#/cn/packages/wxc-button/

**Comment by GJJDD** [comment]
#

**Comment by wyh497823256** [comment]
@GJJDD wxcCell 的高度也受到影响是什么问题。

**Comment by tw93** [comment]
demo 中的 type="normal" 应该换成 type="white" ，cell的问题可以另外提一个issue，这个暂时关闭
