### ISSUE TITLE
weex-ui除了用在weex写的app中，还可以用在网页端吗？

### ISSUE THREAD

**Issue by zwl1619** [alibaba/weex-ui#247]
weex-ui除了用在weex写的app中，还可以用在网页端吗？

**Comment by Yanjiie** [comment]
虽然 weex 使用 Vue 作为 DSL，但不建议在直接用 Vue 开发的网页端中使用 wee ui，因为 weex ui 在 H5 端中依赖于 weex-vue-render。

**Comment by tw93** [comment]
网页主要用于三端一致性，一套代码3端运行，网页端主要是H5，起到外投时降级兼容作用，重点还是客户端自己的Weex 体验
