### ISSUE TITLE
weex写的app要上传图片，怎么调用相册和摄像头？

### ISSUE THREAD

**Issue by zwl1619** [alibaba/weex-ui#249]
weex写的app要上传图片，点击上传按钮的时候，弹出一个菜单，一个是从相册选择，一个是用相机拍摄，那么weex中怎么调用相册和摄像头呢？

**Comment by tw93** [comment]
这里需要结合Native来弄，可以在群里咨询大家看看怎么弄，或者使用现有的plugin
