### ISSUE TITLE
wxc-popup中出现的bug

### ISSUE THREAD

**Issue by beijinaqie** [alibaba/weex-ui#251]
当pos为bottom时，如果content内容里面出现input，会遮挡住内容区域，另外能不能加一个属性，middle居中。weex的input最主要问题就是触发input的时候，系统键盘无法准确弹起，而且输入框内容无法事件清除。

**Comment by tw93** [comment]
今天发布的 0.6.2新增 top 字段，可以用来控制

**Comment by wilson-0422** [comment]
这个组件好像不能背景透明……

**Comment by tw93** [comment]
请使用 weex-ui@0.6.3-beta1 版本
目前popup已经新增`stand-out`来设置突出边框的高度
同时@wilson-0422 遮罩层的透明度一直可以通过`overlay-cfg`这个参数设置
