### ISSUE TITLE
WxcIcon 组件使用本地JS加载出现错误

### ISSUE THREAD

**Issue by ErHu1993** [alibaba/weex-ui#253]
在项目中我对JS文件进行了缓存, 缓存后的地址为 file://xxxx, 当Weex渲染完成后,发现使用WxcIcon组件的地方图片出不来, 显示这样
![image](https://user-images.githubusercontent.com/15101170/39296885-aeca1aa6-4974-11e8-90b4-d1898907d4a4.png)

看了下WxcIcon 的源码index.vue  发现如下引入:
```
beforeCreate () {
    dom.addRule('fontFace', {
      'fontFamily': 'weexUiIconFont',
      'src': "url('//at.alicdn.com/t/font_520368_r89ekv69euahsemi.ttf')"
    })
  },
```

其中的url里是不是不应该有 "//" 去引用, 而应该是http://at.alicdn.com/t/font_520368_r89ekv69euahsemi.ttf 的方式?

不知这是否是你们的Bug ~ 于是就提下问问

**Comment by ErHu1993** [comment]
iOS 系统~

**Comment by tw93** [comment]
欢迎PR，这种问题直接替换下就好

**Comment by tw93** [comment]
请使用 weex-ui@0.6.3-beta 版本 已经修复
