### ISSUE TITLE
wxc-tab-page 组件  slot如果不设置宽高不显示

### ISSUE THREAD

**Issue by chujian0719** [alibaba/weex-ui#256]
解决办法：
       源码中 class  tab-container 中 position: absolute 影响所致  添加 top:0;bottom:0, left:0; right: 0;

**Comment by Yanjiie** [comment]
可以直接提交PR哦

**Comment by tw93** [comment]
正常，这里里面slot是需要传入高宽的，有部分场景是用户自定义使用的，同时通过 添加 top:0;bottom:0, left:0; right: 0; 在iOS上面会有不兼容的
