### ISSUE TITLE
Module build failed: SyntaxError packages/wxc-button/index.vue: Unexpected token (43:8)

### ISSUE THREAD

**Issue by gs80140** [alibaba/weex-ui#261]
I copy the code from the sample tab-bar

[372] multi (webpack)-dev-server/client?http://192.168.0.101:8081 ./temp/_mods/category.js?entry=true 40 bytes {2} [built]
     + 81 hidden modules

ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./~/weex-ui/packages/wxc-button/index.vue
Module build failed: SyntaxError: C:/app/codes/dmaio_niu/niu-app/node_modules/weex-ui/packages/wxc-button/index.vue: Unexpected token (43:8)

  41 |
  42 |       const mrBtnStyle = {
> 43 |         ...STYLE_MAP[type],
     |         ^
  44 |         ...btnStyle,
  45 |         ...BUTTON_STYLE_MAP[size]
  46 |       };

It seems very easy to get error ,not easy to use.
no document.

**Comment by gs80140** [comment]
I got it

it is because I didn't install babel-preset-stage-0 

use this command
npm i babel-plugin-component babel-preset-stage-0 -D

and modify .babelrc to
{
  "presets": ["es2015", "stage-0"],
  "plugins": [
    [
      "component",
      {
        "libraryName": "weex-ui",
        "libDir": "packages",
        "style": false
      }
    ]
  ]
}

**Comment by hongxinfeiyang** [comment]
I have the same problem.

use this command
npm i babel-plugin-component babel-preset-stage-0 -D
and modify .babelrc 

but  it's still a mistake.
development environment:  centos 6.8 ,node(6.9.2 ~ 10.+)

seek the answer of the God.

**Comment by tw93** [comment]
If babel-loader in webpack.config.js has a exclude for node_modules, please turn on for week-ui as exclude: /node_modules(?!(\/|\\).*(weex).*)/.
