### ISSUE TITLE
用的<list><cell>标签安卓和iOS显示效果不一样

### ISSUE THREAD

**Issue by cykl4451** [alibaba/weex-ui#266]
![image](https://user-images.githubusercontent.com/30775058/40094634-bb7ba81a-58fa-11e8-8396-9f91d3ff64a7.png)
![image](https://user-images.githubusercontent.com/30775058/40094642-cf633ba4-58fa-11e8-8cf2-ab7a1b1b7daa.png)
![image](https://user-images.githubusercontent.com/30775058/40094980-5cdc4754-58fc-11e8-8ead-65230c53df4e.png)
![image](https://user-images.githubusercontent.com/30775058/40094647-d6433ac8-58fa-11e8-9b12-bfa0a63724c9.png)

![image](https://user-images.githubusercontent.com/30775058/40094993-67ddd8de-58fc-11e8-95c2-4a180c0a7eaf.png)
Android显示

![image](https://user-images.githubusercontent.com/30775058/40094743-4e141be4-58fb-11e8-96c6-19db7629ef2f.png)
ISO显示结果

![image](https://user-images.githubusercontent.com/30775058/40095026-8301b98c-58fc-11e8-9745-a54dd483e19b.png)
试例显示正常

用的<list><cell>标签，在<cell>里面定义了一个子组件，在子组件里设置了样式，但是最后显示的效果iOS和Android显示的不一样，请帮忙纠正一下。谢谢

**Comment by cykl4451** [comment]
![image](https://user-images.githubusercontent.com/30775058/40095081-c70406e4-58fc-11e8-877e-6eb17ee953de.png)
zi子组件的样式

**Comment by tw93** [comment]
不要用margin来间隔cell，cell里面可以用margin，同时此类问题不建议提issue来咨询，直接群里咨询就好
