### ISSUE TITLE
About immersion status bar for Android

### ISSUE THREAD

**Issue by TaroXin** [alibaba/weex-ui#267]
I want to get support for `Android immersion status bar`.

When i use the `wxc-minibar`，i don't want I need to add support for immersion status bar in Android program

Hope `weex-ui` adds `Android and IOS` native component library to facilitate the use of some `native component-specific features`

**Comment by tw93** [comment]
I'm sorry
Now weex UI is more targeted at UI layer components while allowing users to be incompatible.
Here, `About immersion status bar for Android` needs to modify native code, which is not suitable for UI layer implementation. It can modify native side support by itself.
