### ISSUE TITLE
wxc-button的计算属性中引用了未知type

### ISSUE THREAD

**Issue by pop0505** [alibaba/weex-ui#268]
##### 1.Your development environment（weex、weex-toolkit、system and more).    
 - weex-toolkit

##### 2.Expected behavior and actual behavior.   
 - 在使用`wxc-button`的时候，如果状态发生改变，比如`disabled=true `变为 `disabled=false`，在按钮样式中的文字颜色会变成黑色。经查阅源码，发现在`wxc-button/index.vue `61行中代码如下
```
        const mrTextStyle = { ...TEXT_STYLE_MAP[type], ...textStyle, ...TEXT_FONTSIZE_STYLE_MAP[size] };
```
- 再去`type.js`中找到`TEXT_STYLE_MAP`的定义如下：
```
export const TEXT_STYLE_MAP = {
  taobao: {
    color: '#FFFFFF'
  },
  fliggy: {
    color: '#3D3D3D'
  },
  white: {
    color: '#3D3D3D'
  }
};
```
- 而新版本中`type`的可选值为`white`、`red`、`yellow`、`blue`，`TEXT_STYLE_MAP`中为`taobao`、`fliggy`、`white`，假如我使用`type=red`，在TEXT_STYLE_MAP就找不到该属性，因此计算属性最后的结果会将按钮文字赋为默认的`#000000`黑色。

##### 3.Steps to reproduce the problem.    
 - 如上。

**Comment by tw93** [comment]
谢谢反馈，@GJJDD 跟进一下哦

**Comment by tw93** [comment]
已经修复，请升级到 weex-ui@0.6.4-beta版本
> npm i weex-ui@latest -S

**Comment by yinianjiqi** [comment]
wxc*button里的事件回调@wxcButtonClicked="wxcButtonClicked"应该怎么回调啊？我是初学者有点不会回调
