### ISSUE TITLE
How can I resolve the warnings in the command 

### ISSUE THREAD

**Issue by AppianZ** [alibaba/weex-ui#269]
##### 1.Your development environment（weex、weex-toolkit、system and more).    
 - weex v1.3.5
 - weex-ui v0.6.3-beta3
 - system mac

##### 2.Expected behavior and actual behavior.   
 -  I hope I can hide the warnings about css in the command or I can resolve the warnings by modifying code
 - 我希望能隐藏控制台的很多关于css的warning，或者我手动修改也可以。

![image](https://user-images.githubusercontent.com/15190615/40162506-c98f42d0-59e6-11e8-9371-125e70772e8a.png)

- This is a warning about the "wxc-tab-bar" component of weex-ui

- 这是一个 Weex-ui 的一个组件 -- 底部 tab-bar 底部标签页的组件的warning

**Comment by tw93** [comment]
升级一下weex-vue-loader试试

**Comment by AppianZ** [comment]
我是用 "vue-loader": "^12.2.0",

**Comment by AppianZ** [comment]
我目前用的是vue-loader v12.2.0

**Comment by PerseveranceZ** [comment]
@AppianZ 配置 webpack stats warnings: false ，忽略他

**Comment by AppianZ** [comment]
stats？

**Comment by tw93** [comment]
是weex-vue-loader的版本不是vue-loader版本哦
同时关于stats的配置可以参考这里 https://webpack.js.org/configuration/stats/
