### ISSUE TITLE
weex-ui的响应是怎么实现的？官方文档没找到。

### ISSUE THREAD

**Issue by ada90** [alibaba/weex-ui#27]
补充：动态样式响应

**Comment by ada90** [comment]
weex-ui中生成的行内动态宽高是在编译阶段就生成的吗？可否告知方法？

**Comment by alex1226** [comment]
事件生成：self.$emit  事件消费：@on** = "**handler" 类似注册事件处理函数，可以参考playgroud里面的例子。

**Comment by tw93** [comment]
You can see the vue computed property here https://vuejs.org/v2/guide/computed.html
Aslo can see the source in weex ui package
