### ISSUE TITLE
The height of item-container in wxc-tab-bar isn't correct on Android

### ISSUE THREAD

**Issue by yhvh009** [alibaba/weex-ui#271]
##### 1.Your development environment（weex、weex-toolkit、system and more).    
 - weex v1.3.5
 - weex-ui v0.6.3
 - system mac
 - Android simulator(Nexus 5x api 25, android 7.1.1, 1080 * 1920 :420dpi)

##### 2.Expected behavior and actual behavior.   
 - The height of item-container in wxc-tab-bar isn't correct on Android
 - 使用demo中的例子，但在安卓模拟器中实际item-container的高度有问题

##### 3.Steps to reproduce the problem.    

- 按照官方demo中，在首屏item-container底部加一个div，在安卓模拟器中没有显示出来（表示实际item-container的高度大于期望的可视高度），在750的ios模拟器中是正常的表现

 - add a div to the bottom in the item-container, but it didn't appear.
 - 
![image](https://user-images.githubusercontent.com/5066025/40223867-029ac826-5ab7-11e8-942d-aa5c8b9c02f9.png)

![image](https://user-images.githubusercontent.com/5066025/40223752-abf4b5a4-5ab6-11e8-9816-513764ebce2f.png)
![image](https://user-images.githubusercontent.com/5066025/40223885-110cb55e-5ab7-11e8-884a-bc8ef3e912af.png)

 - but it's ok on ios sim.
![image](https://user-images.githubusercontent.com/5066025/40223830-e567b53e-5ab6-11e8-9d28-5c911e50bcf1.png)

**Comment by yhvh009** [comment]
原因找到了，其实是顶部statusbar的原因，没有把statusbar的高度刨除

**Comment by cyl123** [comment]
statusbar的高度你设置的多少啊！
