### ISSUE TITLE
wxc-slider-bar，更改value值滑动条视图不更新

### ISSUE THREAD

**Issue by yzxbear** [alibaba/weex-ui#275]
##wxc-slider-bar滑动输入，设置value属性后视图未更新
![image](https://user-images.githubusercontent.com/21104214/40463813-e13df418-5f49-11e8-908f-de06ba90e791.png)

**Comment by tw93** [comment]
已经修复，谢谢反馈
请升级weex-ui到weex-ui@0.6.4-beta1
> npm i weex-ui@latest -S

**Comment by yzxbear** [comment]
好的，谢谢了。
