### ISSUE TITLE
引入weex-ui报错

### ISSUE THREAD

**Issue by awhlmycn** [alibaba/weex-ui#28]
import WxcButton from './packages/wxc-button';

Uncaught SyntaxError: Unexpected token import

按钮模块引入不进来

**Comment by tw93** [comment]
参考下这个哦  https://github.com/alibaba/weex-ui#weex-toolkit

**Comment by awhlmycn** [comment]
我按着那个文档来了哦 还是报错
export { default } from './index.vue';
import { WxcButton, WxcPopup } from 'weex-ui';
components: { WxcButton, WxcPopup },
报错： Uncaught SyntaxError: Unexpected token export
export { default } from './index.vue';
希望能帮我解决下：谢谢
