### ISSUE TITLE
weex-ui tab bar styles are changed

### ISSUE THREAD

**Issue by xujiale** [alibaba/weex-ui#280]
##### 1.Your development environment（weex、weex-toolkit、system and more).    
 - system: weex-ui 0.6.3-beta1, iPhone 6s, iOS 10.3.2

##### 2.Expected behavior and actual behavior.   
 - Expected: tab bar's height fixed
- Actual: tab bar's height was change

##### 3.Steps to reproduce the problem.    
 - 1. <input> focus, page is up by keyboard
 - 2. <input> blur, tab bar's height changed

#### 4. code
```
tabStyles: {
    bgColor: '#ffffff',
    titleColor: '#666666',
    activeTitleColor: '#009ff0',
    isActiveTitleBold: true,
    iconWidth: 48,
    iconHeight: 48,
    width: 250,
    height: 96,
    fontSize: 20,
  }
<wxc-tab-bar :tab-titles="tabStyles"></wxc-tab-bar>
```

as show in the image
![qq20180530-0](https://user-images.githubusercontent.com/7278325/40704489-d363f330-641a-11e8-9dcb-1498ffda518b.png)

------------------手动分割--------------
##### 1.Your development environment（weex、weex-toolkit、system and more).    
 - system: weex-ui 0.6.3-beta1, iPhone 6s, iOS 10.3.2有问题，安卓正常

##### 2.Expected behavior and actual behavior.   
 - Expected: tab bar的高度固定，不被改变
- Actual: tab bar的高度被改变了

##### 3.Steps to reproduce the problem.    
 - 1. <input> 聚焦之后，页面被弹出的键盘顶上去了
 - 2. <input> 失焦、键盘关闭之后，tab bar的高度变了

#### 4. code
```
tabStyles: {
    bgColor: '#ffffff',
    titleColor: '#666666',
    activeTitleColor: '#009ff0',
    isActiveTitleBold: true,
    iconWidth: 48,
    iconHeight: 48,
    width: 250,
    height: 96,
    fontSize: 20,
  }
<wxc-tab-bar :tab-titles="tabStyles"></wxc-tab-bar>
```

如上面的图所示

**Comment by xujiale** [comment]
这个问题我后来把tab bar的颜色修改了一下，发现不是tab bar的高度变了，而是键盘弹出来之后把页面顶了上去，关闭键盘后，页面没有下去，所以tab bar也在上面没下来

**Comment by tw93** [comment]
weex 的版本是多少呢？
我记得weex最新版本已经将此类input问题修复
升级都最新weex sdk试试

**Comment by xujiale** [comment]
weex sdk用的是0.18.0。嗯嗯，这应该是weex的问题
