### ISSUE TITLE
popup在弹窗内容很多时加载很慢，导致用户快速点击触发按钮会有不弹窗的现象

### ISSUE THREAD

**Issue by delsedin** [alibaba/weex-ui#281]
安卓机器弹窗速度较慢，弹窗里面的数据一多，就更加慢。配置越低越慢。所以用户快速点击触发弹窗的按钮时，上一次点击触发的弹窗就会在还没有展示的时候就被用户的下一次点击给关闭了
The popup component react slow in android os
 If  data in popup is big,  it behaviors more slower, and it relates to hardware performance
The-pop-component won't display when user tap ping his phone so quick, 
His second tapping close the popup he triggered by first tap

**Comment by jues** [comment]
我也碰到了这个问题

**Comment by tw93** [comment]
weex 性能问题，暂时可以想到的解决办法应该是优化弹层里面组件的性能，数据多是什么样子的？

**Comment by delsedin** [comment]
@tw93 
比如增加了一个scroller的列表，或者是重复了十次以上的<div>块（这个div块大概有三层到四层的结构）

**Comment by tw93** [comment]
暂时无解，不建议在pop里面放太多东西，假如需要放太多东西，建议使用客户端提供一个view实现
