### ISSUE TITLE
[feature]请问weex-ui是修改了什么配置让PC Web也能响应点击事件呢？

### ISSUE THREAD

**Issue by 452MJ** [alibaba/weex-ui#284]
在weex-ui里，需要修改什么东西才能使PC Web上的@click事件得到响应？

新建的weex web工程只有在移动浏览器模式下才能正常点击。

**Comment by tw93** [comment]
这个demo当时是用的一个版本比较低的weex-vue-render  
0.1.2以后的weex-vue-render使用了tap代替click 所以就只有在移动浏览器模式下才能正常点击
但是这个体验更好
毕竟weex页面一般不会在pc运行的

**Comment by ChandleWEi** [comment]
只想问有什么办法在web浏览器上也能正常 这种移动浏览器和PC浏览器的差异表现 哪个文档能查到啊？
