### ISSUE TITLE
/node_modules/weex-ui/packages/wxc-button/index.vue    Module build failed: SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by hongxinfeiyang** [alibaba/weex-ui#285]
1、question：
/node_modules/weex-ui/packages/wxc-button/index.vue
    Module build failed: SyntaxError: Unexpected token (43:8)
      41 | 
      42 |       const mrBtnStyle = {
    > 43 |         ...STYLE_MAP[type],
         |         ^
      44 |         ...btnStyle,
      45 |         ...BUTTON_STYLE_MAP[size]
      46 |       };

2、development environment
    centos 6.8 ,
    node(6.9.2 ~ 10.+)
   "weex-ui": "^0.6.4-beta1"
   "webpack": "^3.12.0"
   "babel-plugin-component": "^1.1.1"
   "babel-preset-stage-0": "^6.24.1"
3、describe

use this command
npm i babel-plugin-component babel-preset-stage-0 -D
and modify .babelrc

but it's still a mistake.
seek the answer of the God.

**Comment by tw93** [comment]
If babel-loader in webpack.config.js has a exclude for node_modules, please turn on for week-ui as exclude: /node_modules(?!(\/|\\).*(weex).*)/.

**Comment by hongxinfeiyang** [comment]
@tw93 
Have been used exclude: /node_modules(?!(/|\).(weex).)/ , but no solution to the problem.
