### ISSUE TITLE
wxc-loading 在Android中无法使用？

### ISSUE THREAD

**Issue by AugTang** [alibaba/weex-ui#286]
wxc-loading 在ios中使用，能够转动。
可是在Android里面，无法使用。
@tw93

**Comment by tw93** [comment]
已知native层面问题，请到这里寻找答案，https://alibaba.github.io/weex-ui/#/cn/faq?id=gif-%E5%9B%BE%E7%89%87%E5%9C%A8-android-%E4%B8%8A%E9%9D%A2%E6%B2%A1%E6%9C%89%E5%8A%A8%E7%94%BB
