### ISSUE TITLE
wxc-city动态加载数据导致搜索不正常的bug

### ISSUE THREAD

**Issue by fyyyr** [alibaba/weex-ui#288]
官方的demo都是直接导入一个data.js进来。而现在遇到的一个需求是这个数据需要通过接口来动态请求。动态请求到数据后，列表成功更新。点击输入框进行搜索，此时出现了两个问题：
1.浏览器中提示了一个warn：[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "sourceData"。
2.若输入字符，又删空输入框，列表会为空，而不会显示动态获取到的数据。
分析：
问题1：查看源码，发现传入组件的数据是放在props中的sourceData字段的。列表的显示就是根据该字段。当动态修改了父组件传入的数据，那么该props.sourceData也会更新，所以列表会更新。然而，当触发onInput事件时，该函数会筛选附和要求的数据，然后用新的数据修改props.sourceData，从而去更新自身列表。关键就在于这个sourceData是个props属性，从子组件修改props，就会弹出上面1中的warn。
问题2：源码中的data有个saveDefaultSourceData字段，用于存储原始的传入数据。当删空输入框时，控件会将saveDefaultSourceData赋给sourceData。然而这个saveDefaultSourceData有个问题就是只在控件初始化时更新一次。当创建控件时，由于数据动态请求的原因，当数据还没返回时，控件已经初始化，所以这个saveDefaultSourceData是一个空列表。而当数据返回后，props中的sourceData会更新，但这个saveDefaultSourceData却并没有更新。于是，当删空输入框，导致saveDefaultSourceData赋给sourceData，就出现了上面2中的问题。
于是，我在获取到数据并更新给sourceData后，直接调用：
this.$refs.wxcCity.saveDefaultSourceData = {...myData};
来手动更新组件的saveDefaultSourceData，问题2会解决。

**Comment by lujiben** [comment]
谢了

**Comment by tw93** [comment]
建议使用 
this.$refs.wxcCity.saveDefaultSourceData = {...myData};  方式
已经加入到文档，谢谢建议
