### ISSUE TITLE
引用WxcPageCalendar 编译时报错

### ISSUE THREAD

**Issue by alex1226** [alibaba/weex-ui#29]
ERROR in invoice.js from UglifyJs
 Unexpected token: name (TRADITIONAL_HOLIDAY) [invoice.js:1973,4]

 ERROR in setting.js from UglifyJs
 Unexpected token: name (TRADITIONAL_HOLIDAY) [setting.js:1206,4]

**Comment by alex1226** [comment]
引用WxcGridSelect没报错，但显示空白。

**Comment by tw93** [comment]
Please follow the same issule here   https://github.com/alibaba/weex-ui/issues/30
I close this
