### ISSUE TITLE
wxc-city的onlyShowList需求

### ISSUE THREAD

**Issue by fyyyr** [alibaba/weex-ui#294]
需求是一个给定的列表，按照给出的顺序显示出来。不需要按拼音排序。
相比于wxc-indexlist，wxc-city带着搜索功能，所以考虑使用wxc-city。
wxc-city是必须要传入pinyin和py字段的，否则就不显示结果。而要显示的列表并没有可以映射到这两个字段的变量，于是默认都赋值一个a，这样就能按顺序正常显示结果了。
然而，这样的一个问题是列表上方会显示一个A导航，右侧有个字母导航条。
设置控件的showIndex属性为false，可以隐藏掉右侧的字母导航条。然而上方的A导航还是一直在显示。
查看源码，发现控件有个onlyShowList属性，可以把上方的A导航也给隐藏掉。于是手动调用：
this.$refs.wxcCity.onlyShowList = true
问题顺利解决。
然而onlyShowList是个data属性，为什么不暴露给用户呢？
查看源码，发现onlyShowList是用在搜索时屏蔽上方的字母导航的，一旦输入框非空，就设置为true；一旦输入框为空，则改回false。
也就是说，我上面的改动还是不完美：一旦搜索一次并删空搜索框，上方的字母导航就又回来了o(╯□╰)o
当然可以通过wxcCityOnInput来处理这个问题……然而好麻烦的说。总之是希望能提供更灵活更强大的配置吧。
项目组辛苦啦。

**Comment by tw93** [comment]
下个版本加上~
