### ISSUE TITLE
wxc-tab-page左右滑动问题

### ISSUE THREAD

**Issue by ww33331000** [alibaba/weex-ui#296]
我发现使用wxc-tab-page控件的时候在安卓端和ios端的demo中都可以实现左右滑动手势来带动tab的切换，但是在web端的demo中没有此效果。请问是否有办法解决这个问题么？因为我当下需要在微信内置浏览器上开发，就需要在web端展现这个效果。但是现在不知道如何处理。。。求各位大牛相助啊。！！！
 -

**Comment by tw93** [comment]
在微信内置开发，建议使用vue相关的组件，weex的web版本只是用于降级版本，关于Web端的降级问题，可以参考下wxc-ep-slider的源码
