### ISSUE TITLE
weex preview 运行报 Uncaught SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by jamesmaxwell** [alibaba/weex-ui#3]
首先恭喜weex终于有了官方的ui库，祝weex越来越好。

我迫不及待地试用了下，当我用以下命令测试的时候发现报了标题中的错。
```
weex src/index.vue
```
另外执行
```
weex run android
```
模拟器上打开后也是一直 loading 状态。

我当前的项目使用 weex-toolkit 脚手框工具生成，版本为：v1.0.9
测试页面很简单，就使用了 wxcButton
```
<template>
  <div class="wrapper">
    <wxc-button text="登录" type="normal" @wxcButtonClicked="onSubmit"></wxc-button>
  </div>  
</template>

<script>
var modal = weex.requireModule('modal')
import { wxcButton } from 'weex-ui'

export default {
  components: {
    wxcButton
  },
  data () {
    return {}
  },
  methods: {
    onSubmit () {
        modal.toast({message: 'login'})
    }
  }
}
</script>

<style>
.wrapper {
  display: flex;
  flex-direction: columns;
  align-items: center;
  justify-content: center;
}
</style>
```

看了下报错的地方，是因为 weex-ui 使用了如下的导出方式：
```
export { default } from './index.vue';
```

了解到可能的原因是 weex preview build 不支持 export 这种es6的方式。不知有没有比较好的处理方法？

**Comment by tw93** [comment]
在native环境使用
import { wxcButton } from 'weex-ui/build/index.native.js' 
在web下环境使用
import { wxcButton } from 'weex-ui/build/index.web.js'

关于 weex-toolkit 还不支持ES6方式，后续我这边推动官方解决哦
谢谢反馈

**Comment by tw93** [comment]
已经更新 readme 文档 ，方式后面用户使用出现这个问题

**Comment by jamesmaxwell** [comment]
@tw93 感谢你的及时回复。

测试了你的方法，似乎并不能解决在 weex preview 里报 **Uncaught SyntaxError: Unexpected token export** 的问题。如你之前所说如果 weex-toolkit 不支持es6的话，只有改 weex-toolkit 才能解决了。不过 weex preview 不能用关系倒也不大，用 **npm run dev & npm run serve** 的方式是可以跑起来的。可惜的是在 android 模拟器里也跑不起来就比较郁闷了。

我现在用你之前提供的如下方法是可以的：
```
import { WxcButton } from 'weex-ui/build/index.web.js'
或
import { WxcButton } from 'weex-ui/build/index.native.js'
```
因为 build 下的 index.web.js 已经是 es5 的了。

**Comment by tw93** [comment]
已经联系weex-toolkit开发的同学升级对应工具，谢谢反馈

**Comment by goodmanman** [comment]
我也遇到了，还是不行阿，放到模拟器不好使，怎么办阿！！！
