### ISSUE TITLE
您好 有没安卓手机apk的demo  可以安装的那种 想看看效果可以吗 没有找到

### ISSUE THREAD

**Issue by Createwj** [alibaba/weex-ui#300]
Hello, there is no android phone apk demo that can be installed. I want to see the effect
您好 有没安卓手机apk的demo  可以安装的那种 想看看效果可以吗 没有找到

**Comment by tw93** [comment]
直接用手淘 或者 飞猪、天猫 扫码 都可以的  同时假如想弄android 的apk 直接使用playground 自己修改下 url 就好
目前weex ui 没有提供自己的展示app，直接二维码更便于使用
