### ISSUE TITLE
在使用 weex-UI 的时候  在 wxc-slider-bar 这个组件滑动的时候怎么获取它滑动的值

### ISSUE THREAD

**Issue by Harvey-dawn** [alibaba/weex-ui#301]
开发的环境是weex，在项目中用到了weex-UI的 <wxc-slider-bar/>这个组件，但是在后面进行滑动的时候，没有回调的事件可以获取，这个组件滑动的值，有没有什么可以解决的方法呀。

**Comment by c1394393468** [comment]
@updateValue="updateValue"

**Comment by tw93** [comment]
文档已经更新，谢谢反馈
