### ISSUE TITLE
example中button使用中的困惑

### ISSUE THREAD

**Issue by shengrl2007** [alibaba/weex-ui#302]
weex-ui/example/button/index.vue中的 import { WxcButton, WxcCell } from '../../index'，
index指的是什么？相应的路径中没有发现相关的内容，导致编译的时候出错

**Comment by tw93** [comment]
'../../index' 对于开发者 就是 'weex-ui'
这里只是为了更好的demo 使用版本的组件，而不是npm后的，为了调试而已
