### ISSUE TITLE
BindingX到底咋引用？

### ISSUE THREAD

**Issue by kouchao** [alibaba/weex-ui#303]
BindingX是被放弃了还是不兼容了？按照文档来引用报错。

**Comment by tw93** [comment]
贴一下详细的报错，建议直接去  <https://github.com/alibaba/bindingx/issues/new>这里提issue即可，或者直接去钉钉群问开发者

**Comment by ansu2009** [comment]
Manifest merger failed : uses-sdk:minSdkVersion 15 cannot be smaller than version 16 declared in library [com.alibaba.android:bindingx-core:1.0.1] C:\Users\pqdaky\.gradle\caches\transforms-1\files-1.1\bindingx-core-1.0.1.aar\21019d8c992c3d02b31e63346f87c16b\AndroidManifest.xml as the library might be using APIs not available in 15
	Suggestion: use a compatible library with a minSdk of at most 15,
		or increase this project's minSdk version to at least 16,
		or use tools:overrideLibrary="com.alibaba.android.bindingx.core" to force usage (may lead to runtime failures)
