### ISSUE TITLE
WxcPanItem 这个组件怎么没有文档

### ISSUE THREAD

**Issue by shangxinbo** [alibaba/weex-ui#307]
在wxc-tab-page里用了WxcPanItem这个组件，但是只是略带而过，为什么没有这个组件的使用文档，这个组件是做什么用的？

**Comment by fishlovestoeatcat** [comment]
这个组件里面包一个垂直的list滑动没效果，不会切换，日志如下：
`D/ExpressionBinding: binding not enabled,try auto enable it.[sourceRef:315,eventType:pan]
D/ExpressionBinding: [ExpressionTouchHandler] onCreate success. {source:315,type:pan}
    enableBinding success.[token:315,type:pan]
    all expression are cleared
D/ExpressionBinding: createBinding success.[exitExp:null,args:[{"element":"309","expression":{"origin":"x-0","transformed":"{\"type\":\"-\",\"children\":[{\"type\":\"Identifier\",\"value\":\"x\"},{\"type\":\"NumericLiteral\",\"value\":0}]}"},"property":"transform.translateX"}]]`

**Comment by tw93** [comment]
有的，因为他主要是tab-page和ep-slider中使用的子组件，详细可见
https://alibaba.github.io/weex-ui/#/cn/packages/wxc-tab-page/?id=wxc-pan-item-%E7%9A%84%E4%BD%BF%E7%94%A8

**Comment by tw93** [comment]
@fishlovestoeatcat  不支持相同方向的嵌套

**Comment by tw93** [comment]
不要这么使用，这样是错误的
你应该是在.content 这个节点使用
详细可以看 tab-page的demo 代码

**Comment by fishlovestoeatcat** [comment]
@tw93 我知道，但是没内容的时候滑不动呀，只能在cell里面用的话，我想要在整个list上可以滑动

**Comment by foyel** [comment]
@tw93 用WxcPanItem的话，页面没内容或者不够一屏的话会滑动不了
