### ISSUE TITLE
tab-bar ios 模拟器问题

### ISSUE THREAD

**Issue by chenyihao2621023** [alibaba/weex-ui#311]
##### 1.Your development environment（weex、weex-toolkit、system and more).    
 -  weex  v1.3.8
 - weexpack : v1.2.5
- weex-builder : v0.4.0
- weex-previewer : v1.5.1
 -  ios
##### 2.Expected behavior and actual behavior.   
 - 运行官网tab-bar demo 用`Weex playground app`扫码调试，正常显示
![2018-08-07 7 35 00](https://user-images.githubusercontent.com/21965525/43813155-44409d9e-9a79-11e8-8bf6-4f0e5b36b563.png)

 - 在mac模拟器下感觉高度没有计算正确，下部会被遮挡一部分
![2018-08-07 7 35 12](https://user-images.githubusercontent.com/21965525/43813200-73aa4896-9a79-11e8-9b0c-9e24c3598d09.png)

##### 3.Steps to reproduce the problem.    
计算高度相关的js
```js
created () {
      const tabPageHeight = Utils.env.getPageHeight();
      // 如果页面没有导航栏，可以用下面这个计算高度的方法
      // const tabPageHeight = env.deviceHeight / env.deviceWidth * 750;
      const { tabStyles } = this;
      this.contentStyle = { height: (tabPageHeight - tabStyles.height ) + 'px' };
    },
```
`config.js`用的是官网中的[https://github.com/alibaba/weex-ui/blob/master/example/tab-bar/config.js](url)

**Comment by tw93** [comment]
// 如果页面没有导航栏，可以用下面这个计算高度的方法
      // const tabPageHeight = env.deviceHeight / env.deviceWidth * 750;
