### ISSUE TITLE
problem appears when mask(popup) is combined with  tab-bar (当tab-bar和mask混合使用时，产生问题。)

### ISSUE THREAD

**Issue by lizihanglove** [alibaba/weex-ui#312]
##### 1.My development environment  (我的开发环境)
 - Win :10;
 - Node : v 8.11.1
 - NPM :6.0.0
 - weex: v1.3.8
 - weexpack : v1.2.3
 - weex-debugger : v1.0.15
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1

##### 2.Expected behavior and actual behavior.   (预期行为和实际行为)
 - there is a page contains wxc-tab-bar component, and the component contains four tabs along with four different pages. I expect that there is a wxc-mask component showing on the top of the phone screen when I clicked some elements in the third page. But there is nothing showing on screen. What surprised me most is that the wxc-mask showed on the first page when I changed the tab to the first. 

我在主页创建了一个含有四个tab 的wxc-tab-bar ,里面有四个页面，我在第三个tab中显示一个wxc-mask的时候，发现第三个界面没有显示出来，而我切换到第一个界面的时候，mask展示在第一个界面中了。
 

##### 3.Steps to reproduce the problem. （重现问题）
 -   同二

**Comment by tw93** [comment]
由于tabar的定位为绝对导致，此处建议wxc-mask和wxc-tab-bar 放到一个层级处理
