### ISSUE TITLE
在weex devtool模式下总是报错Uncaught Error: Uncaught SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by fanlvwen** [alibaba/weex-ui#313]
weex-ui，在debug模式下，也就是安卓结合devtool调试的时候，总是报错：
Runtime.js:289 Uncaught Error: Uncaught SyntaxError: Unexpected token export
    at Object.<anonymous> (Runtime.js:289)
    at EventEmitter.js:49
    at Array.forEach (<anonymous>)
    at EventEmitter._emit (EventEmitter.js:48)
    at EventEmitter.emit (EventEmitter.js:61)
    at onmessage (Runtime.js:96)
，但是如果把js打包，放入原生项目则正常使用

**Comment by fanlvwen** [comment]
常见问题中有这一条：
Uncaught SyntaxError: Unexpected token export；
此错误一般出现在使用老的 weex-toolkit 工具开发的页面。
可以参考此文档进行相关依赖升级。

但是我的weex-toolkit已经升级到最新版 v1.3.8，仍然是这个报错。

**Comment by tw93** [comment]
按照这个步骤检查下~
https://alibaba.github.io/weex-ui/#/cn/with-weex-toolkit

**Comment by fanlvwen** [comment]
不起作用，已经按照文档说明升级weex-toolkit到最新版本，build放入原生项目去本地加载没问题，就是chrome调试devtool的时候报错

**Comment by tw93** [comment]
历史已有问题  参考这个 https://github.com/alibaba/weex-ui/issues/30#issuecomment-338462631

需要修改下  babel exclude 配置内容。

![](https://gw.alicdn.com/tfs/TB1hETgwbZnBKNjSZFrXXaRLFXa-1418-904.png)
