### ISSUE TITLE
list列表里里有几十、几百条数据的时候，点击cell触发mask、dialog等各种弹出层的时候响应就很慢

### ISSUE THREAD

**Issue by cyabc** [alibaba/weex-ui#314]
##### 1.Your development environment（weex、weex-toolkit、system and more).    
 - weex v1.3.8
 - weex-toolkit  @last

##### 2.Expected behavior and actual behavior.   
 - list列表里里有几百条数据的时候，weex ui的弹框类型的组件都在点击触发之后响应很慢，有什么方法解决
  

##### 3.Steps to reproduce the problem.    
 - list列表里里有几十、几百条数据的时候，点击cell触发mask、dialog等各种弹出层的时候响应就很慢了
 - 是list数据多，非弹出层内容。
-只要有mask等相关Weex-ui组件，click事件触发的其他下一步操作就很慢

**Comment by tw93** [comment]
先做list上面的优化，尽可能 cell 比较 薄，层级不要那么深
这样mask弹出效果会好一点儿哦

**Comment by liyuan900226** [comment]
可以使用recycle list  内置模块，回收内存
