### ISSUE TITLE
ios9兼容问题

### ISSUE THREAD

**Issue by baiyujie** [alibaba/weex-ui#315]
##### ios9兼容问题   
 - weex-ui 在使用过程中，ios9测试被遗忘掉，自版本到5.x以来，打包后，ios9无法识别打包后的native.js会出现一些错误，如下

···

<Weex>[error]WXMonitor.m:251, Error Domain=WXErrorDomain Code=-2013 "[WX_KEY_EXCEPTION_WXBRIDGE] [native-bundle-main.js:5872:40919] SyntaxError: Unexpected token '>'
Function@[native code]
Function@[native code]
native-bundle-main.js:1:40919
createInstance@native-bundle-main.js:1:40937
native-bundle-main.js:1:255299" UserInfo={NSLocalizedDescription=[WX_KEY_EXCEPTION_WXBRIDGE] [native-bundle-main.js:5872:40919] SyntaxError: Unexpected token '>'
Function@[native code]
Function@[native code]
native-bundle-main.js:1:40919
createInstance@native-bundle-main.js:1:40937
native-bundle-main.js:1:255299}

···

**Comment by baiyujie** [comment]
找到问题是weex-bindingx引起，不知为什么

**Comment by tw93** [comment]
请bindingx的钉钉群：11790400 进行咨询就好
