### ISSUE TITLE
wxc-grid-select控件怎么用数据里自带的name作为title

### ISSUE THREAD

**Issue by zkj881225** [alibaba/weex-ui#317]
比如数据是这样的：
{
        "id": 11111,
        "name": "海福调度1",
        "phone": "18950295115"
      },
      {
        "id": 11112,
        "name": "海福调度2",
        "phone": "18950295115"
      }
，显示的时候怎么将name作为title显示？
官方demo:里面是这样的数据：
 testData1: [
        {
          'title': '上海'
        },
        {
          'title': '杭州',
          'checked': true
        }]，
文档里有个：
list[{title}] | String |  标题
，这里不知道怎么用

**Comment by tw93** [comment]
通过js转换一下数据，将需要显示的item项通过title字段传入即可，也就是这里的title 应该是对应的你的 name+phone
