### ISSUE TITLE
ep-slider真机卡顿

### ISSUE THREAD

**Issue by jues** [alibaba/weex-ui#318]
需求是进app前展示4张向导图片，w1500h2668的png图片会因内存不足而崩溃（每张在800k左右）
w750h1334的图片可以滑动但是有明显卡顿，请问这是否正常？

"weex-ui": "^0.6.5",

implementation 'com.alibaba.android:bindingx-core:1.0.1'
implementation 'com.alibaba.android:bindingx_weex_plugin:1.0.1'

**Comment by tw93** [comment]
可以用飞猪或者手淘测试下看是否卡顿，假如不卡，应该是bindingx接入有问题
假如也卡的话，建议首先对图片大小进行优化，太大图片导致内存不足，图片尺寸控制带100K以内
否决建议直接使用slider
