### ISSUE TITLE
引入weex-ui组件，执行weex debug访问不了页面？

### ISSUE THREAD

**Issue by chzjstar** [alibaba/weex-ui#32]
在页面中引入weex-ui组件，weex debug调试时发现页面空白，但是去掉weex-ui组件就可以正常显示；我把weex-ui的组件（比如weex-ui/packages/wxc-button文件夹）放入自己项目中，然后在页面中引入，调试就可以正常显示。

**Comment by tw93** [comment]
Please be more detailed，I can do it with weex debug but have some error，and @erha19 help look it :)
![image](https://user-images.githubusercontent.com/8736212/31850495-488d78a4-b618-11e7-93d8-24dd060fe3dc.png)

**Comment by tw93** [comment]
Please follow the same issule here #30
