### ISSUE TITLE
使用wxc-tab-page 出现 undefinedpx

### ISSUE THREAD

**Issue by hiXing** [alibaba/weex-ui#320]
##### 1.Your development environment（weex、weex-toolkit、system and more).    
 - weex 0.18.0
 -  weex-ui 0.6.5
 - 

![image](https://user-images.githubusercontent.com/9985104/44794778-c8cf0c80-abdb-11e8-99fe-aafa01850f25.png)

![image](https://user-images.githubusercontent.com/9985104/44794809-dab0af80-abdb-11e8-89da-50935061d236.png)

![image](https://user-images.githubusercontent.com/9985104/44794423-1303be00-abdb-11e8-8440-d129f8e30792.png)

**Comment by tw93** [comment]
已经修复，谢谢反馈，请升级到最新版本0.6.6
