### ISSUE TITLE
wxc-tab-bar 组件，设备上显示问题.

### ISSUE THREAD

**Issue by keyus** [alibaba/weex-ui#321]
h5是正常的.

我把demo代码，跑起来，放到weexplayground上，以及在iphone5se ，6,上实测，结果无法显示底部文字。只能显示到图标。
测试机iphone5s,   iphone6;

contentStyle height并没有获得 正确的高度.

package.json

`"dependencies": {
    "phantom-limb": "0.0.1",
    "vue": "^2.5.11",
    "vue-router": "^3.0.1",
    "weex-vue-render": "^1.0.17",
    "weex-ui": "^0.6.5"
  },`

`<style scoped>
    .item-container {
        width: 750px;
        background-color: #f2f3f4;
        align-items: center;
        justify-content: center;
    }
</style>`

`<template>
    <wxc-tab-bar :tab-titles="tabTitles"
                 :tab-styles="tabStyles"
                 title-type="icon"
                 @wxcTabBarCurrentTabSelected="wxcTabBarCurrentTabSelected">
        
        <div class="item-container" :style="contentStyle"><text>首页</text></div>

        
        <div class="item-container" :style="contentStyle"><text>特别推荐</text></div>

        
        <div class="item-container" :style="contentStyle"><text>消息中心</text></div>

        
        <div class="item-container" :style="contentStyle"><text>我的主页</text></div>
    </wxc-tab-bar>
</template>

<script>
    import { WxcTabBar, Utils } from 'weex-ui';
    import Config from './config'
    export default {
        components: { WxcTabBar },
        data: () => ({
            tabTitles: Config.tabTitles,
            tabStyles: Config.tabStyles
        }),
        created () {
            const tabPageHeight = Utils.env.getPageHeight();
            const { tabStyles } = this;
            this.contentStyle = { height: (tabPageHeight - tabStyles.height) + 'px' };
        },
        methods: {
            wxcTabBarCurrentTabSelected (e) {
                const index = e.page;
            }
        }
    };
</script>
`

<img width="474" alt="2018-08-31 5 50 32" src="https://user-images.githubusercontent.com/22314310/44906171-bb826100-ad46-11e8-9c04-30e96dabe11a.png">

**Comment by tw93** [comment]
![](https://gw.alicdn.com/tfs/TB12G7wu.OWBKNjSZKzXXXfWFXa-1900-764.png)
可以看文档说明

**Comment by pengxingwang** [comment]
@keyus @tw93  解决了吗，我按照没有导航栏的写
` const tabPageHeight = weex.config.env.deviceHeight / weex.config.env.deviceWidth * 750;`
还是存在这个问题的
