### ISSUE TITLE
WxcPopover chrome浏览器预览报错，手机端正常

### ISSUE THREAD

**Issue by ximelly** [alibaba/weex-ui#327]
vue.runtime.esm.js?ff9b:587 [Vue warn]: Error in render: "TypeError: Cannot read property 'lines' of undefined"

**Comment by tw93** [comment]
暂时可以不关注，这个lines是weex本身的一个属性，这里是降级版本的一个warn 更新weex-vue-loader到最新试试

**Comment by tw93** [comment]
![image](https://user-images.githubusercontent.com/8736212/54105172-3cfd2f00-440d-11e9-81a1-d3f426ce2e6c.png)
是这里引起来的，已经提交代码，晚上发布版本 0.6.10版本
