### ISSUE TITLE
WxcCell 打包错误  ERROR in XXX from UglifyJs Unexpected token: punc (()  [XXX]

### ISSUE THREAD

**Issue by wazsq** [alibaba/weex-ui#33]
本来想用下WxcCell这个组件的，发现只要注册过WxcCell的组件打包就过不了

> ERROR in goods-edit.js from UglifyJs
    Unexpected token: punc (() [goods-edit.js:1574,17]

.babelrc里已经按照文档里写了

> {
  "presets": ["stage-3","es2015"],
  "plugins": [
    "transform-es2015-modules-commonjs",
    "transform-export-extensions",
    [
      "component",
      {
        "libraryName": "weex-ui",
        "libDir": "packages"
      }
    ],
    [
      "transform-runtime",
      {
        "helpers": false,
        "polyfill": false
      }
    ]
  ]
}

其他组件倒是没有发现这个问题

**Comment by tw93** [comment]
update weex-ui  and weex-toolkit to latest , and add a babel exclude to  weex.config.js ,like this. try it.

```
exclude: /node_modules(?!\/.*(weex).*)/
```
in:
{
        test: /\.js$/,
        use: [{
          loader: 'babel-loader'
        }],
        exclude: /node_modules(?!\/.*(weex).*)/
      },

**Comment by tw93** [comment]
https://github.com/alibaba/weex-ui/issues/30
