### ISSUE TITLE
wxc-slider-bar 拖动滑块后禁用仍然可以拖动滑块

### ISSUE THREAD

**Issue by Yang90** [alibaba/weex-ui#331]
weex Android使用了wxc-slider-bar,当拖动过滑块之后将disabled设置为true,仍然可以拖动滑块;
看起来好像是Binding.bind调用之后并没有在disabled为true时调用Binding.unbind

**Comment by tw93** [comment]
谢谢反馈，已经加上，下次这类的可以直接提PR给我们~
