### ISSUE TITLE
顶部标签页和底部标签页wxc-tab-bar wxc-tab-page可以实现懒加载么 如何实现呢？

### ISSUE THREAD

**Issue by herodongliang** [alibaba/weex-ui#334]

**Comment by tw93** [comment]
可以的，相当于这样的思路，默认只加载首次进来的那个页面，其他页面先用一个空白的div代替，等到切换过去时候，有一个事件，这样再加载那个页面数据来更新视图就好。

**Comment by herodongliang** [comment]
非常感谢！

在 2018-10-26 21:12:03，"Tw93" <notifications@github.com> 写道：


可以的，相当于这样的思路，默认只加载首次进来的那个页面，其他页面先用一个空白的div代替，等到切换过去时候，有一个事件，这样再加载那个页面数据来更新视图就好。
