### ISSUE TITLE
wxc-icon显示失效

### ISSUE THREAD

**Issue by smile9211** [alibaba/weex-ui#336]
1.小米note4
2.根据文档填写了icon的name，结果在真机上不显示
<wxc-icon name="back" size='small' ></wxc-icon>
![20181007234441](https://user-images.githubusercontent.com/20120527/46583563-cfc72580-ca8b-11e8-8eca-4fefa5bba41f.jpg)

**Comment by tw93** [comment]
提供一下weex的详细版本和具体demo

**Comment by tw93** [comment]
手上小米正常展示，暂无更多信息排查，暂时关闭
