### ISSUE TITLE
How to change `wxc-radio` value by code in iPhone simulator?

### ISSUE THREAD

**Issue by shinriyo** [alibaba/weex-ui#339]
##### 1.Your development environment（weex、weex-toolkit、system and more).    
 - `weex --version`   v1.3.11
 - weex-ui 0.6.6

##### 2.Expected behavior and actual behavior.   
 - like this.

<img width="372" alt="screen shot 2018-10-14 at 17 41 09" src="https://user-images.githubusercontent.com/396927/46914433-7bb2c880-cfd8-11e8-8a8e-a470b6e5f292.png">

##### 3.Steps to reproduce the problem.    
 - 
```
import { WxcRadio, WxcButton } from 'weex-ui';
```

it is `list`
```
      list: [
        // { title: 'thousand', value: 1, checked: true },
        { title: 'thousand', value: 1 },
        { title: 'million', value: 2 },
        { title: 'billion', value: 3 },
        { title: 'trillion', value: 4 },
      ],
```

my pug code.
```
wxc-radio(:list='list', @wxcRadioListChecked='wxcRadioListChecked')
```

I changed dynamically check.
It works fine in web version.

```
this.list[Number(event.data) - 1].checked = true;
```

it is web version which start by `yarn start`.
<img width="314" alt="screen shot 2018-10-14 at 17 40 18" src="https://user-images.githubusercontent.com/396927/46914417-3d1d0e00-cfd8-11e8-8f51-e6ea9ae12422.png">

however... iPhone simulator didn't!
it invisible "check". background it is checked.

<img width="538" alt="screen shot 2018-10-14 at 17 43 34" src="https://user-images.githubusercontent.com/396927/46914447-b583cf00-cfd8-11e8-9eb3-4763175fbd1f.png">

How to show check or redraw?

**Comment by tw93** [comment]
This modification does not trigger the update logic of the underlying Vue.
You can try this by this https://vuejs.org/v2/api/#Vue-set

```vue
Vue.set(this.list, 0, { title: '选项1', value: 1,checked: true});
Vue.set(this.list, 1, { title: '选项2', value: 1,checked: false});
```
