### ISSUE TITLE
Uncaught SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by wdh-1025** [alibaba/weex-ui#34]
不清楚什么原因，引入后使用组件报了Uncaught SyntaxError: Unexpected token export
  module: {
    rules: [{
      test: /\.vue$/
    }, {
      test: /\.js$/,
      use: [{
        loader: 'babel-loader'
      }],
      exclude: /node_modules(?!\/.*(weex).*)/
    }]
  }
----------------------------------------------------------
{
  "presets": ["es2015", "stage-0"],
  "plugins": [
    [
      "component",
      {
        "libraryName": "weex-ui",
        "libDir": "packages"
      }
    ]
  ]
}

**Comment by tw93** [comment]
https://github.com/alibaba/weex-ui/issues/30#issuecomment-338462631
