### ISSUE TITLE
can wxc-indexlist  config scroll speed or disable animation ? when data is large , click index 'z' will scroll to button so long...

### ISSUE THREAD

**Issue by awuliu** [alibaba/weex-ui#341]

**Comment by tw93** [comment]
Thank you for feedback. I will provide a param.

**Comment by tw93** [comment]
I added a new need-animation to solve your problem. You can ban animation when you introduce false.
More you can see here.  https://alibaba.github.io/weex-ui/#/packages/wxc-indexlist/
