### ISSUE TITLE
关于组件样式覆盖，有没有办法？

### ISSUE THREAD

**Issue by shawon1220** [alibaba/weex-ui#342]
如WxcButton 需要修改圆角，用新的class无法覆盖border-radius属性，只能用内联样式 style="border-radius"，不知有没有方案实现。

**Comment by tw93** [comment]
有的，有一个暴露参数叫做 btnStyle ，可以看看文档https://alibaba.github.io/weex-ui/#/cn/packages/wxc-button/
![image](https://user-images.githubusercontent.com/8736212/47567567-7c951400-d961-11e8-8e03-cb3aa6f8782c.png)
