### ISSUE TITLE
wxc-tab-page wxc-tab-bar 可以 搭配使用吗？ 滑动切换顶部的tab，底部点击切换（禁用底部的滑动）

### ISSUE THREAD

**Issue by noman798** [alibaba/weex-ui#345]
wxc-tab-page wxc-tab-bar 可以 搭配使用吗？ 滑动切换顶部的tab，底部点击切换（禁用底部的滑动）
我看tab-page有need-slider参数，但是底部的tab-bar没有need-slider参数
但是我的需求貌似是跟现有的接口反过来的的，我需要底部tab-bar关闭need-slider

**Comment by rccoder** [comment]
@noman798  底部 Tab 切换建议试试 `<embed />` 标签，可控性更高一些

https://github.com/apache/incubator-weex/blob/master/examples/vue/include/tabbar.vue#L3

**Comment by tw93** [comment]
不建议搭配使用，推荐@rccoder  建议

**Comment by noman798** [comment]
@rccoder embed哪儿有文档吗？我搜索了weex的文档和weex ui的文档，都找到
