### ISSUE TITLE
在model 模式下 右侧地区索引无效

### ISSUE THREAD

**Issue by metooweb** [alibaba/weex-ui#349]
##### 1.Your development environment（weex、weex-toolkit、system and more).    
 - wxc-city
 - 

##### 2.Expected behavior and actual behavior.   
 -  在model 模式下 右侧地区索引无效
 - 

##### 3.Steps to reproduce the problem.    
 - 在model 模式下
 -

**Comment by tw93** [comment]
我这边用iOS 和Android都测试了下demo都是好的，看一下是否是没有设置高度高度呢

**Comment by tw93** [comment]
暂无回复，先关闭，有详细错误再打开就好
