### ISSUE TITLE
希望增加滚动加载，下拉刷新，瀑布流等

### ISSUE THREAD

**Issue by J3DFox** [alibaba/weex-ui#35]
希望增加以下组件
上拉加载
下拉刷新
瀑布流(滚动加载)
购物车业务组件
SKU业务组件（类似vantui）

**Comment by tw93** [comment]
上拉加载和下拉刷新 目前对于的list 中的refresh、loading, 你可以参考这儿http://weex-project.io/cn/references/components/list.html#子组件

关于瀑布流后续有计划开源
购物车业务组件目前应该没有类似场景，欢迎pr~

**Comment by webthen** [comment]
貌似不更新了
自己要写一个。
