### ISSUE TITLE
wxc-tab-bar高度计算问题

### ISSUE THREAD

**Issue by TingYuLC** [alibaba/weex-ui#351]
在h5表现是正常的
但在android的高度明显短了
![image](https://user-images.githubusercontent.com/13540973/47984376-69c4d100-e111-11e8-8f83-d6101b01311d.png)
![image](https://user-images.githubusercontent.com/13540973/47984405-7ea16480-e111-11e8-9791-7075781bfd42.png)
如果按照说明改下代码，高度又明显长了。。。（文字被下方tab挡住了）
![image](https://user-images.githubusercontent.com/13540973/47984428-924ccb00-e111-11e8-82b7-66f320e6436d.png)
![image](https://user-images.githubusercontent.com/13540973/47984436-97aa1580-e111-11e8-812c-060b66247a31.png)

**Comment by pengxingwang** [comment]
下面文字不见了
