### ISSUE TITLE
同时使用WxcIcon和自己的iconfont时，不能同时显示

### ISSUE THREAD

**Issue by LionBuer** [alibaba/weex-ui#352]
Try to search for your [issue](https://github.com/alibaba/weex-ui/issues?utf8=%E2%9C%93&q=), it may have already been answered or even fixed in the development branch. 
 
 在开 issue 前，可以先搜索以下以往的旧 [issue](https://github.com/alibaba/weex-ui/issues?utf8=%E2%9C%93&q=)，你遇到的问题可能已经有人提了，也可能已经在最新版本中被修正。

开源项目的用户和维护者之间并不是甲方和乙方的关系，issue 也不是客服。
在开 issue 的时候，请抱着一种『一起合作来解决这个问题』的心态，同时请尽可能描述清楚，这样效率才会高。

Remember to delete the above statement before committing.
同时建议使用英语进行描述，这样国外的开发者也可以看懂，提交之前，**记得将上述说明删除!!**。

##### 1.Your development environment（weex、weex-toolkit、system and more).    

$ weex -v
   v1.3.8
 - weexpack : v1.2.5
 - weex-debugger : v1.1.4
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1

##### 2.Expected behavior and actual behavior.   

我在页面中使用了iconfont，结果是可以正常显示出来的。
然而当我想同时使用wxc-icon的时候，我发现wxc-icon怎么也显示不出来。

当我把自己代码中的
 beforeCreate: function () {
            //目前支持ttf、woff文件，不支持svg、eot类型,moreItem at http://www.iconfont.cn/
            weex.requireModule('dom').addRule('fontFace', {
                'fontFamily': "iconfont",
                'src': "url('http://at.alicdn.com/t/font_78331_tmx8p628gmj.ttf')"
            });
        }
注释掉，wxc-icon就能正常显示。

希望能让两者iconfont都能显示

##### 3.Steps to reproduce the problem.    
 - 
 -

**Comment by tw93** [comment]
在Android上面的确会有这个问题，ios和H5是好的，建议暂时用图片来代替解决，同时给weex报一个bug
https://weex-project.io/cn/bug-report-guidelines.html
