### ISSUE TITLE
button被禁用后，click事件依然被触发

### ISSUE THREAD

**Issue by WentaoHou** [alibaba/weex-ui#353]
![image](https://user-images.githubusercontent.com/37180194/48285114-8019b680-e49c-11e8-8b4b-e5e2ed2aae9a.png)

**Comment by tw93** [comment]
是的，在这里的disabled更多是一个属性，点击时候会有一个回调，你需要根据 `this.$emit('wxcButtonClicked', { e, type, disabled });` 回调的值判断下 data.disabled 即可，自行处理，假如是true，就直接return掉就好
