### ISSUE TITLE
我想在vue项目中使用weex-ui

### ISSUE THREAD

**Issue by nqdy666** [alibaba/weex-ui#354]
##### 1.Your development environment（weex、weex-toolkit、system and more).    
 - weex
 - vue

##### 2.Expected behavior and actual behavior.   
- 我想在vue项目中使用weex-ui，我该如何操作。非常感谢。

##### 3.Steps to reproduce the problem.    
- 我通过vue init生成一个常规的项目，希望实现组件可视化编辑
- 我的项目已经引入了element-ui，现在也希望引入week-ui
- 但是直接引入week-ui无法运行，会报“weex”变量找不到，
- 在webpack配置引入了weex-loader，会报无法找不到render或者template

**Comment by SamZSL** [comment]
1、安装weex-ui

npm install weex-ui -S
2、如果使用weex-toolkit来开发Weex项目并不打包所有组件，安装依赖插件 'state-0' 和 'babel-plugin-component'

npm i babel-preset-stage-0 babel-plugin-component -D
3、修改.babelrc文件

{
    "presets": ["es2015", "stage-0"],
    "plugins": [
        [
            "component",
            {
                "libraryName": "weex-ui",
                "libDir": "packages",
                "style": false
            }
        ]
    ]
}

**Comment by tw93** [comment]
不建议纯vue项目使用 weex-ui，weex-ui 更时候以weex 为主，同时需要降级H5的场景
