### ISSUE TITLE
通过外部按钮置空checkList

### ISSUE THREAD

**Issue by EnTrouble** [alibaba/weex-ui#359]
- weex
 在页面里引入了checkList组件
<wxc-checkbox-list
      :list="brandList"
      :config="typeConfig"
      theme="search-item"
      :valueStyle="{marginRight:'20px'}"
      valuePosition="left"
      ref='clearAll'
      @wxcCheckBoxListChecked="wxcCheckBoxListChecked"
 ></wxc-checkbox-list>

<div class="btn">
      <wxc-button
        text="重置"
        type='white'
        @wxcButtonClicked="handleReset"
        :btnStyle="{'width':'375px','border-width':'0'}"
        :textStyle="{'color':'#f55d22'}"
      ></wxc-button>
      <wxc-button
        text="确认"
        @wxcButtonClicked="handleAssure"
        :btnStyle="{'width':'375px'}"
      ></wxc-button>
   </div>
想要实现可以通过点击《重置》按钮清空选择的效果，但是目前一直无法实现...
关键是：很奇怪的一点，我在当前页面是无法获取到this.$refs.clearAll的，不是undefined而是会报错，报错如下：
[Vue warn]: Property or method "toJSON" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property.

**Comment by tw93** [comment]
为什么不支持通过点击修改 brandList 的值呢？
这样会更好方便和符合代码逻辑哦
