### ISSUE TITLE
weex-ui可以打包成HTML5的发布包吗？

### ISSUE THREAD

**Issue by TonyLuo** [alibaba/weex-ui#36]
weex-ui可以打包成HTML5的发布包吗？跑哪个命令可以直接生成html的发布包？
weex号称可以三端统一，但找了好久,只看到用浏览器调试页面的文档，看不到可以打包成html5发布包的相关文档......

**Comment by rccoder** [comment]
@TonyLuo 

https://weex.incubator.apache.org/cn/guide/set-up-env.html#第三步：开发

用 `weex-toolkit` 话能自动生成一套简易环境。

`npm run build` 之后会在 `dist` 文件夹下打出用于 web 降级的 `app.web.js`，根目录下有 `weex.html` 引用了 `app.web.js`。`weex.html` 就是入口

**Comment by TonyLuo** [comment]
谢谢回复。像vue本身提供的模板里在build的时候会把所有的相关资源打包到dist里，直接把dist拷到服务器用就行了，weex-toolkit生成dist后还要自己去挑选文件才能发布...
