### ISSUE TITLE
提个需求，做个weex表格组件

### ISSUE THREAD

**Issue by kang558** [alibaba/weex-ui#360]
- 很喜欢这个组件库，很多实用的组件。

## 正题：
表格在APP中也是经常使用的，找了很多个weex组件库发现都没有表格组件。功能强大的表格组件 类似[饿了么的表格组件](http://element-cn.eleme.io/#/zh-CN/component/table) 十分强大。特别是过滤、筛选、排序，表头固定、侧边表固定横向滚动等。

**Comment by tw93** [comment]
抱歉，移动端其实不太适合用表格来展示东西，这里建议换一种方式来展示，同时weex不太适合表格布局这种模式
