### ISSUE TITLE
wxc-lightbox 可以新增index选项吗？

### ISSUE THREAD

**Issue by shanghen** [alibaba/weex-ui#361]
现在的wxc-lightbox组件 无法制定初始化的时候幻灯片的索引值，希望可以加上

**Comment by http-lbw** [comment]
解决了吗,我也遇到了同样的问题

**Comment by shanghen** [comment]
@http-lbw 他的实现是用官方的slider组件完成的
要解决就要再源码上的prop上加上这个参数，传进去内部的slider组件中。因为要改动源码所以我没又去动
你可是把源码复制一份到自己的代码中重新建个组件 传入你想要的参数即可

**Comment by http-lbw** [comment]
好的,谢谢

**Comment by tw93** [comment]
我加一下，谢谢反馈

**Comment by shanghen** [comment]
@tw93 WxcSpecialRichText组件也有个奇怪的问题 tag的情况下 首行的空格再IOS的环境下空格不够。
我去看过源码后发现 你们对ios的环境下 对空格去除于2的相关代码，不知道是处于什么考虑有个这个hack

**Comment by tw93** [comment]
@shanghen 因为当时业务中有场景，然后反复测试后，这样计算的，我这边检查后更新一下哦，谢谢反馈

**Comment by tw93** [comment]
新增index和interval增强lightbox属性，稍后更新到最新即可

> npm i weex-ui@latest -S

| Prop | Type | Required | Default | Description |
|-------------|------------|--------|-----|-----|
| index | `Number` |`N`| `0` | 当前初始打开选择哪一页 |
| interval | `Number` |`N`| `3000` | 设置自动播放时候的间隔时间 |

**Comment by limbo-wayne** [comment]
index 目前只有在第一个和最后一个时生效呢
