### ISSUE TITLE
wxc-special-rich-text 在iOS端显示问题

### ISSUE THREAD

**Issue by zhongdom** [alibaba/weex-ui#362]
##### 1.Your development environment（weex、weex-toolkit、system and more).    
 - `weex` `iOS`
 - 

##### 2.Expected behavior and actual behavior.   
 - 同一套代码，安卓显示正常，iOS端超过三个文字的tag 与后面的文字重叠，小于三个文字显示正常

**Comment by tw93** [comment]
谢谢反馈，这个逻辑是当时weex版本较老时候的一个兼容hack逻辑，现在用新版测试是好的，已经去除，今天发布版本可以用上
