### ISSUE TITLE
tabbar底部条在ios显示不全的问题

### ISSUE THREAD

**Issue by lxf9601** [alibaba/weex-ui#363]
在ios虚拟机上显示的高度明显比android低，导致导航的title显示不完整

**Comment by tw93** [comment]
因为ios虚拟机的头部默认是隐藏的，需要自己设置下高度，详细可见
![image](https://user-images.githubusercontent.com/8736212/50532627-f65e9f00-0b56-11e9-9373-af61e8ce76e7.png)
