### ISSUE TITLE
wxc-page-calendar 中选中日期的颜色

### ISSUE THREAD

**Issue by guakun** [alibaba/weex-ui#365]
能否提供一个配置项使得可以配置 page-calendar 中选中日期的颜色

**Comment by tw93** [comment]
我加一下，谢谢反馈，下一个版本上

**Comment by tw93** [comment]
新增如下参数来支持，待会儿请升级最新的版本即可：

> npm i weex-ui@latest -S

| Prop | Type | Required | Default | Description |
|-------------|------------|--------|-----|-----|
| selected-cell-style | `Object` | `N` | `{}` |覆盖选中日期的 cell 样式|
| selected-text-style | `Object` | `N` | `{}` |覆盖选中日期的 text 样式|

**Comment by hilads** [comment]
> 能否提供一个配置项使得可以配置 page-calendar 中选中日期的颜色

你可以了吗?  我按照文档上加的 怎么没有效果  
![image](https://user-images.githubusercontent.com/46804595/60497992-63aae280-9ce8-11e9-87b6-28cf53bdeac1.png)

![image](https://user-images.githubusercontent.com/46804595/60497939-542b9980-9ce8-11e9-85b1-fb56b280f55a.png)

**Comment by hilads** [comment]
解决了 我的版本 太低了
