### ISSUE TITLE
环境报错

### ISSUE THREAD

**Issue by yaochenfeng** [alibaba/weex-ui#369]
##### 1.Your development environment（weex、weex-toolkit、system and more).    
 - weex    v1.3.11
 - weexpack : v1.2.7
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1
 - 

##### 2.Expected behavior and actual behavior.   
 - npm i weex-ui -S and add Demo.vue
 - Failed to compile

##### 3.Steps to reproduce the problem.    
> webpack-dev-server --env.NODE_ENV=development --progress

 95% emitting                                                                 w
 ERROR  Failed to compile with 2 errors                                 10:21:51

 error  in ./node_modules/weex-ui/packages/wxc-popup/index.vue

Module parse failed: Unexpected token (135:34)
You may need an appropriate loader to handle this file type.
|         backgroundColor: popupColor
|       };
|       pos === 'top' && (style = { ...style,
|         top: `${-height + stand}px`,
|         height: `${height}px`

 @ ./node_modules/weex-ui/packages/wxc-popup/index.vue 8:2-92
 @ ./node_modules/weex-ui/packages/wxc-popup/index.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/pages/Demo.vue
 @ ./src/pages/Demo.vue
 @ ./.temp/pages/Demo.web.js
 @ multi (webpack)-dev-server/client?http://192.168.3.19:8081 ./.temp/pages/Demo.web.js

 error  in ./node_modules/weex-ui/packages/wxc-button/index.vue

Module parse failed: Unexpected token (46:27)
You may need an appropriate loader to handle this file type.
|         disabledStyle
|       } = this;
|       const mrBtnStyle = { ...STYLE_MAP[type],
|         ...btnStyle,
|         ...BUTTON_STYLE_MAP[size]

 @ ./node_modules/weex-ui/packages/wxc-button/index.vue 8:2-92
 @ ./node_modules/weex-ui/packages/wxc-button/index.js
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/pages/Demo.vue
 @ ./src/pages/Demo.vue
 @ ./.temp/pages/Demo.web.js
 @ multi (webpack)-dev-server/client?http://192.168.3.19:8081 ./.temp/pages/Demo.web.js

**Comment by yaochenfeng** [comment]
weex create my-project
npm i weex-ui -S
add Demo.vue
`<template>
  <div>
    <wxc-button text="Open Popup"
                @wxcButtonClicked="buttonClicked">
    </wxc-button>
    <wxc-popup width="500"
               pos="left"
               :show="isShow"
               @wxcPopupOverlayClicked="overlayClicked">
    </wxc-popup>
  </div>
</template>

<script>
  import { WxcButton, WxcPopup } from 'weex-ui';
  // or
  // import WxcButton from 'weex-ui/packages/wxc-button';
  // import WxcPopup from 'weex-ui/packages/wxc-popup';
  module.exports = {
    components: { WxcButton, WxcPopup },
    data: () => ({
      isShow: false
    }),
    methods: {
      buttonClicked () {
        this.isShow = true;
      },
      overlayClicked () {
        this.isShow = false;
      }
    }
  };
</script>
`
Failed to compile

**Comment by tw93** [comment]
历史已知问题，请参考文档解决https://github.com/alibaba/weex-ui/issues/30#issuecomment-338462631

**Comment by SteinsGateHz** [comment]
babel版本问题
`npm i babel-plugin-component babel-preset-stage-0 -D`
`npm install babel-loader@7 babel-core@6 -D`
`npm uninstall @babel/core @babel/preset-env `
最后按照官方的.babelrc 配置即可
亲测有效！

**Comment by SteinsGateHz** [comment]
@yaochenfeng
