### ISSUE TITLE
wxc-ep-slider 提供的demo无法滚动

### ISSUE THREAD

**Issue by MIAPP-H5** [alibaba/weex-ui#37]
Before you start writing a issue,Please make sure [there](https://github.com/alibaba/weex-ui/issues?utf8=%E2%9C%93&q=) have not the same issue.

#### Your development environment（weex、weex-toolkit、system and more.）
- 
- 

#### Expected behavior and actual behavior.
- 
- 

#### Steps to reproduce the problem.
- 
-

**Comment by MIAPP-H5** [comment]
请提供一个正确的示例，

**Comment by marekchen** [comment]
please see this issue #6

**Comment by MIAPP-H5** [comment]
wxc-ep-slider 能够设置自定滚动吗？

**Comment by tw93** [comment]
可以的 我新加了一个版本，详细可见demo
https://github.com/alibaba/weex-ui/blob/master/example/ep-slider/index.vue
关于ep的开源可见 https://github.com/alibaba/weex-ui/issues/6
