### ISSUE TITLE
Module parse failed: Unexpected token (46:27)

### ISSUE THREAD

**Issue by liandelanniao** [alibaba/weex-ui#370]
Module parse failed: Unexpected token (46:27)
You may need an appropriate loader to handle this file type.
|         disabledStyle
|       } = this;
|       const mrBtnStyle = { ...STYLE_MAP[type],
|         ...btnStyle,
|         ...BUTTON_STYLE_MAP[size]

新版本weex-toolkit 创建的，求大神指导，好几天的都崩溃了

**Comment by liandelanniao** [comment]
> 也遇到这个问题
> 貌似节前临近下班前更新的weex？好多问题

在babel6上能跑起来，到7上就崩溃，weex-toolkit都到babel7了，不想换成6，哎弄的我头大

**Comment by 13274902239** [comment]
我也遇到这个问题

**Comment by 13274902239** [comment]
大神们，有什么处理办法吗？

**Comment by tw93** [comment]
参考一下这个，需要修改下webpack配置，因为生成的默认对node modules里面不使用es6
https://github.com/weex-ui-team/weex-ui-demo/blob/master/webpack.config.js#L110-L153

**Comment by zwblue** [comment]
问题解决了么？

**Comment by tw93** [comment]
@zwblue 见上面的回复 我的文档也更新下

**Comment by liandelanniao** [comment]
我是直接把新版weex-toolkit生成的所有关于babel7的都换成了6跑起来的，工期紧张在babel7上没有在尝试解决办法，这两天完结了试试在7上的调整
