### ISSUE TITLE
TabPage不能左右滑动切换tab

### ISSUE THREAD

**Issue by topcloud-xx** [alibaba/weex-ui#371]
使用Weex Playground扫描WeexUI二维码体验，TabPage不能左右滑动切换tab，但是使用淘宝APP扫描二维码确可以左右滑动切换tab，不知到什么原因。

**Comment by tw93** [comment]
需要接入这个sdk https://alibaba.github.io/bindingx/

**Comment by topcloud-xx** [comment]
> 需要接入这个sdk https://alibaba.github.io/bindingx/
我自己开发应用，weex-ui使用的是最新的0.6.8版本，weex使用的0.20.2版本
bindingx也接入了，使用BindEnv.supportsEBForAndroid()；BindEnv.supportsEBForIos()；验证都是true。
我跟踪Weex-ui代码，bindExp方法执行到了。在wxc-tab-page\index.vue中
程序执行至276行：
          **const tabElement = this.$refs['tab-container'];**
          const { currentPage, panDist } = this;
          const dist = currentPage * 750;
发现tabElement没有获取到。

感谢及时答复，谢谢！

**Comment by liuyfl** [comment]
我也遇到了这种情况，请问是怎么解决的呢

**Comment by tw93** [comment]
谢谢反馈，我本地模拟一下这个环境看看

**Comment by liuyfl** [comment]
@tw93 不行，demo无法加载出来
![_20190108205644](https://user-images.githubusercontent.com/24668614/50832049-f09f5f80-1387-11e9-949e-e350732582b7.jpg)
