### ISSUE TITLE
babel-preset-env

### ISSUE THREAD

**Issue by maoyu** [alibaba/weex-ui#372]
18年5月份时，按官方的步骤将weex-ui集成到weex项目是没有问题的。前天新创建项目时，集成weex-ui后，在vue页import操作就出错。 baberic 文件的presets是babel-preset-env

**Comment by tw93** [comment]
详细报错给一下哦

**Comment by tw93** [comment]
这个是正解 https://github.com/alibaba/weex-ui/issues/369#issuecomment-451812878
我找weex-toolkit将新版那个问题解决下就好
