### ISSUE TITLE
weex-tookit中引入组件失败报下面错误，大神请看看

### ISSUE THREAD

**Issue by zwblue** [alibaba/weex-ui#374]
Module parse failed: Unexpected token (82:8)
You may need an appropriate loader to handle this file type.
| return {
| width: this.width + 'px',
| ...this.indicatorColor
| };
| }

@ ./node_modules/weex-ui/packages/wxc-lightbox/index.vue 8:2-92
@ ./node_modules/weex-ui/packages/wxc-lightbox/index.js
@ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/index.vue
@ ./src/index.vue
@ ./.temp/entry.js
@ multi (webpack)-dev-server/client?http://172.188.32.116:8081 ./.temp/entry.js
大神
请帮忙看一下这个

**Comment by tw93** [comment]
很久之前不少同学碰到过

https://github.com/alibaba/weex-ui/issues/33#issuecomment-338462263
