### ISSUE TITLE
按照官方文档创建项目运行时报错  babel-loader采用 8.0.4

### ISSUE THREAD

**Issue by zhouqj1414657557** [alibaba/weex-ui#375]
这种我只能对 babel  进行降级处理吗?

**Comment by tw93** [comment]
https://github.com/weex-ui-team/weex-ui-demo/blob/master/webpack.config.js#L110
https://github.com/weex-ui-team/weex-ui-demo/blob/master/webpack.config.js#L153
参考一下这两行

**Comment by zhouqj1414657557** [comment]
嗯嗯  ，我昨天把babel  降级了后可以了，今天我试试你这方法

**Comment by tw93** [comment]
谢谢你的反馈，之前解法不适合了，是weex-toolkit有一个更新比较大，
参考这里即可：
https://alibaba.github.io/weex-ui/#/cn/with-weex-toolkit?id=%E5%9C%A8%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8-weex-ui


![image](https://user-images.githubusercontent.com/8736212/50806689-a9d34a80-1332-11e9-8c05-19a696f37ae3.png)
