### ISSUE TITLE
能针对最新版本的weex-toolkit处理下#370的问题么？

### ISSUE THREAD

**Issue by zwblue** [alibaba/weex-ui#376]
Module parse failed: Unexpected token (46:27)
You may need an appropriate loader to handle this file type.
|         disabledStyle
|       } = this;
|       const mrBtnStyle = { ...STYLE_MAP[type],
|         ...btnStyle,
|         ...BUTTON_STYLE_MAP[size]

config.js中
 excludeModuleReg: /node_modules(?!(\/|\\).*(weex).*)/,

webpack.common.conf.js中已有这个配置
 module: {
    rules: [
      {
        test: /\.js$/,
        use: [{
          loader: 'babel-loader'
        }],
        exclude: config.excludeModuleReg
      },

**Comment by tw93** [comment]
请参考 https://github.com/alibaba/weex-ui/issues/369#issuecomment-451812878 
这个是正解

**Comment by tw93** [comment]
这个是正解  https://github.com/alibaba/weex-ui/issues/369#issuecomment-451812878

**Comment by tw93** [comment]
文档已经更新 https://alibaba.github.io/weex-ui/#/cn/with-weex-toolkit?id=%E5%9C%A8%E9%A1%B9%E7%9B%AE%E4%B8%AD%E4%BD%BF%E7%94%A8-weex-ui
![image](https://user-images.githubusercontent.com/8736212/50806668-932cf380-1332-11e9-808f-a355f9e6cc7c.png)

**Comment by zwblue** [comment]
谢谢
