### ISSUE TITLE
请问一下wxc-tab-bar怎么在里面嵌套另一个vue？

### ISSUE THREAD

**Issue by reverseAndroid** [alibaba/weex-ui#378]
你们的demo只有一个text，能否添加上嵌套一个vue，从而实现，类似android的TabLayout+fragment的功能呢。请帮助我。

**Comment by tw93** [comment]
@reverseAndroid 这个embed组件可以满足你的需求，目前weex-ui上面的这个wxc-tabbar更多用于简单的场景
https://github.com/apache/incubator-weex/blob/master/examples/vue/include/tabbar.vue#L3

**Comment by tw93** [comment]
@zhuyuhaoliar  有的🙂

**Comment by tmceom** [comment]
@tw93 感谢大神们的无私，非常不错的框架，正在学习中
