### ISSUE TITLE
iOS weex 在WXCoreBridge类中子线程做了UI操作

### ISSUE THREAD

**Issue by fanglinwei** [alibaba/weex-ui#379]
Try to search for your [issue](https://github.com/alibaba/weex-ui/issues?utf8=%E2%9C%93&q=), it may have already been answered or even fixed in the development branch. 
 
 在开 issue 前，可以先搜索以下以往的旧 [issue](https://github.com/alibaba/weex-ui/issues?utf8=%E2%9C%93&q=)，你遇到的问题可能已经有人提了，也可能已经在最新版本中被修正。

开源项目的用户和维护者之间并不是甲方和乙方的关系，issue 也不是客服。
在开 issue 的时候，请抱着一种『一起合作来解决这个问题』的心态，同时请尽可能描述清楚，这样效率才会高。

Remember to delete the above statement before committing.
同时建议使用英语进行描述，这样国外的开发者也可以看懂，提交之前，**记得将上述说明删除!!**。

##### 1.Your development environment（weex、weex-toolkit、system and more).    
iOS   weex 0.20.1
iOS weex 在WXCoreBridge类中子线程做了UI操作

##### 2.Expected behavior and actual behavior.   
![default](https://user-images.githubusercontent.com/16839723/51009924-00d45c00-158d-11e9-97fc-41d82a68bdf6.png)

##### 3.Steps to reproduce the problem.    
 - 
 -

**Comment by tw93** [comment]
weex 的bug 可以统一报道 https://weex-project.io/cn/contributing.html#bao-bug
不建议放到weex-ui下面，因为weex ui的维护同学主要还是前端同学
