### ISSUE TITLE
到底是需要include还是exclude weex-ui

### ISSUE THREAD

**Issue by xxl558** [alibaba/weex-ui#38]
如果你的webpack.config.js中 babel-loader 配置有对 node_modules 进行 exclude 处理，需要排除掉 weex-ui 包才可以使用 exclude: /node_modules(?!\/.*(weex).*)/。

排除了整个/node_modules，不就包含了/node_modules(?!\/.*(weex).*)/吗？

**Comment by tw93** [comment]
也就是对node_modules下的weex-ui进行babel处理的意思
