### ISSUE TITLE
ERR! missing script: ide:preview

### ISSUE THREAD

**Issue by LouieLi03** [alibaba/weex-ui#381]
你好！我是初学者，按照官网引入Weex Ui，运行项目
<img width="580" alt="image" src="https://user-images.githubusercontent.com/20454921/51449858-fffbb100-1d68-11e9-9db1-df22ea3341b0.png">
<img width="719" alt="image" src="https://user-images.githubusercontent.com/20454921/51449880-1a358f00-1d69-11e9-84d9-84bf03b21260.png">
报以上错误，更新npm也没有用，烦请帮忙查看

**Comment by tw93** [comment]
这个看起来是EMAS这个编辑器问题，不是weex-ui这边问题，建议按照这个来https://alibaba.github.io/weex-ui/#/cn/with-weex-toolkit
或者升级EMAS到最新时事

**Comment by fantengfei** [comment]
所以问题解决了吗？

**Comment by belivar** [comment]
同问

**Comment by maimaituiguang** [comment]
我已放弃 EMAS 编译器
