### ISSUE TITLE
weex-city在搜索框输入数据出现下面的警告

### ISSUE THREAD

**Issue by githubchenshihua** [alibaba/weex-ui#382]
用demo运行也报了这个warn
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "sourceData"

found in

---> <WxcCity> at D:\webstormWorkSpace\programmer-app\node_modules\weex-ui\packages\wxc-city\index.vue
       <City> at D:\webstormWorkSpace\programmer-app\src\components\City.vue
         <Root>

**Comment by tw93** [comment]
谢谢反馈，我看一下

**Comment by tw93** [comment]
已经更新，请等待 0.6.10版本的weex-ui，代码提交提交，待发布中
