### ISSUE TITLE
wxc-tab-bar 嵌套 Vue 页面为什么在 web 端不显示呢？

### ISSUE THREAD

**Issue by ZhangLanqiu** [alibaba/weex-ui#383]
#### 环境信息:
* OS win7
* weex 1.3.11
* weex-ui 0.6.6

我根据官方文档的方式通过 WxcTabbar 作为底部导航栏展示页面，但是很奇怪的是，在手机中可以正常显示但在移动 Web 端无法展示当前的页面，而且页面的布局也很奇怪如下:
#### Web端
![124170033](https://user-images.githubusercontent.com/23022347/51667008-fe94e780-1ff9-11e9-9f86-037dec648558.png)

#### 手机
![image](https://user-images.githubusercontent.com/23022347/51667099-37cd5780-1ffa-11e9-9111-106ea3e3b5cd.png)

**Comment by tw93** [comment]
没有看懂原有截图样子和问题，看起来是高度设置错误的问题，请检查下demo中如下高度计算的代码
![image](https://user-images.githubusercontent.com/8736212/54086222-7ccb0480-4382-11e9-913a-d770a68213e3.png)
