### ISSUE TITLE
wxc-popover 报错

### ISSUE THREAD

**Issue by ibubbo** [alibaba/weex-ui#384]
![image](https://user-images.githubusercontent.com/32586819/51722704-41ee6500-2091-11e9-8043-0855832d41ec.png)

> Error in render: "TypeError: Cannot read property 'lines' of undefined"

我直接引入的[官网的例子](https://alibaba.github.io/weex-ui/#/cn/packages/wxc-popover/)，原封不动，为啥会出现这问题

**Comment by tw93** [comment]
和这个问题是一样的
归并到此 https://github.com/alibaba/weex-ui/issues/327
