### ISSUE TITLE
 wxc-lightbox 属性index 目前只有在第一个和最后一个时生效呢

### ISSUE THREAD

**Issue by limbo-wayne** [alibaba/weex-ui#387]
新增index和interval增强lightbox属性，稍后更新到最新即可

> npm i weex-ui@latest -S

| Prop | Type | Required | Default | Description |
|-------------|------------|--------|-----|-----|
| index | `Number` |`N`| `0` | 当前初始打开选择哪一页 |
| interval | `Number` |`N`| `3000` | 设置自动播放时候的间隔时间 |

_Originally posted by @tw93 in https://github.com/alibaba/weex-ui/issues/361#issuecomment-450460312_

index 目前只有在第一个和最后一个时生效呢

**Comment by gaoshu883** [comment]
在`setTimeout()`里动态更新索引貌似可以，例如：
```JavaScript
setTimeout(() => {
    this.index = index;
}, 20);
```

**Comment by tw93** [comment]
@limbo-wayne  里面其实是直接使用的 slider 组件进行多图切换的
没有做其他的处理，我这边本地测试直接赋值是可以的，方便贴一下代码吗？
或者暂时按照 @gaoshu883  这种方式处理就好
