### ISSUE TITLE
关于wxc-ep-slider在ios下,官方demo无法正常运行

### ISSUE THREAD

**Issue by JackChengGZ** [alibaba/weex-ui#389]
我刚开始在自己的项目中做了一个demo,在安卓下是可以的,但是在ios下不行,我的bindingx环境都已经搭建完成,我查看过之前的Issues,然后把官方的demo在weex playround中运行,也不可以,也参考过https://github.com/alibaba/weex-ui/blob/master/example/ep-slider/index.vue这个的方式;
https://h5.m.taobao.com/trip/wx-detection-demo/ep-slider/index.weex.js这个是编译后的地址,我把生成二维码在weex playgound运行,我去滑动元素,总是会跳转到第一个元素

**Comment by tw93** [comment]
可能是ios环境搭的有些有问题，Android是可以的，ios 可以去
![image](https://user-images.githubusercontent.com/8736212/54096426-cc431c00-43e6-11e9-87df-e67726f4c61f.png)

**Comment by JackChengGZ** [comment]
是官方的环境搭的有问题还是我自己的?不是一个bindingX就可以了吗
