### ISSUE TITLE
能否支持使用iconfont图标

### ISSUE THREAD

**Issue by hizhengfu** [alibaba/weex-ui#39]
目前此项目中都是使用的图片作为图标。http://www.iconfont.cn/ 中有大量的资源可以使用，图标是否可以直接使用字体图标。现在项目使用都是自行来替换，估计很多人都有类似需求。

**Comment by play175** [comment]
这是我的使用方法，仅供参考：

定义css
```
* {
  font-family: "iconfont" !important;
}
```
加载字体
```
beforeCreate() {
    var domModule = weex.requireModule('dom');
    //目前支持ttf、woff文件，不支持svg、eot类型,moreItem at http://www.iconfont.cn/
    domModule.addRule('fontFace', {
      'fontFamily': "iconfont",
      'src': "url('//at.alicdn.com/t/font_153151_5zv8k123shziwwmi.ttf')"
    });
  }
```

然后就可以愉快的使用了：

```
<text>&#xe715;用户中心</text>
```

**Comment by hizhengfu** [comment]
@play175 我们这也采用类似方案，封装了一个组件来处理图标的问题。目前类似wxc-tab-page组件中的图标是图片，如果使用图标需要自行修改才可以。如果在组件中可以直接支持字体图标，用起来会更方便。

**Comment by tw93** [comment]
@jlsky  本地可能是路径问题 获取不到的  建议放到cdn 或者直接使用http://iconfont.cn/

**Comment by jlsky** [comment]
真是奇怪了。刚把问题发上来，就发现，字体显示了。
我把字体放在了app的assets目录下。
mydom.addRule('fontFace', {
              'fontFamily': "iconfont3",
              'src': "url('file://asstes/iconfont2.ttf')"
          });
另外说明，用weex playground源码里的android代码，在加载本地js代码时，bundelUrl指向的是 http://your_ip:12580/examples/build/ 而不是js代码所在的assets目录。

**Comment by jlsky** [comment]
重新说明一下，字体在本地还是不成功。此前说的，出来的原因是：我在子组件里引用了网上的字体，主界面上显示了所用的字体，误导了。

**Comment by tw93** [comment]
weex iconfont 字体可能第一次出不来 ，可以参考这个优化  https://segmentfault.com/q/1010000009357817

**Comment by phoenixsky** [comment]
@jlsky 你引用的方式不对
参考官方文档
1. 怎么将字体挂载到页面 -->[dom \| Weex](https://weex.apache.org/cn/references/modules/dom.html#fontFace)
2. 如何区别本地资源和在线资源-->  [Path \(英\) \| Weex](https://weex.apache.org/cn/references/path.html#Schemes)
3. native端的相对路径--> [Path \(英\) \ # 相对路径| Weex](https://weex.apache.org/cn/references/path.html#Schemes)

### 结论
> 1. android或者iOS 访问本地图片或者字体,在weex中统一以 `local://`为前缀 ;
> 2.  `/`在android下如果加载的是字体对应的就是`assets`目录,若果加载的图片就从`drawable `, 所以iconfont.ttf放置在`src/assets`目录下的花,字体的url加载方式应该为`('local:///font/iconfont.ttf')`
> 3. iOS同理,不过资源文件在`bundle resources`下.(加载方法未测试)

### iconfontUtil.js
```
/**
 * 初始化加载iconfont字体
 * 
 * @type {{initIconfont: (function())}}
 */
let iconfontUtils = {
    initIconfont() {
        let dom = weex.requireModule('dom');
        //通过获取platform判断加载字体文件的路径,(待完善,在手机playground中,是无法加载本地文件的)
        let platform = weex.config.env.platform.toLowerCase();
        let url;
        if ( "android" == platform) {
            //本地资源采用'local:// '的方式加载
           //第三个斜杠是代表当前目录,对于android来说就是assets的文件夹,那么`/iconfont.ttf'`就是加载`assets`目录下的iconfont.ttf文件
            url = "url('local:///font/iconfont.ttf')";
        } else if ("ios" == platform) {
            //todo 理论上同android未测试
            url = "url('local:///font/iconfont.ttf')";
        } else {
            url = "url('http://at.alicdn.com/t/xxxxxxx.ttf')"
        }
        dom.addRule('fontFace', {
            'fontFamily': "iconfont",
            'src': url
        });
    }
}
export default iconfontUtils;
```

**Comment by tw93** [comment]
@hizhengfu 我对wxc-tab-page 进行了一次升级，新增[自定义nav栏头部](https://github.com/alibaba/weex-ui/blob/v0.2.7/packages/wxc-tab-page/README.md#注1自定义头部导航块)  这样就可以使用iconfont了
同时还有一些其他的升级，可以看一下wxc-tab-page的文档哦

**Comment by tw93** [comment]
可以更新weex-ui到最新，目前wxc-tab-bar、wxc-tab-page 已经支持配置iconfont

> npm i weex-ui@latest -S

详细设置可见
https://alibaba.github.io/weex-ui/#/cn/packages/wxc-tab-bar/?id=%e6%b3%a81%ef%bc%9a%e4%bd%bf%e7%94%a8-iconfont
