### ISSUE TITLE
自定义图标，在web上显示没有问题，但是在playground上面就会出错

### ISSUE THREAD

**Issue by LukeGod** [alibaba/weex-ui#391]
添加阿里图标

-------

![image](https://user-images.githubusercontent.com/22097805/53481937-1956f200-3ab9-11e9-8d5e-97cdcdfc077c.png)

--------

在web上模拟正常

![image](https://user-images.githubusercontent.com/22097805/53482109-7a7ec580-3ab9-11e9-94a9-a07e26068e65.png)

但是在手机的playground就会错误

![image](https://user-images.githubusercontent.com/22097805/53482201-abf79100-3ab9-11e9-9a48-05314f430163.png)

------------------

请问是什么原因导致的呢

**Comment by tw93** [comment]
记得这里有一个小坑，可以看看这个 https://github.com/alibaba/weex-ui/issues/39
或者直接在weex-ui群里来咨询大家
