### ISSUE TITLE
Weex-UI的组件是使用px的，我想用wx。

### ISSUE THREAD

**Issue by gonghuiyuan516** [alibaba/weex-ui#393]
Weex-UI的组件是使用px的，我想用wx这个单位，要下载源码手动修改吗

**Comment by tw93** [comment]
目前是按照750px去动态计算的，在阿里内部用weex ui 这种方式单位方式很多，关于你想用wx方式，建议先看看px这个能否解决问题？ 按理说是可以解决问题的

**Comment by gonghuiyuan516** [comment]
谢谢这位同学。

px解决不了，我看了闲鱼等APP，在PAD上 原声跳转Weex页面，字体图片等会等比放大，与原生DP方案不一样，导致用户看到的效果是瞬间放大。

目前是源码集成，改用wx单位。
