### ISSUE TITLE
wxc-slider-bar在Android上拖动，值更新错误

### ISSUE THREAD

**Issue by Akun97** [alibaba/weex-ui#394]

**Comment by tw93** [comment]
可以直接用demo在手淘、飞猪上面测试哦？
怀疑是客户端里bindingx配置有问题

**Comment by Akun97** [comment]
![image](https://user-images.githubusercontent.com/41559812/54105674-b47f8e00-440e-11e9-92b5-36de558ce32b.png)
![image](https://user-images.githubusercontent.com/41559812/54105702-cbbe7b80-440e-11e9-9089-3ecde35ddf12.png)
不是這樣配置嗎
