### ISSUE TITLE
WxcMask中使用input或textarea一直抖动

### ISSUE THREAD

**Issue by zhanggujun** [alibaba/weex-ui#395]
WxcMask中使用input或textarea一直抖动
    "weex-devtool": "^0.2.83",
    "weex-loader": "0.4.5",
    "weex-ui": "^0.6.8",
    "weex-vue-loader": "0.2.12",
    "weex-vue-render": "0.11.57"
    "vue": "2.4.2",
然后输入法上来的时候 会把导航顶上去 输入法隐藏的时候，导航条下不来。

**Comment by zhongwang2008** [comment]
删除源里的css样式的宽高试试吧

**Comment by tw93** [comment]
使用最新版本，记得已经修复了

**Comment by FavorPan** [comment]
我试过安装了最新版本，抖动依然存在
