### ISSUE TITLE
wxc-tab-page   组件设置top  left  right  bottom 边框方式，没找到合适方法

### ISSUE THREAD

**Issue by lichentao** [alibaba/weex-ui#396]
Try to search for your [issue](https://github.com/alibaba/weex-ui/issues?utf8=%E2%9C%93&q=), it may have already been answered or even fixed in the development branch. 
 
 在开 issue 前，可以先搜索以下以往的旧 [issue](https://github.com/alibaba/weex-ui/issues?utf8=%E2%9C%93&q=)，你遇到的问题可能已经有人提了，也可能已经在最新版本中被修正。

开源项目的用户和维护者之间并不是甲方和乙方的关系，issue 也不是客服。
在开 issue 的时候，请抱着一种『一起合作来解决这个问题』的心态，同时请尽可能描述清楚，这样效率才会高。

Remember to delete the above statement before committing.
同时建议使用英语进行描述，这样国外的开发者也可以看懂，提交之前，**记得将上述说明删除!!**。

##### 1.Your development environment（weex、weex-toolkit、system and more).    
 - botao-macbookpro:damai botao$ weex -v
   v1.3.11
 - weex-debugger : v1.2.5
 - weex-builder : v0.4.1
 - weex-previewer : v1.5.1
 - 

##### 2.Expected behavior and actual behavior.   
 - 
 - 
![image](https://user-images.githubusercontent.com/5095376/54187239-0fd17f00-44e8-11e9-9f78-e455f2dbc4e0.png)

##### 3.Steps to reproduce the problem.    
 - I want  to use  wxc-tab-page  to set bottom line for custom, like step 2  image

thank you for your regard ~
 -

**Comment by tw93** [comment]
![image](https://user-images.githubusercontent.com/8736212/55946620-9ca26080-5c7f-11e9-995a-7807b9c2cbc4.png)
通过这几个参数应该可以控制
