### ISSUE TITLE
wxc-button组件的btnStyle属性，设置fontSize没有效果

### ISSUE THREAD

**Issue by zhongwang2008** [alibaba/weex-ui#397]
v1.3.11
 - weexpack : v1.2.7
 - weex-debugger : v1.3.0
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1
  -weex-ui : 0.6.10

代码：
 <wxc-button text="登  录"
                    :btnStyle="{backgroundColor:'#3B444D', width:'620px',height: '94px',fontSize: '100px',borderRadius: '94px'}"
                    @wxcButtonClicked="wxcButtonClicked">
        </wxc-button>

**Comment by tw93** [comment]
文字样式设置textStyle 参数就好，参考  https://alibaba.github.io/weex-ui/#/cn/packages/wxc-button/?id=%E5%8F%AF%E9%85%8D%E7%BD%AE%E5%8F%82%E6%95%B0
