### ISSUE TITLE
wxc-button组件的disabled属性值变更时，按钮长度和圆角效果闪动。

### ISSUE THREAD

**Issue by zhongwang2008** [alibaba/weex-ui#398]
v1.3.11
 - weexpack : v1.2.7
 - weex-debugger : v1.3.0
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1
  -weex-ui : 0.6.10

wxc-button组件的disabled属性值变更时，按钮长度和圆角效果，瞬间从默认值变为自定义值；看上去就是闪了一下的现象。
代码：
 <input class="login-body-input"
               type="text"
               placeholder="请输入登录用户"
               v-model="userName"
               @input="onInput" />
<input class="login-body-input"
               type="password"
               placeholder="请输入登录密码"
               v-model="password"
               @input="onInput" />
<wxc-button text="登  录"
                    :disabled="isLoginDisabled"
                    :btnStyle="btnLoginStyle"
                    @wxcButtonClicked="wxcButtonClicked" />

 data () {
    return {
        isLoginDisabled: true, // 登录按钮状态（默认：禁用）
        btnLoginStyle: {
            width: '620px',
            height: '94px',
            // fontSize: '100px',//不起作用（bug）
            borderRadius: '94px',
            backgroundColor: '#008D92'// 3B444D
       }
    },
 methods: {
    onInput () {
      if (this.userName && this.password) {
        if (this.isLoginDisabled) {
          this.isLoginDisabled = false
          modal.toast({message: '启用'})
        }
      } else if (!this.isLoginDisabled) {
        this.isLoginDisabled = true
        modal.toast({message: '禁用'})
      }
    }
  }

**Comment by tw93** [comment]
已经升级，请稍后在0.6.11版本使用
