### ISSUE TITLE
一个按钮没有响应它的点击事件

### ISSUE THREAD

**Issue by aababy** [alibaba/weex-ui#40]
Before you start writing a issue,Please make sure [there](https://github.com/alibaba/weex-ui/issues?utf8=%E2%9C%93&q=) have not the same issue.

#### Your development environment（weex、weex-toolkit、system and more.）
weex  v1.1.0

#### Expected behavior and actual behavior.
一个最简单的例子, 一个按钮没有响应它的点击事件.

#### Steps to reproduce the problem.
1.安装weex & weex create xxx
2. cd 到 weex project 目录
3. npm i weex-ui -S
4. npm i babel-plugin-component -D
5. 替换该目录下的.babelrc
6. 修改index.vue, 添加一个按钮
7. npm run dev & npm run serve

[归档.zip](https://github.com/alibaba/weex-ui/files/1432863/default.zip)

**Comment by tw93** [comment]
:wxcButtonClicked="buttonClicked"  ==>  @wxcButtonClicked="buttonClicked"

**Comment by aababy** [comment]
我试过不: 换成 @ ,一样的效果

**Comment by tw93** [comment]
看了下代码  少了一个 { 导致了错误
```vue
<template>
  <div class="rootview">
    <div>
      <wxc-button :text="buttonName"
        @wxcButtonClicked="buttonClicked">
      </wxc-button>
    </div>

  </div>
</template>

<style>
  .wrapper { align-items: center; margin-top: 120px; }
  .title { padding-top:40px; padding-bottom: 40px; font-size: 48px; }
  .logo { width: 360px; height: 156px; }
  .desc { padding-top: 20px; color:#888; font-size: 24px;}
</style>

<script>
  import { WxcButton, WxcPopup } from 'weex-ui';
  var api = require('./api.js');

  export default {
    components: { WxcButton, WxcPopup },
    data: {
      logoUrl: api.apiurl.resurl + 'vued08aa73a9ab65dcbd360ec54659ada97c.png',
      searchicon: 'https://img.alicdn.com/tps/TB1z.55OFXXXXcLXXXXXXXXXXXX-560-560.jpg',
      target: 'World',
      buttonName: '这是一个按钮',
    },
    methods: {
      update: function (e) {
        this.target = 'Weex'
        console.log('target:', this.target)
      }, 
      buttonClicked: function () {
        this.buttonName = '被我点了一下'
        console.log('target:', this.buttonName)
      },
    }
  }
</script>
```

![jietu20171101-112359](https://user-images.githubusercontent.com/8736212/32258740-52b4acf6-be8a-11e7-96d3-1d886d6e8a1d.jpg)
