### ISSUE TITLE
为什么weex-ui的很多不实现v-model，而是用事件返回值呢

### ISSUE THREAD

**Issue by LukeGod** [alibaba/weex-ui#401]
比如日历，步进器，都没有双向绑定，而是通过@wxcPageCalendarDateSelected="calendarDateSelect" 等事件来返回结果。实现了双向绑定不是更好吗，为什么组件没有提供呢，处于什么样的考虑呢

**Comment by tw93** [comment]
weex 并不支持 v-model  所以就通过这种事件回调来弄
