### ISSUE TITLE
wxc-popup 需要指定确定的高度-可优化

### ISSUE THREAD

**Issue by yuwanli** [alibaba/weex-ui#403]
由于不支持百分比单位，底层封装的时候需要指定传入高度
觉得这块可以做下优化，因为有的时候弹窗的高度是自适应的并不是确定的，目前这种需要指定高度的方式使用起来比较鸡肋。
我这边尝试做了优化和尝试，具体可查看
[https://github.com/yuwanli/weex-coms/blob/master/components/weex-popup/README.md](https://github.com/yuwanli/weex-coms/blob/master/components/weex-popup/README.md)
可安装调试查看
`
npm install weex-coms -i
`

**Comment by tw93** [comment]
欢迎提交 pr @yuwanli

**Comment by tw93** [comment]
已经合并pr，关闭之
