### ISSUE TITLE
div标签的:hack的作用是？

### ISSUE THREAD

**Issue by yoyou** [alibaba/weex-ui#41]
<div class="wxc-overlay"
         ref="wxc-overlay"
         v-if="show"
         :hack="shouldShow"
         @click="overlayClicked"
         :style="overlayStyle">

**Comment by tw93** [comment]
和 watch 这个特性类似
主要是监听某些数据（多个）的变化，然后做一些事件操作

**Comment by pcwang0205** [comment]
@tw93  hack事件生效不了把，在数据变化的时候我hack事件都没进去
