### ISSUE TITLE
weex run android  加载界面绑定的数据显示不出来，网页端正常

### ISSUE THREAD

**Issue by Funnyyanne** [alibaba/weex-ui#410]
1.当前环境win7 64位
![1](https://user-images.githubusercontent.com/19363761/56332992-09a87f80-61c5-11e9-8337-9dee136415be.png)

2.编写weex官网的demo时，在android端显示失败，在网页加载显示正常
![3](https://user-images.githubusercontent.com/19363761/56333102-67d56280-61c5-11e9-96d3-cf2eafb47386.jpg)

![2](https://user-images.githubusercontent.com/19363761/56333129-7e7bb980-61c5-11e9-9184-ea30a17afcbe.png)

**Comment by tw93** [comment]
weex-toolkit 问题bug 可以提交到  https://github.com/weexteam/weex-toolkit
