### ISSUE TITLE
Wxc-minibar occasionally flickers when I switch between right-text text

### ISSUE THREAD

**Issue by pidogc** [alibaba/weex-ui#411]
![image](https://user-images.githubusercontent.com/42857270/56399093-f3201980-6200-11e9-907e-50de3c5eea78.png)

**Comment by zhongwang2008** [comment]
删除源码中的 "background-color: #009ff0;"
![QQ截图20190430140710](https://user-images.githubusercontent.com/41984848/56943262-43786f00-6b51-11e9-95c6-63880b869cdd.png)

**Comment by pidogc** [comment]
ok,i try it

**Comment by tw93** [comment]
@zhongwang2008  welcome pr

**Comment by tw93** [comment]
Please use the latest version
