### ISSUE TITLE
wxc-radio 组件现在只支持图片吗？还有如何改变icon大小呢

### ISSUE THREAD

**Issue by pidogc** [alibaba/weex-ui#412]
![image](https://user-images.githubusercontent.com/42857270/56540451-9fbe0c00-651d-11e9-9010-667ee9270f6e.png)
当icon出现后，明显因为icon大小问题，列被撑大了

**Comment by wjun94** [comment]
是改变打勾的icon大小吗？

**Comment by pidogc** [comment]
是的，該怎麼改變呢？文檔好像沒有提及

**Comment by wjun94** [comment]
weex-ui更新到0.6.12，就不会出现你这个问题了。
