### ISSUE TITLE
wxc-rich-text 组件type为tag时空格计算不准确

### ISSUE THREAD

**Issue by zhongdom** [alibaba/weex-ui#413]
使用 0.6.11版本，iOS和安卓端均存在此问题。 
- 如果 `value` 为纯汉字，大概6个以上文字就明显能看到标签和后面的文字之间的空格过大
- 如果 `value` 为纯字母或者纯数字，空格又明显少了，更极端的话会文字和标签会重叠

**Comment by wjun94** [comment]
可以给这个添加style设置样式，来取代空格。{type: 'tag', style: {设置样式}}
