### ISSUE TITLE
popup 层级无法调整吗？在其下方有定位元素

### ISSUE THREAD

**Issue by pidogc** [alibaba/weex-ui#415]
Can't the popup level be adjusted? There are positioning elements below it
![image](https://user-images.githubusercontent.com/42857270/56702926-6e7b4280-66bb-11e9-8a04-534254648a15.png)

**Comment by tw93** [comment]
现在weex本身不支持这个层级设定，然后这里建议通过顺序的方式来控制，想在上面显示的直接写到后面
