### ISSUE TITLE
image url //gw.alicdn.com/tfs/TB1x18VpwMPMeJjy1XdXXasrXXa-21-36.png convert problem

### ISSUE THREAD

**Issue by marekchen** [alibaba/weex-ui#42]
Before you start writing a issue,Please make sure [there](https://github.com/alibaba/weex-ui/issues?utf8=%E2%9C%93&q=) have not the same issue.

#### Your development environment（weex、weex-toolkit、system and more.）
- weex-android:0.16.0

#### Expected behavior and actual behavior.
- since weex-ui@v0.2.0 image src changed to '//gw.alicdn.com/tfs/TB1x18VpwMPMeJjy1XdXXasrXXa-21-36.png',on android platform,this url convert to  'file://gw.alicdn.com/tfs/TB1x18VpwMPMeJjy1XdXXasrXXa-21-36.png'

#### Steps to reproduce the problem.
- add 'http:' prefix to url such as 'http://gw.alicdn.com/tfs/TB1x18VpwMPMeJjy1XdXXasrXXa-21-36.png'

**Comment by tw93** [comment]
Thank you for your feedback.  I have fixed it 
please update weex-ui  to latest

```
npm i weex-ui@latest -S
```
