### ISSUE TITLE
wxc-mask overlay灰层没有遮挡住页面的输入框

### ISSUE THREAD

**Issue by zhongwang2008** [alibaba/weex-ui#425]
wxc-mask显示后，点击overlay灰层关闭；当再显示wxc-mask弹层，点击overlay灰层时，主页面里的文本框获取到了焦点，并且wxc-mask没有关闭；如下图所示：

![QQ截图20190430112957](https://user-images.githubusercontent.com/41984848/56939510-6ac44180-6b3b-11e9-8b06-1953869abe02.png)
![67BFB6DE-4372-47de-8A03-C00BA0E22027](https://user-images.githubusercontent.com/41984848/56939523-70218c00-6b3b-11e9-9b82-58d505368937.png)

**Comment by wjun94** [comment]
http://emas.weex.io/zh/solution-detail/detail.html?spm=a2c7j.-zh-community-.0.0.3c3c1a8ek3JsK7&id=42
参考第7条。

**Comment by zhongwang2008** [comment]
@wjun94 该问题是点击灰层，wxc-mask组件没有关闭或隐藏；不是文本框的焦点问题！

**Comment by tw93** [comment]
@zhongwang2008  这边暂时不能复现了，先关闭之
