### ISSUE TITLE
关于使用dialog和tabbar的问题

### ISSUE THREAD

**Issue by JackgorHJ** [alibaba/weex-ui#429]
在其他页面使用的dialog弹窗，但是一直出现在tabbar的第一个div里面，请问这个问题现在又得到解决吗？

**Comment by wjun94** [comment]
下一个版本，0.6.13。wxc-overlay 添加了left属性，可以通过设置left来移动dialog弹窗。

**Comment by tw93** [comment]
已经修复，稍等马上发布
