### ISSUE TITLE
 SyntaxError: Unexpected identifier 'UrlParser'. import call expects exactly one argument 报这个错误,引用了utils

### ISSUE THREAD

**Issue by zxb3121999** [alibaba/weex-ui#43]
调用tabpage的时候,报这个错误

**Comment by tw93** [comment]
npm i weex-ui@latest -S
try it

**Comment by zxb3121999** [comment]
还是一样的.

**Comment by tw93** [comment]
https://github.com/alibaba/weex-ui#weex-toolkit
Please post your environment and code

**Comment by zxb3121999** [comment]
v1.1.0-beta.6
 - weexpack : v0.4.7-beta.17
 - weex-builder : v0.2.13-beta.4
 - weex-devtool : v0.3.2-beta.7
 - weex-previewer : v1.3.13-beta.8
 - toolkit-repair : v0.0.5


{
  "presets": ["es2015", "stage-0"],
  "plugins": [
    [
      "component",
      {
        "libraryName": "weex-ui",
        "libDir": "packages"
      }
    ]
  ]
}

**Comment by zxb3121999** [comment]
代码就是你们那个例子里面的tabpag的代码

**Comment by tw93** [comment]
The error detail screenshot and the code post oh, is there any other component error?

**Comment by zxb3121999** [comment]
ReportException : Exception: SyntaxError: Unexpected identifier 'UrlParser'. import call expects exactly one argument.
                                                           at (global function):1292
                                                           Function@[native code]
                                                           Function@[native code]
                                                           w@(weex framework):4:2096
                                                           a@(weex framework):3:30077
                                                           (weex framework):8:26566

如果将这个页面单独做为一个页面是可以跑起来的.但如果做为一个tabpage里面的页面,调用js页面的话 就出问题了 我是通过weex compile编译的

**Comment by tw93** [comment]
@erha19  have a look

**Comment by zxb3121999** [comment]
通过npm run build形式打出来没问题.应该是编译问题.改用在webpack.config.js配置entry.就ok了.关闭问题了
