### ISSUE TITLE
wxc-swipe-action 這個組件沒有slot嗎？樣式也不能，感覺可用性不高啊？

### ISSUE THREAD

**Issue by pidogc** [alibaba/weex-ui#435]
這個組件最重要的就是左滑動的功能把，可以節省不少時間，但是現在什麼可操作的不多？感覺沒什麼用啊

**Comment by wjun94** [comment]
可以添加样式，但是slot估计是不行。

**Comment by pidogc** [comment]
感謝你的跟進！但是如果不支持slot，這個組件的實用性很小，在實際開發中，需求很小可能會這麼有這麼的cell，這樣顯得改組件很雞肋

**Comment by pidogc** [comment]
感謝你的跟進！但是如果不支持slot，這個組件的實用性很小，在實際開發中，需求很少可能會解構這麼簡單的cell，這樣顯得該組件很雞肋

**Comment by pidogc** [comment]
感謝你的跟進！但是如果不支持slot，這個組件的實用性很小，在實際開發中，需求很少可能會結構這麼簡單的cell，這樣顯得該組件很雞肋

**Comment by wjun94** [comment]
已经添加了slot标签的使用，后续验证下，如果没有啥问题，下个版本就可以使用slot标签。

**Comment by pidogc** [comment]
非常感謝你的更新，期待，個人感覺weex-ui可以多寫點富交互的組件，對移動端，我認為才是真正節省了開發者不少時間，這只是個人建議，希望weex-ui跟進一步發展吧，還有下次更新現在可以確定時間嗎？

**Comment by tw93** [comment]
@pidogc  有兴趣来一起开发weex-ui吗？

**Comment by pidogc** [comment]
感謝！但是現在由於項目關係十分繁忙，我可以在空閒時間嘗試pr一下

**Comment by tw93** [comment]
已经修复，使用最新版本即可
