### ISSUE TITLE
wxc-searchbar的barStyle設置其width控制的是外框，但是input的長度如何設置？

### ISSUE THREAD

**Issue by pidogc** [alibaba/weex-ui#437]
![image](https://user-images.githubusercontent.com/42857270/57932676-49b85c00-7870-11e9-9795-806812e070c3.png)
文檔中也沒有具體表明barStyle設置的具體支持數據

**Comment by wjun94** [comment]
目前没有暴露设置这个input宽度的属性

**Comment by tw93** [comment]
已经发布0.6.15版本
