### ISSUE TITLE
wxc-radio組件修改list array時無法修改期選中項

### ISSUE THREAD

**Issue by pidogc** [alibaba/weex-ui#438]
![image](https://user-images.githubusercontent.com/42857270/58565038-e371f880-81e2-11e9-8a7c-fcac5706915c.png)
![image](https://user-images.githubusercontent.com/42857270/58565116-07353e80-81e3-11e9-9339-bd9317d376d3.png)

**Comment by pidogc** [comment]
不知道是我寫錯了，還是什麼原因，切換時無法初始化，有空可否看看

**Comment by pidogc** [comment]
![image](https://user-images.githubusercontent.com/42857270/58600854-19db6200-823b-11e9-8004-7e04387e2239.png)

**Comment by pidogc** [comment]
查看源碼發現當list更新時，checkedIndex沒有初始化，導致當新list更新時，checked顯示問題,不知道是不是這個原因呢？麻煩有空查看一下，謝謝

**Comment by pidogc** [comment]
究竟有沒有問題呢？

**Comment by wjun94** [comment]
> 究竟有沒有問題呢？

感觉应该是你的写法有问题。

**Comment by pidogc** [comment]
但是切換tab時確實源碼沒有將checkedIndex初始化，props進去的list已經不是同一個了

**Comment by pidogc** [comment]
就是因為checkedIndex沒有初始化，導致foreach時，之前選的被重新變為true，導致的

**Comment by pidogc** [comment]
@wjun94 請問試過像這樣tab切換嗎？

**Comment by wjun94** [comment]
> @wjun94 請問試過像這樣tab切換嗎？

还没试过，目前没啥时间，比较忙。

**Comment by wjun94** [comment]
更新到下个版本解决。

**Comment by tw93** [comment]
已经发布0.6.15最新版本

**Comment by pidogc** [comment]
![image](https://user-images.githubusercontent.com/42857270/60752703-e7313180-9f7d-11e9-82aa-7dc1097fce8c.png)

**Comment by pidogc** [comment]
@wjun94 請問一下最新版本什麼後上線呢

**Comment by pidogc** [comment]
@tw93 发现升级到0.6.15后问题仍然没有解决，问题如上

**Comment by pidogc** [comment]
![image](https://user-images.githubusercontent.com/42857270/61303788-f8a7e400-a79c-11e9-9af6-df4618e230b5.png)

**Comment by pidogc** [comment]
还是没有初始化checkedIndex啊，问题根本没有解决

**Comment by wjun94** [comment]
更新到0.6.16 因为0.6.15没有把相关代码合并上去。

**Comment by wjun94** [comment]
> 还是没有初始化checkedIndex啊，问题根本没有解决

更新到0.6.16 因为0.6.15没有把相关代码合并上去。

**Comment by wjun94** [comment]
> @tw93 发现升级到0.6.15后问题仍然没有解决，问题如上

更新到0.6.16 因为0.6.15没有把相关代码合并上去。

**Comment by wjun94** [comment]
@pidogc 更新到0.6.16 因为0.6.15没有把相关代码合并上去。

**Comment by pidogc** [comment]
升級到0.6.16問題已解決，感謝
