### ISSUE TITLE
wxc-overlay层级过高

### ISSUE THREAD

**Issue by liandelanniao** [alibaba/weex-ui#439]
wxc-overlay层级过高，点击在它之后的div默认执行的是wxc-overlay的关闭方法

**Comment by wjun94** [comment]
靠后的元素层级更高，因此，对于层级高的元素，可将其排列在后面。可通过修改元素位置，修改层级结构。

**Comment by liandelanniao** [comment]
显示的元素就在遮罩组件的后边，而且遮罩层弹出的时候出现了闪烁

**Comment by liandelanniao** [comment]
找到问题了，安卓出现事件点击穿透现象

**Comment by liujie16638250858** [comment]
> 靠后的元素层级更高，因此，对于层级高的元素，可将其排列在后面。可通过修改元素位置，修改层级结构。

但是ios和安卓不行啊，还是会覆盖

**Comment by tw93** [comment]
可以参考这个 https://github.com/alibaba/weex-ui/blob/master/packages/wxc-dialog/index.vue#L25
