### ISSUE TITLE
mask 的属性overlay-can-close不起作用

### ISSUE THREAD

**Issue by hodgevk** [alibaba/weex-ui#44]
mask组件的overlay-can-close属性不起作用，查看了源码就没有使用到

**Comment by tw93** [comment]
已经改正，这应该是一个老参数，直接使用`overlay-cfg`配置就好，dev 分支已经替换

| 名称      | 类型     | 默认值   | 备注  |
|-------------|------------|--------|-----|
| overlay-cfg | `Object` | '{ hasAnimation: true, timingFunction: ['ease-in', 'ease-out'], duration: 300, opacity: 0.6,canAutoClose:true }' |  蒙层配置参数，参考 [wxc-overlay](https://github.com/alibaba/weex-ui/blob/master/packages/wxc-overlay/README.md) 组件 |
