### ISSUE TITLE
WxcPanItem组件的点击事件参数回传有问题

### ISSUE THREAD

**Issue by wangxulong2008go** [alibaba/weex-ui#441]
在WxcPanItem这个组件内，未使用props来接收extId，导致回传的时候参数拿不到问题，希望尽快加上props: {
      url: {
        type: String,
        default: ''
      },
      needSlider: {
        type: Boolean,
        default: true
      },
      extId:{
        type: Number,
        default:0
      }
    },的extId接收，否则安卓手机拿不到

**Comment by tw93** [comment]
最新版本 0.6.16 已加上
