### ISSUE TITLE
weex ui弹框类组件好像一直没解决 weex0.19+版本的适配啊。蒙层遮挡无效、弹框也是透传的。点击效果都直接在背后界面了

### ISSUE THREAD

**Issue by cyabc** [alibaba/weex-ui#444]
weex ui弹框类组件好像一直没解决 weex0.19+版本的适配啊。蒙层遮挡无效、弹框也是透传的。点击效果都直接在背后界面了

**Comment by cyabc** [comment]
进一步判断加了recycle-list就有这个问题

**Comment by tw93** [comment]
谢谢反馈，我们看一下

**Comment by cyabc** [comment]
> 谢谢反馈，我们看一下

<template>
  <div class="container">
    <div class="demo">
      <div
        class="btn"
        @click="openDialog"
      >
        <text class="btn-txt">对话消息Dialog</text>
      </div>
    </div>

    <input style="width:200px;height:100px;border-width:1;border-color:#ccccccc;" />

    <div class="demo">
      <div
        class="btn"
        style="width:200px;height:100px;"
        @click="testtt"
      >
        <text class="btn-txt">ccccccccccccccccccccccc</text>
      </div>
    </div>
    <recycle-list
      for="(item, i) in longList"
      switch="type"
    >
      <cell-slot
        @click="abc(i)"
        case="A"
        :style="{width:750,height:100}"
      >
        <text>- A {{i}} -</text>
      </cell-slot>
      <cell-slot case="B"  @click="abc(i)" :style="{width:750,height:100}">
        <text>- B {{i}} -</text>
      </cell-slot>
    </recycle-list>

    <wxc-dialog
      title="标题"
      content="这里是内容"
      :show="show"
      :single="false"
      :is-checked="isChecked"
      :show-no-prompt="true"
      @wxcDialogCancelBtnClicked="wxcDialogCancelBtnClicked"
      @wxcDialogConfirmBtnClicked="wxcDialogConfirmBtnClicked"
      @wxcDialogNoPromptClicked="wxcDialogNoPromptClicked"
    >
    </wxc-dialog>
  </div>
</template>

<script>
const modal = weex.requireModule("modal");
import { WxcDialog } from "weex-ui";
export default {
  components: { WxcDialog },
  data: function() {
    return {
      show: false,
      isChecked: false,
      longList: [
        { type: "A" },
        { type: "B" },
        { type: "B" },
        { type: "A" },
        { type: "B" }
      ]
    };
  },
  methods: {
    abc(i) {
      modal.alert({ message: "abc"+i });
    },
    testtt() {
      modal.alert({ message: 1 });
    },
    openDialog() {
      this.show = true;
    },
    wxcDialogCancelBtnClicked() {
      //此处必须设置，组件为无状态组件，自己管理
      this.show = false;
    },
    wxcDialogConfirmBtnClicked() {
      //此处必须设置，组件为无状态组件，自己管理
      this.show = false;
    },
    wxcDialogNoPromptClicked(e) {
      //此处必须设置，组件为无状态组件，自己管理
      this.isChecked = e.isChecked;
    }
  }
};
</script>
确认了一下，recycle里面的节点点击事件abc()  ,如果传了参数就出现这个bug。不传参数就正常。

**Comment by tw93** [comment]
![image](https://user-images.githubusercontent.com/8736212/68928577-5ab53c00-07c5-11ea-9501-7362732fc588.png)
目前recycle-list 不建议在实际线上业务使用！容易有问题
