### ISSUE TITLE
弹窗类问题

### ISSUE THREAD

**Issue by WolverineX1990** [alibaba/weex-ui#446]
在wxc-tab-bar内容页中使用弹窗类组件，弹窗类组件都会在第一个tab下显示，不论组件在哪个tab下使用

**Comment by wjun94** [comment]
weex-ui更新到最新版本(0.6.13)。https://github.com/alibaba/weex-ui/issues/429  参考这个issues

**Comment by tw93** [comment]
已经修复，请用最新版本weex-ui
