### ISSUE TITLE
Weex JSPlaygrounds "http://dotwe.org/vue/" is open source?

### ISSUE THREAD

**Issue by xiaoyang678** [alibaba/weex-ui#451]
I want to implement a Weex JSPlaygrounds inside the enterprise, like http://dotwe.org/vue/, is it open source？ or how should I implement it, can you suggest?

**Comment by tw93** [comment]
![image](https://user-images.githubusercontent.com/8736212/60712375-7708b880-9f49-11e9-9d46-0d38d186b6f9.png)
You can seek advice here
