### ISSUE TITLE
引入weex-UI组件，npm start编译很慢，修改保存也很慢

### ISSUE THREAD

**Issue by huanghao1234** [alibaba/weex-ui#452]
##### 1
MacBook Pro (Retina, 15-inch, Mid 2015)
weex -v
2.0.0-beta.17 (Core 2.0.0-beta.31)
- @weex-cli/doctor : v2.0.0-beta.20
- @weex-cli/generator : v2.0.0-beta.16
- @weex-cli/run : v2.0.0-beta.21
- @weex-cli/device : v2.0.0-beta.2
- @weex-cli/debug : v2.0.0-beta.31
- @weex-cli/compile : v2.0.0-beta.27
weex-ui: 0.6.14
node -v
v10.16.0
npm --version
6.9.0
##### 2.Expected behavior and actual behavior.   
 - npm start编译很慢
 -  21% building modules 99/104 modules 5 active ...ue-loader/lib/component-normalizer.js 
 
 - 
 -

**Comment by wjun94** [comment]
weex-ui可以设置按需引入试试。
