### ISSUE TITLE
在pack:web打包后，每个组件重复发起ajax请求的问题

### ISSUE THREAD

**Issue by goolorn** [alibaba/weex-ui#458]
有个weex项目，运行在web环境
使用npm run pack:web打包
"build:prod:web": "webpack --env.NODE_ENV=release"

打包后每个组件被打包成独立的JS
引发一个问题：

weex ui的tab-bar有4个组件，created的时候会有ajax数据请求，
打包后发现每个组件（有10个自定义组件）都在发起重复、相同的ajax请求，
加载个首页，竟然发起了4*10个数据请求

**Comment by goolorn** [comment]
weex ui的tab-bar有四个标签页，每个标签页是一个组件，
每个标签页created的时候会用stream.fetch数据文件
打包后发现项目中所有组件（项目有10个自定义组件）都在发起四个重复、相同的ajax请求，
加载个含tab-bar的首页，竟然发起了4*10个网络数据请求

开发模式下没有问题，使用npm run pack:web打包后，投产出现这个问题

**Comment by goolorn** [comment]
wxc-tab-page组件也有相同的问题
wxcTabPageCurrentTabSelected这个事件引发十几个相同的网络请求

**Comment by goolorn** [comment]
<wxc-tab-bar ref="tabbar" :tab-titles="tabbarTitles" :tab-styles="tabbarStyles" title-type="iconFont" @wxcTabBarCurrentTabSelected="wxcTabBarCurrentTabSelected">
  <div class="item-container" :style="contentStyle">
    <home-page ref="homePage" currentPage="currentPage"></home-page>
  </div>
  <div class="item-container" :style="contentStyle">
    <tv-page ref="tvPage"></tv-page>
  </div>
  <div class="item-container" :style="contentStyle">
    <search-page ref="searchPage"></search-page>
  </div>
  <div class="item-container" :style="contentStyle"></div>
  <div class="item-container" :style="contentStyle">
    <user-page ref="userPage"></user-page>
  </div>
</wxc-tab-bar>

**Comment by goolorn** [comment]
<wxc-tab-bar ref="tabbar" :tab-titles="tabbarTitles" :tab-styles="tabbarStyles" title-type="iconFont" @wxcTabBarCurrentTabSelected="wxcTabBarCurrentTabSelected">
  <div class="item-container" :style="contentStyle">
    <home-page ref="homePage" currentPage="currentPage"></home-page>
  </div>
  <div class="item-container" :style="contentStyle">
    <tv-page ref="tvPage"></tv-page>
  </div>
  <div class="item-container" :style="contentStyle">
    <search-page ref="searchPage"></search-page>
  </div>
  <div class="item-container" :style="contentStyle"></div>
  <div class="item-container" :style="contentStyle">
    <user-page ref="userPage"></user-page>
  </div>
</wxc-tab-bar>

**Comment by goolorn** [comment]
<wxc-tab-bar ref="tabbar" :tab-titles="tabbarTitles" :tab-styles="tabbarStyles" title-type="iconFont" @wxcTabBarCurrentTabSelected="wxcTabBarCurrentTabSelected">
  <div class="item-container" :style="contentStyle">
    <home-page ref="homePage" currentPage="currentPage"></home-page>
  </div>
  <div class="item-container" :style="contentStyle">
    <tv-page ref="tvPage"></tv-page>
  </div>
  <div class="item-container" :style="contentStyle">
    <search-page ref="searchPage"></search-page>
  </div>
  <div class="item-container" :style="contentStyle"></div>
  <div class="item-container" :style="contentStyle">
    <user-page ref="userPage"></user-page>
  </div>
</wxc-tab-bar>

**Comment by goolorn** [comment]
homePage
tvPage
searchPage
userPage

这几个是wxc-tab-bar的页面组件，created的时候请求数据

默认tab页homePage在created中初始化数据，被十个组件重复触发created，引发十几个重复请求

**Comment by tw93** [comment]
看起来是写法侧的问题，暂时关闭
