### ISSUE TITLE
wxc-slider-bar 在真机iPhoneX下拖动无反应, 在其他iPhone型号下正常

### ISSUE THREAD

**Issue by pygzfei** [alibaba/weex-ui#459]
真机下无法拖动, 而且@updateValue="updateValue" 而且返回值一直为初始值的value值
![image](https://user-images.githubusercontent.com/27998440/63579187-e57bf700-c546-11e9-8ee8-4ebf494f800d.png)
虚拟机下没问题, 可以拖动 , 返回值正常
![image](https://user-images.githubusercontent.com/27998440/63579326-3986db80-c547-11e9-96d4-734b1b047780.png)

**Comment by tw93** [comment]
放到安全区域以上试试
