### ISSUE TITLE
wxc-tab-page这个组件怎么把main的内容放在上方.导航栏放在下方

### ISSUE THREAD

**Issue by linyh123** [alibaba/weex-ui#46]
wxc-tab-page这个组件一般显示的是nav导航栏在上方,main内容在下方.
wxc-tab-page这个组件怎么把main的内容放在上方.nav导航栏放在最下方
看了一下属性,没有这个属性功能.看了组件的源码  要引多重js.
所以勉强用了绝对定位定到最下面.把main隐藏了.自己再手写一个main,所以就没有左右滑动的效果.
发帖问问大神们怎么解决的

**Comment by tw93** [comment]
你说的应该是这个 https://github.com/alibaba/weex-ui/issues/22
wxc-tab-page 更多是用于tab页面切换的
后续有计划提供，我暂时关闭这个哦，欢迎关注
