### ISSUE TITLE
wxc-overlay top not have `px`,?

### ISSUE THREAD

**Issue by SleepingCat-xiaohui** [alibaba/weex-ui#460]
Hi, component `wxc-overlay` props `top` is Number, but why `computed. overlayStyle.top` is `this.top` not have `px`?

Hello, 咱们组件 `wxc-overlay` 有个 props `top` 是 Number 类型，但是计算属性里的 top 没有 px，，？

**Comment by tw93** [comment]
谢谢反馈，已经修复，请使用最新版本
