### ISSUE TITLE
wxc-tab-page 返回时上个界面的内容会等一下才消失,请看下视频可能是什么原因,

### ISSUE THREAD

**Issue by b1003572686** [alibaba/weex-ui#465]
=
[QQ20190920-174358-HD.mp4.zip](https://github.com/alibaba/weex-ui/files/3635282/QQ20190920-174358-HD.mp4.zip)

**Comment by tw93** [comment]
这个看起来应该和你们路由侧有关系，可以试试在代码侧解决这个问题，修改外侧的overflow属性试试
