### ISSUE TITLE
wxc-tab-bar   iphoneX series   error height

### ISSUE THREAD

**Issue by ruhao0518** [alibaba/weex-ui#466]
What do I have to do to make this ‘wxc-tab-bar’ compatible with the iphoneX series？
I want it to have a reasonable height when displayed.
When I open this project on my iPhoneX using a browser, his tabbar displays as shown below.
我在使用wxc-tab-bar进行web开发时，在iphoneX系列的微信浏览器上打开时，出现了tabbar高度偏高的情况。我需要做些什么使得wxc-tab-bar能够兼容iphoneX系列。
![tabbar-error](https://user-images.githubusercontent.com/43698090/65816935-1fba7180-e234-11e9-9364-a98e337779ae.png)

**Comment by ruhao0518** [comment]
我的配置如下：
tabIconFontStyles: {
      bgColor: '#f3f3f3',
      titleColor: '#666666',
      activeTitleColor: '#ff0000',
      activeBgColor: '#f3f3f3',
      isActiveTitleBold: true,
      width: 160,
      height: 120,
      fontSize: 24,
      textPaddingLeft: 10,
      textPaddingRight: 10,
      iconFontSize: 50,
      iconFontMarginBottom: 8,
      iconFontColor: '#333333',
      activeIconFontColor: 'red',
      iconFontUrl: '//at.alicdn.com/t/font_1298046_zep41u7vy5.ttf'
    }

**Comment by tw93** [comment]
这个iphoneX 判断更多是针对在 weex 环境下面的，这里我给你加一个参数supportXBar解决，你判断假如微信环境就传入 false 就好

**Comment by ruhao0518** [comment]
感谢解答
