### ISSUE TITLE
Can not use two 'tag' in specialConfigList of wxc-rich-text

### ISSUE THREAD

**Issue by myeveryheart** [alibaba/weex-ui#47]
In specialConfigList of wxc-rich-text, we can use one 'tag' and one 'text'. When we try to use two 'tag's and one 'text', then there's error.
Can it be multi 'tag's and 'text's?

**Comment by tw93** [comment]
you can use the `wxc-rich-text` for mixed situation like this:
```
icon+tag+text+link (1 line)
```


and the `wxc-special-rich-text` only supports two lines like 
```
icon+text(2 lines)
tag+text(2 lines)
```

**Comment by myeveryheart** [comment]
@tw93 tks, I know how to use wxc-rich-text and wxc-special-rich-text, I just wish to use tag+tag+text(2 lines)
