### ISSUE TITLE
WxcMask中使用textarea输入时一直抖动

### ISSUE THREAD

**Issue by FavorPan** [alibaba/weex-ui#470]
"dependencies": {
    "phantom-limb": "^0.0.1",
    "vue": "^2.5.11",
    "weex-ui": "^0.7.0",
    "weex-vue-render": "^1.0.17"
  },
使用的是0.7.0版本 weex-ui，但是仍然有抖动问题

**Comment by Sijia1998** [comment]
> "dependencies": {
> "phantom-limb": "^0.0.1",
> "vue": "^2.5.11",
> "weex-ui": "^0.7.0",
> "weex-vue-render": "^1.0.17"
> },
> 使用的是0.7.0版本 weex-ui，但是仍然有抖动问题

@FavorPan 设备型号是什么呀？方便贴一下代码吗，我这边没有复现你说的问题...

**Comment by FavorPan** [comment]
![image](https://user-images.githubusercontent.com/38341183/67746617-0e57b700-f9e4-11e9-8634-597a0aa12a42.png)

**Comment by FavorPan** [comment]
设备：华为mate20 ；华为平板BTV-W09；三星SM-T380C；小米平板4

**Comment by Sijia1998** [comment]
> 设备：华为mate20 ；华为平板BTV-W09；三星SM-T380C；小米平板4

![image](https://user-images.githubusercontent.com/29126094/68276744-9d319700-00a8-11ea-8b31-583b36b3a8d1.png)

进钉钉群交流一下吧

**Comment by Sijia1998** [comment]
> 设备：华为mate20 ；华为平板BTV-W09；三星SM-T380C；小米平板4

<table><tr><td><img src="https://img.alicdn.com/tfs/TB1AEsZf7T2gK0jSZPcXXcKkpXa-750-990.jpg" width="190"></td></tr></table>
进钉钉群交流一下吧

**Comment by Sijia1998** [comment]
> 设备：华为mate20 ；华为平板BTV-W09；三星SM-T380C；小米平板4

<table><tr><td><img src="https://img.alicdn.com/tfs/TB1AEsZf7T2gK0jSZPcXXcKkpXa-750-990.jpg" width="190"></td></tr></table>
@FavorPan 进钉钉群交流一下吧

**Comment by tw93** [comment]
已经修复，麻烦升级weex-ui 到最新版本即可
