### ISSUE TITLE
wxc-popup need overlay's click can not close

### ISSUE THREAD

**Issue by DorisOu** [alibaba/weex-ui#473]
"weex-ui": "^0.6.16",
"weex-vue-render": "^1.0.17"

1. I need the ovelay could not close when click it.

**Comment by tw93** [comment]
Please add param ：`:overlay-cfg="{'can-auto-close': false}"`

**Comment by DorisOu** [comment]
@tw93 sorry, I make a mistake,  overlay's click can not close in wxc-mask, I have set  overlay-can-close="false",pls check the below codes：
<wxc-mask height="500"
              width="500"
              border-radius="0"
              duration="200"
              mask-bg-color="rgba(255,255,255,0)"
              :has-animation="hasBusiness"
              :has-overlay="true"
              :show-close="false"
              :show="showBusiness"
              :overlay-can-close="false"
              @wxcMaskSetHidden="wxcMaskBusiness">
    </wxc-mask>
<wxc-mask height="500"
              width="500"
              border-radius="0"
              duration="200"
              mask-bg-color="rgba(255,255,255,0)"
              :has-animation="hasBusiness"
              :has-overlay="true"
              :show-close="false"
              :show="showBusiness"
              overlay-can-close="false"
              @wxcMaskSetHidden="wxcMaskBusiness">
    </wxc-mask>:
