### ISSUE TITLE
手势滑动切换时，对应的tabPage页面没有跟随手指一起动

### ISSUE THREAD

**Issue by Stone-Wang** [alibaba/weex-ui#48]
用的ios,如果手指只是滑动一点点，页面是不动的，滑动的大的话，会根据手势，通过动画过渡到另一页，但没有随我的手指一点一点滑动，但是看你的demo，是可以这样的。原因是wxc-item吗？

**Comment by tw93** [comment]
这个是使用的expressionBinding的一个特性，目前寒老师这边正在开源中，我暂时关闭此issue，可以关注这个issue
https://github.com/alibaba/weex-ui/issues/6

**Comment by Stone-Wang** [comment]
好的，thx
