### ISSUE TITLE
请问你们是如何处理自定义标签的，比如mask

### ISSUE THREAD

**Issue by lijicheng123** [alibaba/weex-ui#49]
dialog的组件有一些问题，可能是自定义标签造成的，希望回答一下

#### Your development environment（weex、weex-toolkit、system and more.）
```
"dependencies": {
    "vue": "^2.1.10",
    "vue-router": "^2.1.1",
    "vuex": "^2.1.1",
    "vuex-router-sync": "^4.0.1",
    "weex-ui": "^0.2.4",
    "weex-vue-render": "^0.12.3"
  },
"devDependencies": {
    "babel-core": "^6.20.0",
    "babel-loader": "^6.2.9",
    "babel-plugin-component": "^0.10.1",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-stage-0": "^6.24.1",
    "css-loader": "^0.26.1",
    "serve": "^1.4.0",
    "vue-loader": "^10.0.2",
    "vue-template-compiler": "^2.1.10",
    "webpack": "^2.2.1",
    "weex-loader": "^0.4.4"
  }
```
- node v8.9.1

- weex、weex-toolkit都是根据最新的安装的，windows7

#### Expected behavior and actual behavior.
- wxc-dialog组件根本无法显示
- 官方demo的xc效果
![image](https://user-images.githubusercontent.com/15669871/32644470-ba76e2d4-c61c-11e7-878a-cb7b9f6cde49.png)
- 自己的效果
![image](https://user-images.githubusercontent.com/15669871/32644523-f851493c-c61c-11e7-87bc-93f2b4cd9472.png)

-如果我吧wxc-dialog组件的index.vue的mask标签改成div后是能正常的显示的
![image](https://user-images.githubusercontent.com/15669871/32644589-74c0c876-c61d-11e7-9c5c-a5d3b6378727.png)

-然后就正常了
![image](https://user-images.githubusercontent.com/15669871/32644885-5a360eb0-c61f-11e7-835a-eef5d0915380.png)

#### Steps to reproduce the problem.
- npm run dev
- npm run serve

**Comment by tw93** [comment]
抱歉，这是我的疏忽，mask这个组件在weex-vue-render中没有被兼容导致，我已经替换成wxc-overlay来实现，请更新weex-ui到最新即可
