### ISSUE TITLE
子组件改变父组件的值,父组件通过字面量定义的style,在回调后不会生效

### ISSUE THREAD

**Issue by phoenixsky** [alibaba/weex-ui#52]
####  封装了一个选项菜单,点击后会通过pick弹出选项, 第一次加载`textarea`的背景色为red,但通过`onSelected`回调后,`textarea`的背景色就会变成class里边定义的gray.代码如下
```
<template>
    <div class="wrapper">
        <option-text class="option"
                     @onSelected="selectedValue => item.value = selectedValue">
        </option-text>
        <textarea class="input" style="background-color: red"></textarea>
    </div>
</template>

<script>
    import optionText from '../../component/option-text.vue'
    export default {
        components: {
            optionText,
        },
        data() {
            return {
                item:{
                    value: 2,
                    remark: '备注4',
                }

            }
        },
        methods: {}
    }
</script>

<style scoped>

    .wrapper {
        width: 750px;
        background-color: white;
        flex-direction: column;
    }

    .option {
        height: 70px;
        width: 280px;
        margin: 5px;
    }

    .input {
        background-color: gray;
    }


</style>
```

但是如果通过动态绑定的方式如将`textarea`的代码修改为
```
<textarea class="input" :style="{backgroundColor: red}"></textarea>
```
这样就没问题了,这个是什么原因?

#### 另外,顺便在问下两个问题,
1.  weex在国际化方面有相关的文档么?
2. 下图这个报错是不支持三角函数么?,在webstorm中,可以设置么?
![image](https://user-images.githubusercontent.com/6359214/32690944-615c87ae-c6c5-11e7-8502-b007e37d805e.png)

**Comment by tw93** [comment]
第一个问题 需要 `:style`这样写，不然你传入的就是string类型了
第二个问题 国际化的东西可以试试这个 https://github.com/kazupon/vue-i18n
第三个问题 是支持的，设置webstorm js 为es6就好，但是建议放到methods处理会优雅一点

**Comment by phoenixsky** [comment]
第一个问题没有表达清楚.我的意思是.
1.  页面`第一次加载`的时候,使用`style="background-color: red"`的方式是生效的.
2.  但是经过@onSelected方法后,通过字面量定义的style就不生效了.
> 我代码中`option-text'就是一个点击后会弹出一个选项列表,选择一个选项后,通过回调执行@onSelected()方法,将选中的值,赋给页面中的item.value,页面加载后,背景都是红的,点击option-text,回调后,通过`style="background-color: red"`定义的红色背景就无效了.

以上情况有个前提就是,`class`中已经定义过了`style`中定义的属性,才会出现.
 比如 input的选择器和style中都定义了 `background-color`属性

**Comment by tw93** [comment]
native 和 web 渲染都一样吗？

**Comment by phoenixsky** [comment]
重新缕了一下,android端用playground预览和直接运行在android native中都有这个问题.
我写了个简单的demo.
```
<template>
    <div style="width: 750px;">
        <text style="width: 100px;height: 100px;background-color: #afddff" @click="item.value = 10"></text>
        <input class="input" style="background-color: red; font-size: 50px" :value="item.value"/>
    </div>
</template>

<style scoped>
    .input {
        background-color: gray;
    }
</style>

<script>
    export default {
        data() {
            return {
                item: {
                    key: 2,
                    value: 1,
                }
            }
        }
    }
</script>
```

根据效果来分析是,只要input绑定的value发生了变化,那么这个input会重新渲染,但是重新渲染的时候,通过字面量赋值的style里的属性,如果在class也有,就会被忽略.

**Comment by tw93** [comment]
@phoenixsky 我看了看native这边都有这个问题的，建议写成{backgroundColor: red} 这样哦
内部处理问题，重新渲染没有考虑那种情况
