### ISSUE TITLE
编译js "use strict" 导致运行-2013

### ISSUE THREAD

**Issue by littleantsos** [alibaba/weex-ui#54]
//"use strict";
Object.defineProperty(__webpack_exports__, "__esModule", { value: true });
const STYLE_MAP = {
  taobao: {
    backgroundColor: '#FF5000'
  },
  fliggy: {
    backgroundColor: '#FFC900'
  },
  normal: {
    backgroundColor: '#FFFFFF',
    borderColor: '#A5A5A5',
    borderWidth: '1px'
  },
  highlight: {
    backgroundColor: '#FFFFFF',
    borderColor: '#EE9900',
    borderWidth: '1px'
  }
};

编出的js文件中这行代码报错, 但是把"use strict";注释掉就OK了.这是源码的问题,还是编译出了问题?

**Comment by tw93** [comment]
详细报错信息贴一下哦

**Comment by littleantsos** [comment]
11-17 08:00:53.704 15001-15001/com.haitai.android.jiaoren W/amapsdk: Key验证失败：[INVALID_USER_SCODE]
11-17 08:00:56.585 15001-15016/com.haitai.android.jiaoren D/weex: callJS >>>> instanceId:1function:callJS tasks:[{"data":"1","type":2},{"data":"[{\"args\":[\"5\",\"click\",{\"position\":{\"height\":59.895832,\"width\":180.20833,\"x\":0,\"y\":56.770832}},null],\"method\":\"fireEvent\"}]","type":3}]
11-17 08:00:56.586 15001-15016/com.haitai.android.jiaoren D/weex: [WXBridgeManager] callNative >>>> instanceId:1, tasks:[{"module":"navigator","method":"push","args":[{"url":"file://assets/dist/pages/setting.js","animated":"true"},"2"]}], callback:-1
11-17 08:00:56.587 15001-15016/com.haitai.android.jiaoren D/weex: [WXBridgeManager] callNative >>>> instanceId:1, tasks:[{"module":"dom","method":"updateFinish","args":[]}], callback:-1
11-17 08:00:56.591 15001-15016/com.haitai.android.jiaoren D/weex: callJS >>>> instanceId:1function:callJS tasks:[{"data":"1","type":2},{"data":"[{\"args\":[\"2\",\"WX_SUCCESS\",false],\"method\":\"callback\"}]","type":3}]
11-17 08:00:56.591 15001-15016/com.haitai.android.jiaoren D/weex: [WXBridgeManager] callNative >>>> instanceId:1, tasks:[{"module":"dom","method":"updateFinish","args":[]}], callback:-1
11-17 08:00:56.591 15001-15016/com.haitai.android.jiaoren D/weex: callJS >>>> instanceId:1function:callJS tasks:[{"data":"1","type":2},{"data":"[{\"args\":[\"2\",\"WX_FAILED\",false],\"method\":\"callback\"}]","type":3}]
11-17 08:00:56.591 15001-15016/com.haitai.android.jiaoren D/weex: [WXBridgeManager] callNative >>>> instanceId:1, tasks:[{"module":"dom","method":"updateFinish","args":[]}], callback:-1
11-17 08:00:56.594 15001-15016/com.haitai.android.jiaoren D/weex: callJS >>>> instanceId:1function:callJS tasks:[{"data":"1","type":2},{"data":"[{\"args\":[\"_root\",\"viewdisappear\",null,null],\"method\":\"fireEvent\"}]","type":3}]
11-17 08:00:56.594 15001-15016/com.haitai.android.jiaoren D/weex: [WXBridgeManager] callNative >>>> instanceId:1, tasks:[{"module":"dom","method":"updateFinish","args":[]}], callback:-1
11-17 08:00:56.601 15001-15001/com.haitai.android.jiaoren W/weex: Warning :Component tree has not build completely,onActivityCreate can not be call!
11-17 08:00:56.602 15001-15001/com.haitai.android.jiaoren E/WXTBUtil: isSupportSmartBar:false
11-17 08:00:56.602 15001-15001/com.haitai.android.jiaoren D/WXTBUtil: status:84
11-17 08:00:56.603 15001-15001/com.haitai.android.jiaoren D/WXTBUtil: height:2308
11-17 08:00:56.604 15001-15001/com.haitai.android.jiaoren W/weex: Warning :Component tree has not build completely,onActivityStart can not be call!
11-17 08:00:56.604 15001-15001/com.haitai.android.jiaoren W/weex: Warning :Component tree has not build completely, onActivityResume can not be call!
11-17 08:00:56.604 15001-15016/com.haitai.android.jiaoren D/weex: createInstance >>>> instanceId:2, options:{"bundleUrl":"file://assets/dist/pages/setting.js"}, data:null
11-17 08:00:56.604 15001-15016/com.haitai.android.jiaoren D/weex: callJS >>>> instanceId:2function:createInstance
11-17 08:00:56.606 15001-15016/com.haitai.android.jiaoren E/jsengine:  ReportException :undefined:345: SyntaxError: Use of const in strict mode.
11-17 08:00:56.607 15001-15016/com.haitai.android.jiaoren E/jsengine:  ReportException : SyntaxError: Use of const in strict mode.
                                                                          at Jt ((weex):4:2004)
                                                                          at Object.Dt [as createInstance] ((weex):3:31729)
                                                                          at Object.R [as createInstance] ((weex):1:7385)
                                                                          at global.(anonymous function) ((weex):7:1148)
11-17 08:00:56.608 15001-15016/com.haitai.android.jiaoren E/weex: reportJSException >>>> instanceId:2, exception function:createInstance, exception:SyntaxError: Use of const in strict mode.
11-17 08:00:56.658 15001-15021/com.haitai.android.jiaoren E/EGL_emulation: tid 15021: eglSurfaceAttrib(1165): error 0x3009 (EGL_BAD_MATCH)
11-17 08:00:56.658 15001-15021/com.haitai.android.jiaoren W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xa002f1c0, error=EGL_BAD_MATCH
11-17 08:00:56.786 15001-15027/com.haitai.android.jiaoren E/Surface: getSlotFromBufferLocked: unknown buffer: 0xadbf26c0
11-17 08:00:57.056 15001-15021/com.haitai.android.jiaoren E/Surface: getSlotFromBufferLocked: unknown buffer: 0xb4015090 
这是进入新页面后所有的日志,我是通过ReportException :undefined:345: SyntaxError: Use of const in strict mode.这行把上面的use strict 给注释了,就运行成功了

**Comment by littleantsos** [comment]
"use strict";
Object.defineProperty(__webpack_exports__, "__esModule", { value: true });
const STYLE_MAP = {
  taobao: {
    backgroundColor: '#FF5000'
  },
  fliggy: {
    backgroundColor: '#FFC900'
  },
  normal: {
    backgroundColor: '#FFFFFF',
    borderColor: '#A5A5A5',
    borderWidth: '1px'
  },
  highlight: {
    backgroundColor: '#FFFFFF',
    borderColor: '#EE9900',
    borderWidth: '1px'
  }
};
这个是编译后的js的错误代码部分

**Comment by tw93** [comment]
你现在的node版本是多少，低版本应该不支持，更新node到6以上即可

**Comment by littleantsos** [comment]
我的版本已经更新到V8.9.0了，这个问题折磨了我老久了，差点就要换react来做了，结果让我找到问题的位置了， T T

**Comment by tw93** [comment]
@littleantsos  已经修复了吗？ 没有问题了，可以将这个issue关掉
