### ISSUE TITLE
Popup 弹出的内容区域只有设置 width 的一半

### ISSUE THREAD

**Issue by caiyongmin** [alibaba/weex-ui#55]
Before you start writing a issue,Please make sure [there](https://github.com/alibaba/weex-ui/issues?utf8=%E2%9C%93&q=) have not the same issue.

#### 一、Your development environment（weex、weex-toolkit、system and more.）
- weex-toolkit
- Mac OS

##### Expected behavior
弹出的内容区域等于设置的 width 值。
![image](https://user-images.githubusercontent.com/11053605/33059277-91f5c31a-cece-11e7-8be8-7c0e697bbb99.png)

##### Actual behavior
弹出的内容区域只有设置 width 值的一半。

#### 三、Steps to reproduce the problem.
使用通用 demo 就可以复现。

**Comment by tw93** [comment]
加上这个试试 https://github.com/weexteam/weexpack-create/pull/2/commits/ee820f3fb7bbe886a3bf00ed3c772b4ee7519532#diff-79e419d0157b98ec6be582b1b394d819

**Comment by caiyongmin** [comment]
i already add those code:

```js
{
        test: /\.vue(\?[^?]+)?$/,
        use: [{
          loader: 'vue-loader',
          options: {
            /**
             * important! should use postTransformNode to add $processStyle for
             * inline style normalization.
             */
            compilerModules: [
              {
                postTransformNode: el => {
                  el.staticStyle = `$processStyle(${el.staticStyle})`
                  el.styleBinding = `$processStyle(${el.styleBinding})`
                }
              }
            ]
          }
        }]
      },
```

**Comment by tw93** [comment]
@caiyongmin  Is that all right?

**Comment by caiyongmin** [comment]
@tw93  nope, still has the problem.

**Comment by caiyongmin** [comment]
我觉得问题不是出在这儿，扫仓库首页的二维码查看，也是有这样的问题。
左边弹出来的 popup 的宽度只有设置宽度(500)的一半(250)。

![image](https://user-images.githubusercontent.com/11053605/33070420-eae7c97c-cef2-11e7-99a1-83dc4abc6665.png)

**Comment by tw93** [comment]
That should be correct , Because it's based on 750

**Comment by caiyongmin** [comment]
![image](https://user-images.githubusercontent.com/11053605/33071900-5520afe8-cef8-11e7-8a94-707ba13ef483.png)

确实是由于 设备像素比 的问题，`transform: translateX(250px)` 里面的值是 250px
但是 `width: 500px` 里面的值是 500px，感觉就有点奇怪，应该是 250px 才对。如果是 500px 的话，左边就有一大片空白需要用 padding-left 填充，不然就看不到设置的内容。

![image](https://user-images.githubusercontent.com/11053605/33072138-3f2cf628-cef9-11e7-968a-ff3dafd5c398.png)

**Comment by tw93** [comment]
> weex update weexpack
Recreate a project and replace it. do not forget 
> npm i 
> npm i babel-preset-stage-0 -D
and you can see it here https://github.com/tw93/weex-ui-with-toolkit
![image](https://user-images.githubusercontent.com/8736212/33073188-0c8e3bce-cefd-11e7-9574-87bbb3f4d415.png)

**Comment by caiyongmin** [comment]
OK, thx! I'll check the webpack configuration to see what went wrong.
