### ISSUE TITLE
import { wxcButton } from 'weex-ui';   这个wxcButton的首字母应该是大写WxcButton才能取到

### ISSUE THREAD

**Issue by MR-yuhuashi** [alibaba/weex-ui#56]
Before you start writing a issue,Please make sure [there](https://github.com/alibaba/weex-ui/issues?utf8=%E2%9C%93&q=) have not the same issue.

#### Your development environment（weex、weex-toolkit、system and more.）
- 
- 

#### Expected behavior and actual behavior.
- 
- 

#### Steps to reproduce the problem.
- 
-

**Comment by tw93** [comment]
Thank you for your feedback. I made the mistake of the document and I will modify it right away
