### ISSUE TITLE
expressionBinding

### ISSUE THREAD

**Issue by fromIRIS** [alibaba/weex-ui#6]
any detail information or document about expressionBinding feature ? i can not find this feature in offical document [website](http://weex-project.io/cn/guide/)  

and how can i import this module as you say in this readme?

thanks!

**Comment by Rowandjj** [comment]
@fromIRIS hello, `expression binding`  feature is not included in weex_sdk for now, but we plan to open source it later this year。
thanks for your attention:)

**Comment by fromIRIS** [comment]
@Rowandjj so currently we can not use this kind of components like [wxc-tab-page](https://github.com/alibaba/weex-ui/blob/master/packages/wxc-tab-page/README.md) in our app which includes weex sdk(0.13.0) even 0.16.0 ?

**Comment by Rowandjj** [comment]
@fromIRIS i'am sorry but yes.

**Comment by wintercn** [comment]
@Rowandjj 
I would suggest removing these components from open-source version of weex-ui until we finish our work on open-source expression binding feature.

**Comment by Rowandjj** [comment]
i agree with @wintercn , pls think about it.@tw93 @Imlisten :)

**Comment by tw93** [comment]
@wintercn @Rowandjj @fromIRIS  
Considering that Tmall  and Aliyun  ISV will use this component ，I will do this in the next version of this downgrade, so that it will not affect the use of other，It will also be explained in the document

**Comment by marekchen** [comment]
@tw93  wxc-slider-bar also use expressionBinding.Maybe need star *wxc-slider-bar in the document?

**Comment by tw93** [comment]
@marekchen Thanks, I have updated it

**Comment by ada90** [comment]
你好，可以在业务层修改UI吗？

**Comment by am1102** [comment]
expression Binding 什么时候会支持呀？

**Comment by tw93** [comment]
@am1102  预计12月中下旬开源~

**Comment by Jevirs** [comment]
native的slider求滑动啊，求开源啊。。。

**Comment by am1102** [comment]
expression Binding 开源了吗？

**Comment by jessica1990** [comment]
Is  expression binding open source now? Which version of weex sdk?

**Comment by tw93** [comment]
![img_0952](https://user-images.githubusercontent.com/8736212/35368974-da61502c-01c0-11e8-9b4d-0a8b294199bd.JPG)

**Comment by phoenixsky** [comment]
I hope  one thousand  ten thousand don't  tiaopiao in feb   66666666

**Comment by tw93** [comment]
Binding is open source https://alibaba.github.io/bindingx/
