### ISSUE TITLE
searchbar组件theme= red无效

### ISSUE THREAD

**Issue by janxy** [alibaba/weex-ui#62]
使用searchbar组件的时候theme="yellow"有效，theme="red"无效，不知道为啥，，除了这些还有其他主题吗

**Comment by tw93** [comment]
目前只有正常的theme="gray" 和“yellow”  建议使用gray

**Comment by janxy** [comment]
tabbar组件会运行报错，tabpage就正常，为啥捏

**Comment by tw93** [comment]
贴一下详细错误

**Comment by janxy** [comment]
好的，要下班了，明早
