### ISSUE TITLE
关于wxc-page-calendar组件头部不显示问题

### ISSUE THREAD

**Issue by janxy** [alibaba/weex-ui#63]
> wxc-page-calendar组件在web下头部显示正常，在虚拟机和手机下头部不显示，如图：

![qq 20171130090259](https://user-images.githubusercontent.com/10809790/33407864-42cff364-d5ae-11e7-9fac-5d7ab0e911dd.png)
![qq 20171130090314](https://user-images.githubusercontent.com/10809790/33407865-4309f44c-d5ae-11e7-8914-49a1ac38f402.png)

set-nav.js，是不是原生的头部代码？在页面created里面都有执行setTitle('xxx');是不是就是定义他的头部名，，，可是为什么头部都没有显示呢，是不是要配置什么呢？

**Comment by tw93** [comment]
set-nav.js  用于设置导航栏的，setTitle('xxx');是定义他的头部title的
我给你加一个参数 稍等

**Comment by janxy** [comment]
请问下要加在哪里哦

**Comment by tw93** [comment]
直接npm i weex-ui@latest -S就是最新的哦
查看版本可以找到根目录下的node_modules/weex-ui/package.json 里面的version字段
```
<wxc-page-calendar   :show-header="true"></wxc-page-calendar>
```

**Comment by janxy** [comment]
选择日期title已显示，不过在返回按钮中的事件没有反应，
wxcPageCalendarBackClicked () {
        modal.toast({
          message: '你按了返回按钮'
        })
      },


===========================
那其他页面的set-nav.js ，setTitle('xxx');怎么让他显示呢？

**Comment by janxy** [comment]
wxc-page-calendar组件头部已显示，但是点击返回wxcPageCalendarBackClicked事件没有反应
==========================
第二个问题：set-nav.js ，setTitle('xxx'); 其他页面的头部如何显示？
![qq 20171130105022](https://user-images.githubusercontent.com/10809790/33410720-89f74e0a-d5bc-11e7-85a0-80cb4aabe18e.png)

**Comment by tw93** [comment]
是我的疏忽，已经修正，请更新到0.3.1
第二个问题：set-nav.js ，setTitle('xxx'); 其他页面的头部如何显示？ 这里需要客户端自己支持，相当于是navigatorBar module，weex自己去调用
