### ISSUE TITLE
拷贝wxc-tab-bar组件例子后报错，其他正常组件正常。

### ISSUE THREAD

**Issue by janxy** [alibaba/weex-ui#64]
index.web.js:3 Uncaught Error: Cannot find module "weex-ui/packages/wxc-tab-bar"

**Comment by tw93** [comment]
直接使用就好 不要拷贝哦

**Comment by janxy** [comment]
其他组件正常，唯独引用wxc-tab-bar报错
![qq 20171130095317](https://user-images.githubusercontent.com/10809790/33409043-5c38aa52-d5b4-11e7-96ac-5104db8cd082.png)
![qq 20171130095324](https://user-images.githubusercontent.com/10809790/33409044-5c6d8330-d5b4-11e7-8eac-7470d1693561.png)

**Comment by tw93** [comment]
组件更新到最新了吗

**Comment by janxy** [comment]
我也想过是这个问题啊，问下大神如何更新组件啊。

**Comment by janxy** [comment]
感谢大神，更新后恢复正常。
