### ISSUE TITLE
wxc-page-calendar组件底下会有一个大概header的距离显示不全

### ISSUE THREAD

**Issue by janxy** [alibaba/weex-ui#65]
![qq 20171130150447](https://user-images.githubusercontent.com/10809790/33418271-0cfed9a8-d5e0-11e7-9ee0-8d4fcca485e5.png)

**Comment by tw93** [comment]
weex.config.env.appName是什么哦

**Comment by janxy** [comment]
再下小白，有点不理解weex.config.env.appName什么意思。

**Comment by tw93** [comment]
![image](https://user-images.githubusercontent.com/8736212/33418910-0de1be96-d5e3-11e7-8861-ec46745c5a80.png)
扫码看看 截图给我~

**Comment by janxy** [comment]
![_20171130153024](https://user-images.githubusercontent.com/10809790/33418987-6f862f6a-d5e3-11e7-99ad-2f269ca8fd7b.jpg)

**Comment by tw93** [comment]
这里是将头隐藏了吗？ 我这边用playground看是好的哦

**Comment by janxy** [comment]
恩，是的，我没有头部，不知道怎么让他出来。可否教我下。

**Comment by tw93** [comment]
建议自己用native 写一个公共的头就好

**Comment by janxy** [comment]
set-nav.js这里就是公共的头部吧，页面也引用了。不晓得为啥他不显示，求助。

**Comment by tw93** [comment]
因为这个需要客户端支持呢，你这边需要自己弄哦
还有刚刚日历这个问题我修复了，优化了下支持各种无头情况
你运行下
npm i weex-ui@latest -S 
即可
