### ISSUE TITLE
tab-page组件运行会警告。vue.runtime.js:478 [Vue warn]: Cannot find element: #root

### ISSUE THREAD

**Issue by janxy** [alibaba/weex-ui#66]
页面运行正常，不知是否有其他影响
昨天好像没有这个告警。
 

![qq 20171130154154](https://user-images.githubusercontent.com/10809790/33419411-354a545a-d5e5-11e7-9a6d-b7296cd62cdf.jpg)

**Comment by tw93** [comment]
没影响 相当于组件自己指定了自己的入口，没有使用原来默认的

https://github.com/zwwill/yanxuan-weex-demo/pull/21
