### ISSUE TITLE
tabpage和tabbar的问题

### ISSUE THREAD

**Issue by janxy** [alibaba/weex-ui#68]
1：咨询下，tabpage和tabbar组件有什么区别？
我在tabpage下面直接把wxc-tab-page改成wxc-tab-bar照样也可以用切换不同的页面。
=======================================================
2：tabpage是否能tab放在底下呢，tabbar是否能把tab放在上面呢，这个是固定吗还是可以自定义的？
========================================================
3：tab图标下的字体用font-family改成其他字体好像都没有效果。

**Comment by tw93** [comment]
不建议直接改组件
这样其实违背了package的初心了
第一个问题 可以这样理解
第二个 不可以
第三个 font-family取决于客户端容器自己的支持哦  weex只是负责将这个参数传递给客户端
