### ISSUE TITLE
怎么在tabpage和tabbar的组件tab那个图标旁边加个小圆点或者数字标签

### ISSUE THREAD

**Issue by janxy** [alibaba/weex-ui#69]
如题

**Comment by tw93** [comment]
在weex 0.3.3 版本已经tabbar已经支持小红点和数字标签
详细可见 https://alibaba.github.io/weex-ui/#/cn/packages/wxc-tab-bar/
数据格式为https://github.com/alibaba/weex-ui/blob/master/example/tab-bar/config.js#L22
![image](https://user-images.githubusercontent.com/8736212/33659757-514212b6-dabc-11e7-8ab9-72bac2cd5def.png)

但是tabpage 属于标签页切换组件，暂时不打算将此使用频率很低参数加入
