### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by loocao** [alibaba/weex-ui#70]
`wxc-pan-item/index.vue`,`wxc-tab-page/index.vue`,`wxc-tab-bar/index.vue`
这三个组件中仍然使用的是`module.exports`方式，会导致`Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'`错误

**Comment by tw93** [comment]
收到， 谢谢反馈，马上更新~
