### ISSUE TITLE
能否在vue项目中使用？

### ISSUE THREAD

**Issue by mantou-kk** [alibaba/weex-ui#73]
如题！

**Comment by tw93** [comment]
weex-ui是使用vue的dsl实现的，也即在web降级上面是跑的vue的，这里涉及到weex-vue-render
假如想单纯在纯vue项目中使用，可以讲原有使用替换成这个试试

import { WxcComponent1, WxcComponent2 } from "weex-ui/build/index.web.js"

**Comment by NoraGithub** [comment]
@tw93 weex-ui 下没有build目录哦。请问怎么解决呢？
