### ISSUE TITLE
[wxc-popup] 浮层弹出时，在遮罩上上下滑动，能滑动后面的页面，期望不可以滑动

### ISSUE THREAD

**Issue by caiyongmin** [alibaba/weex-ui#74]
Before you start writing a issue,Please make sure [there](https://github.com/alibaba/weex-ui/issues?utf8=%E2%9C%93&q=) have not the same issue.

#### Your development environment（weex、weex-toolkit、system and more.）
```bash
weex -v
   v1.1.0-beta.1
 - weexpack : v0.4.7-beta.21
 - weex-builder : v0.2.13-beta.1
 - weex-devtool : v0.3.2-beta.7
 - weex-previewer : v1.3.13-beta.2
```

#### Expected behavior and actual behavior.
- 期望不可以滑动

#### Steps to reproduce the problem.
- 弹出层后面增加一个可以滚动的页面。
- 触发浮层弹出，在遮罩上上下滑动，会滑动后面的页面。

**Comment by tw93** [comment]
此问题暂时没有很好的解法

**Comment by zgs1108** [comment]
你好，请问有什么好的解决方案吗？ @tw93 @caiyongmin
