### ISSUE TITLE
安装依赖以后没有packages里面没有wex-tab-bar

### ISSUE THREAD

**Issue by githubOfyhw** [alibaba/weex-ui#75]
Before you start writing a issue,Please make sure [there](https://github.com/alibaba/weex-ui/issues?utf8=%E2%9C%93&q=) have not the same issue.

#### Your development environment（weex、weex-toolkit、system and more.）
- 
- 

#### Expected behavior and actual behavior.
- 
- 

#### Steps to reproduce the problem.
- 
-

**Comment by tw93** [comment]
npm i weex-ui@latest -S
