### ISSUE TITLE
npm run build后把dist文件夹直接放在tomcat上可以运行嘛？

### ISSUE THREAD

**Issue by janxy** [alibaba/weex-ui#77]
![qq 20171204180127](https://user-images.githubusercontent.com/10809790/33546906-460c0e7e-d91d-11e7-9e9d-7961d9148984.png)

**Comment by tw93** [comment]
你可以试试，把他当做一个cdn来处理
类似于这样的格式
https://h5.m.taobao.com/trip/weex-ui/index.html?_wx_tpl=https%3A%2F%2Fh5.m.taobao.com%2Ftrip%2Fweex-ui%2Fdemo%2Findex.native-min.js

**Comment by janxy** [comment]
有几个个疑问：
1：https://h5.m.taobao.com/trip/weex-ui/index.html这个是web访问地址嘛？我的项目根目录下没有index.html？
2：?_wx_tpl=https%3A%2F%2Fh5.m.taobao.com%2Ftrip%2Fweex-ui%2Fdemo%2Findex.native-min.js后面跟着的这个参数是给手机端打开的地址嘛？?
3：如果我的app是对于内部用，没有外网的话那么我的js是不是要跟着app一起打包？这样可以嘛

**Comment by tw93** [comment]
1，2 可以这么理解，项目根目录没有就自己加一个就好，可以参考weex ui example中的案例
为啥不放一个稳定在客户端，然后通过cdn动态更新，这样我认为可控点儿

**Comment by janxy** [comment]
按照这种做法直接把index.html和dist下面的文件夹放在tomcat上就可以运行了，这个是不是你说的做法？
 
![qq 20171205145815](https://user-images.githubusercontent.com/10809790/33593943-bc00e460-d9cc-11e7-991f-92f79cfe98ab.jpg)

**Comment by janxy** [comment]
\example中每个文件夹都有一个index.html才能供浏览器访问嘛？这样理解对嘛 ·？
那我是不是做h5项目的时候每个页面都要手动建一个index.html这个壳才能让浏览器访问，要么navigator.push打开js的话浏览器不支持解析。这样理解对嘛 ·？
https://h5.m.taobao.com/trip/weex-ui/index.html?_wx_tpl=http://192.168.0.195:8081/btn.js
前面的html供浏览器访问，后面参数js是手机端访问是这么理解嘛？

**Comment by tw93** [comment]
是的
