### ISSUE TITLE
weexpack 工程加weex-UI后报错

### ISSUE THREAD

**Issue by cgxking** [alibaba/weex-ui#84]
#### Your development environment（weex、weex-toolkit、system and more.）
weex  

#### Steps to reproduce the problem.

![image](https://user-images.githubusercontent.com/34331642/33701939-3292f75e-db5c-11e7-9d80-e28906b06b62.png)

**Comment by tw93** [comment]
详细可见 https://github.com/alibaba/weex-ui#weex-toolkit
