### ISSUE TITLE
Loading组件的菊花在安卓上不会转

### ISSUE THREAD

**Issue by Sunrise1970** [alibaba/weex-ui#85]
Before you start writing a issue,Please make sure [there](https://github.com/alibaba/weex-ui/issues?utf8=%E2%9C%93&q=) have not the same issue.

#### Your development environment（weex、weex-toolkit、system and more.）
- weex
- 红米手机note4x
- 安卓7.0

#### Expected behavior and actual behavior.
- Loading组件的菊花在安卓上会转

**Comment by tw93** [comment]
这个是图片库的需要支持，palyground的图片库是不支持的gif的，手淘的图片库的可以支持的，这个功能偏适配层，需要开发自己在自己的图片库实现

https://zhoukekestar.github.io/notes/2017/07/17/weex-gif.html
