### ISSUE TITLE
开发模式引入weex-ui组件报错SyntaxError: Unexpected keyword 'export'

### ISSUE THREAD

**Issue by chencl1986** [alibaba/weex-ui#86]
Before you start writing a issue,Please make sure [there](https://github.com/alibaba/weex-ui/issues?utf8=%E2%9C%93&q=) have not the same issue.

#### Your development environment（weex、weex-toolkit、system and more.）
 - windows7 & Mac OS 10.13
 - 小米6 & iPhone6s
 - npm v5.6.0
 - webpack v2.2.1
 - webpack-dev-server v2.4.2
 - weex -v  v1.1.0-beta.7
 - weexpack : v0.4.7-beta.26
 - weex-builder : v0.2.13-beta.6
 - weex-devtool : v0.3.2-beta.9
 - weex-previewer : v1.3.13-beta.13
 - weex-ui : v0.3.6

#### Expected behavior and actual behavior.
- 正常引入weex-ui组件不报错

#### Steps to reproduce the problem.
 - 代码如下：
<template>
  <div class="wrapper">
    <wxc-button text="确定"
          type="red"
         @wxcButtonClicked="jump"></wxc-button>
  </div>
</template>
<script>
  import { WxcButton } from 'weex-ui';
  export default {
    data() {
      return {}
    },
    components: { WxcButton },
    }
  }
</script>

 - webpack配置修改entry: { 'index': pathTo.resolve('src', 'entry.js') }

 - 运行npm run dev & npm run serve之后Web端正常。
 - 开启debug模式（weex debug src -e entry.js）后，手机通过Weex Playground扫描二维码后报错：

reportJSException >>>> instanceId:7, exception function:createInstance, exception:Exception: SyntaxError: Unexpected keyword 'export'
at (global function):3385
Function@[native code]
Function@[native code]
w@(weex framework):4:1545
a@(weex framework):3:30112
(weex framework):8:22648

PS：查阅了之前的Issue，尝试修改后依然报错。

**Comment by guixue** [comment]
@chencl1986  检查有没有执行：

 npm i babel-plugin-component -D

`// add a plugins setting to .babelrc
{
  "plugins": [
    [
      "component",
      {
        "libraryName": "weex-ui",
        "libDir": "packages"
      }
    ]
  ]
}`

**Comment by tw93** [comment]
You can refer to this document for more information <https://alibaba.github.io/weex-ui/#/docs/with-weex-toolkit>
About compatibility issues , @erha19 is In the optimization

**Comment by chencl1986** [comment]
@guixue @tw93 按照你们的说法都试过了，还是报错
reportJSException >>>> instanceId:15, exception function:createInstance, exception:Exception: SyntaxError: Unexpected keyword 'export'
at (global function):3146
Function@[native code]
Function@[native code]
w@(weex framework):4:1545
a@(weex framework):3:30112
(weex framework):8:22648

**Comment by chencl1986** [comment]
node -v
v8.2.1
npm --version
5.6.0
weex -v
   v1.1.0-beta.7
 - weexpack : v0.4.7-beta.26
 - weex-builder : v0.2.13-beta.6
 - weex-devtool : v0.3.2-beta.9
 - weex-previewer : v1.3.13-beta.13

**Comment by kangchangyuan** [comment]
同问，还是会报错

**Comment by tw93** [comment]
Run `weex update weex-devtool@0.3.2-beta.11` to update

**Comment by chencl1986** [comment]
@tw93 It's ok after update weex-devtool@0.3.2-beta.11.
I'll do more test.
Thanks.

**Comment by tw93** [comment]
Thank you for your feedback. If there is no problem, you can close this issue.
