### ISSUE TITLE
建议tab-bar上面的图标采用iconfont或者base64编码

### ISSUE THREAD

**Issue by tong3jie** [alibaba/weex-ui#87]

**Comment by tw93** [comment]
可以更新weex-ui到最新，目前已经支持配置iconfont
> npm i weex-ui@latest -S
详细设置可见
https://alibaba.github.io/weex-ui/#/cn/packages/wxc-tab-bar/?id=%e6%b3%a81%ef%bc%9a%e4%bd%bf%e7%94%a8-iconfont
