### ISSUE TITLE
tab-bar的计算高度是不是也有点问题

### ISSUE THREAD

**Issue by tong3jie** [alibaba/weex-ui#88]
手机终端：huawei mate9
![_20171212001115](https://user-images.githubusercontent.com/14191774/33840847-0679c292-ded1-11e7-91ae-1d5998169c57.jpg)

- 
-

**Comment by tw93** [comment]
Update the `weex-ui` to latest, I have fixed it in v0.3.7
And you don`t need post a `tabPageHeight` param, More you can see here https://alibaba.github.io/weex-ui/#/cn/packages/wxc-tab-bar/
> npm i weex-ui@latest -S
