### ISSUE TITLE
not work when set  modules to false in babelrc

### ISSUE THREAD

**Issue by lerit** [alibaba/weex-ui#9]
this is my babelrc:
`{
  "presets": [{ "es2015": {
          "modules": false
        }}, "stage-0"],
  "plugins": [
    [
      "component",
      {
        "libraryName": "weex-ui",
        "libDir": "packages"
      }
    ]
  ]
}`
it throw error:
![00](https://user-images.githubusercontent.com/4743467/31373833-1b1b50dc-adce-11e7-8f09-998a531cf24e.png)
i google this problem,and i guess the set modules=false cause this problem. does weex-ui component compat with this setting?
sorry for my poor vue and weex knowledge

**Comment by tw93** [comment]
Because it need to read the es6 source code below weex-ui  node_modules , so you need not set modules=false 😊
