### ISSUE TITLE
getPageHeight 在iOS中获取到的高度不正确

### ISSUE THREAD

**Issue by June0611** [alibaba/weex-ui#90]
getPageHeight 我看了下减去的是132,不应该是192 吗?iOS上面还有一个状态栏呢还是有别的用法呢,望解答,谢谢

**Comment by tw93** [comment]
非常建议在weex里面我们使用系统native 自己的navigatorBar 来实现

**Comment by June0611** [comment]
@tw93 您好,我使用的就是系统的navigationBar

**Comment by tw93** [comment]
soga  在大部分weex 容器中 其实都没有将状态栏放进去计算，假如有需要计算的场景建议自行实现就好哦
或者使用https://github.com/alibaba/weex-ui/blob/master/example/dialog/index.vue#L87

**Comment by June0611** [comment]
@tw93 谢谢!已采用其他方式布局
