### ISSUE TITLE
wxc-minibar改进建议

### ISSUE THREAD

**Issue by chencl1986** [alibaba/weex-ui#91]
根据使用wxc-minibar的情况，提几个修改建议：

1. 增加left-text配置，有时候设计的左边按钮不一定是Icon
2. 左右按钮都增加可自己定义Icon大小
3. Icon希望能支持Iconfont
4. 字体大小增加自定义配置

综述：目前在使用中，发现wxc-minibar的样式被限制，无法根据需求自定义，导致跟我现在项目的设计图极为不符。
建议参考蚂蚁金服的配置选项，它的导航栏，左右按钮都可以传入任意类型数据，如：文字、图片、SVG图标、Node
https://mobile.ant.design/components/nav-bar-cn/

**Comment by tw93** [comment]
you can update weex-ui to `0.3.9-beta`, I have add a param named `left-text`.
but When the above configurations are not satisfied, You can customize this component by using slot.
```
<wxc-minibar background-color="#FFF3CD">
  <image src="https://img.alicdn.com/tfs/TB1QN8pdlHH8KJjy0FbXXcqlpXa-220-80.png"
         slot="left"
         style="height: 32px;width: 88px;"></image>
  <text style="font-size: 40px;" slot="middle">Customize this component</text>
  <image slot="right"
         src="https://img.alicdn.com/tfs/TB1j39Uc0fJ8KJjy0FeXXXKEXXa-160-128.png"
         style="height: 32px;width: 40px"></image>
</wxc-minibar>
```
more you can see in here https://github.com/alibaba/weex-ui/blob/dev/packages/wxc-minibar/README.md#slot

**Comment by chencl1986** [comment]
Thank you~~

**Comment by tong3jie** [comment]
中文版也英文本的文档还有区别，掉渣天。下次看E文的吧。
