### ISSUE TITLE
内容滚动后头部保持固定是否有这样的组件

### ISSUE THREAD

**Issue by janxy** [alibaba/weex-ui#92]
例子里滚动到不可见区后红色区域固定是否有这样的组件
![qq 20171219145354](https://user-images.githubusercontent.com/10809790/34144556-f8f84bfa-e4cc-11e7-90cb-87e9514cf6b5.png)

**Comment by tw93** [comment]
直接使用list中的header就好
无需weex ui组件

**Comment by janxy** [comment]
好的，谢谢
