### ISSUE TITLE
建议设计icon的地方都可以设置iconfont模式，这样可以减少请求

### ISSUE THREAD

**Issue by tong3jie** [alibaba/weex-ui#94]
Before you start writing a issue,Please make sure [there](https://github.com/alibaba/weex-ui/issues?utf8=%E2%9C%93&q=) have not the same issue.

#### Your development environment（weex、weex-toolkit、system and more.）
- 
- 

#### Expected behavior and actual behavior.
- 
- 

#### Steps to reproduce the problem.
- 
-

**Comment by tw93** [comment]
这里的请求在客户端请求上面比起解析iconfont或者base64 的性能不算啥，目前大部分大icon是可以自定义成iconfont的，此处暂时应该不会修改。
