### ISSUE TITLE
wxc-tab-page和wxc-tab-bar有什么本质上的区别嘛？

### ISSUE THREAD

**Issue by janxy** [alibaba/weex-ui#95]
1；wxc-tab-page和wxc-tab-bar组件里面都可以放页面组件进行切换，
2；wxc-tab-page组件有几个不同的页面，假如10个，都是不一样的页面，每个页面都单独请求不一样的数据，那么是不是在启动app后就会同时的加载这10个页面和请求10个不同的数据，这样会不会影响速度和性能之类的呢·？
3；wxc-tab-page和wxc-tab-bar有什么本质上的区别嘛

**Comment by tw93** [comment]
第一个问题 本质区别：
- wxc-tab-page 属于tab在顶部，同时可以扩展多个（超过屏幕宽度）的tab头，常用语频道这种场景
- wxc-tab-bar 属于tab在底部，总宽度需保持在屏幕内，详细可见-
https://developer.apple.com/ios/human-interface-guidelines/bars/tab-bars/
- 为何弄两个组件：使用规范、交互量组件不一样，同时为了功能划分和后续的扩展

第二个问题 数据请求
- 可以同时请求，不过需要注意是分开渲染，到了这个页面再渲染，这样性能才不会受阻
- 也可以分开请求，等到切到页面后会有回调，然后再请求数据进行渲染
