### ISSUE TITLE
wxc-minibar can't show the right slot

### ISSUE THREAD

**Issue by chencl1986** [alibaba/weex-ui#97]
When I add a right slot like this:
      <image 
        class="nav-right"
        :src="imgUrl"
      />
If i use classname to control the style, slot can't be seen.
It showed after I change class to style.

      <image 
        style="width: 64px; height: 64px;"
        :src="imgUrl"
      />

version: weex-ui@0.3.9-beta1

**Comment by tw93** [comment]
Because of the vue property , Basically, you cannot modify the inserted content. You will have to wrap the slot in another element.
https://forum-archive.vuejs.org/topic/1316/how-can-i-properly-bind-a-class-to-the-slot/3
