### ISSUE TITLE
wxc-page-calendar组件问题

### ISSUE THREAD

**Issue by Shruan** [alibaba/weex-ui#98]
这个组件能不能再添加一个字段，让日期可以倒过来显示， 在选择过去时间到今天的时间的时候需要这个使用， 现在使用这个组件找到最新时间需要滚动到最下方才能选择

**Comment by tw93** [comment]
这样是不符合日历的情况的，主要是 星期、月份、日期的统一性，否则这就不像日历了，暂时不考虑加入此功能，可以和你们产品商量换一个更加通用方案
